// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `ISR` reader"]
pub struct R(crate::R<ISR_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<ISR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<ISR_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<ISR_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `DEDI` reader - Data Frame Interrupt Flag - DEDI"]
pub type DEDI_R = crate::BitReader<bool>;
#[doc = "Field `DECI` reader - Command Frame Interrupt Flag - DECI"]
pub type DECI_R = crate::BitReader<bool>;
#[doc = "Field `DTFI` reader - Time Frame Interrupt Flag - DTFI"]
pub type DTFI_R = crate::BitReader<bool>;
#[doc = "Field `URDI` reader - Receive Data Interrupt Flag - URDI"]
pub type URDI_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bit 0 - Data Frame Interrupt Flag - DEDI"]
    #[inline(always)]
    pub fn dedi(&self) -> DEDI_R {
        DEDI_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - Command Frame Interrupt Flag - DECI"]
    #[inline(always)]
    pub fn deci(&self) -> DECI_R {
        DECI_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - Time Frame Interrupt Flag - DTFI"]
    #[inline(always)]
    pub fn dtfi(&self) -> DTFI_R {
        DTFI_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - Receive Data Interrupt Flag - URDI"]
    #[inline(always)]
    pub fn urdi(&self) -> URDI_R {
        URDI_R::new(((self.bits >> 3) & 1) != 0)
    }
}
#[doc = "Interrupt Status Register\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [isr](index.html) module"]
pub struct ISR_SPEC;
impl crate::RegisterSpec for ISR_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [isr::R](R) reader structure"]
impl crate::Readable for ISR_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets ISR to value 0"]
impl crate::Resettable for ISR_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
