// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `EVFLAGCLR` writer"]
pub struct W(crate::W<EVFLAGCLR_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<EVFLAGCLR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<EVFLAGCLR_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<EVFLAGCLR_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `RESEC0` writer - Result Event Clear - RESEC0"]
pub type RESEC0_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAGCLR_SPEC, bool, O>;
#[doc = "Field `RESEC1` writer - Result Event Clear - RESEC1"]
pub type RESEC1_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAGCLR_SPEC, bool, O>;
#[doc = "Field `RESEC2` writer - Result Event Clear - RESEC2"]
pub type RESEC2_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAGCLR_SPEC, bool, O>;
#[doc = "Field `RESEC3` writer - Result Event Clear - RESEC3"]
pub type RESEC3_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAGCLR_SPEC, bool, O>;
#[doc = "Field `RESEC4` writer - Result Event Clear - RESEC4"]
pub type RESEC4_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAGCLR_SPEC, bool, O>;
#[doc = "Field `RESEC5` writer - Result Event Clear - RESEC5"]
pub type RESEC5_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAGCLR_SPEC, bool, O>;
#[doc = "Field `ALEC0` writer - Alarm Event Clear - ALEC0"]
pub type ALEC0_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAGCLR_SPEC, bool, O>;
#[doc = "Field `ALEC1` writer - Alarm Event Clear - ALEC1"]
pub type ALEC1_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAGCLR_SPEC, bool, O>;
#[doc = "Field `ALEC2` writer - Alarm Event Clear - ALEC2"]
pub type ALEC2_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAGCLR_SPEC, bool, O>;
#[doc = "Field `ALEC3` writer - Alarm Event Clear - ALEC3"]
pub type ALEC3_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAGCLR_SPEC, bool, O>;
#[doc = "Field `ALEC4` writer - Alarm Event Clear - ALEC4"]
pub type ALEC4_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAGCLR_SPEC, bool, O>;
#[doc = "Field `ALEC5` writer - Alarm Event Clear - ALEC5"]
pub type ALEC5_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAGCLR_SPEC, bool, O>;
impl W {
    #[doc = "Bit 0 - Result Event Clear - RESEC0"]
    #[inline(always)]
    #[must_use]
    pub fn resec0(&mut self) -> RESEC0_W<0> {
        RESEC0_W::new(self)
    }
    #[doc = "Bit 1 - Result Event Clear - RESEC1"]
    #[inline(always)]
    #[must_use]
    pub fn resec1(&mut self) -> RESEC1_W<1> {
        RESEC1_W::new(self)
    }
    #[doc = "Bit 2 - Result Event Clear - RESEC2"]
    #[inline(always)]
    #[must_use]
    pub fn resec2(&mut self) -> RESEC2_W<2> {
        RESEC2_W::new(self)
    }
    #[doc = "Bit 3 - Result Event Clear - RESEC3"]
    #[inline(always)]
    #[must_use]
    pub fn resec3(&mut self) -> RESEC3_W<3> {
        RESEC3_W::new(self)
    }
    #[doc = "Bit 4 - Result Event Clear - RESEC4"]
    #[inline(always)]
    #[must_use]
    pub fn resec4(&mut self) -> RESEC4_W<4> {
        RESEC4_W::new(self)
    }
    #[doc = "Bit 5 - Result Event Clear - RESEC5"]
    #[inline(always)]
    #[must_use]
    pub fn resec5(&mut self) -> RESEC5_W<5> {
        RESEC5_W::new(self)
    }
    #[doc = "Bit 16 - Alarm Event Clear - ALEC0"]
    #[inline(always)]
    #[must_use]
    pub fn alec0(&mut self) -> ALEC0_W<16> {
        ALEC0_W::new(self)
    }
    #[doc = "Bit 17 - Alarm Event Clear - ALEC1"]
    #[inline(always)]
    #[must_use]
    pub fn alec1(&mut self) -> ALEC1_W<17> {
        ALEC1_W::new(self)
    }
    #[doc = "Bit 18 - Alarm Event Clear - ALEC2"]
    #[inline(always)]
    #[must_use]
    pub fn alec2(&mut self) -> ALEC2_W<18> {
        ALEC2_W::new(self)
    }
    #[doc = "Bit 19 - Alarm Event Clear - ALEC3"]
    #[inline(always)]
    #[must_use]
    pub fn alec3(&mut self) -> ALEC3_W<19> {
        ALEC3_W::new(self)
    }
    #[doc = "Bit 20 - Alarm Event Clear - ALEC4"]
    #[inline(always)]
    #[must_use]
    pub fn alec4(&mut self) -> ALEC4_W<20> {
        ALEC4_W::new(self)
    }
    #[doc = "Bit 21 - Alarm Event Clear - ALEC5"]
    #[inline(always)]
    #[must_use]
    pub fn alec5(&mut self) -> ALEC5_W<21> {
        ALEC5_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Event Flag Clear Register\n\nThis register you can [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [evflagclr](index.html) module"]
pub struct EVFLAGCLR_SPEC;
impl crate::RegisterSpec for EVFLAGCLR_SPEC {
    type Ux = u32;
}
#[doc = "`write(|w| ..)` method takes [evflagclr::W](W) writer structure"]
impl crate::Writable for EVFLAGCLR_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets EVFLAGCLR to value 0"]
impl crate::Resettable for EVFLAGCLR_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
