// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `EVFLAG` reader"]
pub struct R(crate::R<EVFLAG_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<EVFLAG_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<EVFLAG_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<EVFLAG_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `EVFLAG` writer"]
pub struct W(crate::W<EVFLAG_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<EVFLAG_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<EVFLAG_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<EVFLAG_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `RESEV0` reader - Result Event - RESEV0"]
pub type RESEV0_R = crate::BitReader<bool>;
#[doc = "Field `RESEV0` writer - Result Event - RESEV0"]
pub type RESEV0_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAG_SPEC, bool, O>;
#[doc = "Field `RESEV1` reader - Result Event - RESEV1"]
pub type RESEV1_R = crate::BitReader<bool>;
#[doc = "Field `RESEV1` writer - Result Event - RESEV1"]
pub type RESEV1_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAG_SPEC, bool, O>;
#[doc = "Field `RESEV2` reader - Result Event - RESEV2"]
pub type RESEV2_R = crate::BitReader<bool>;
#[doc = "Field `RESEV2` writer - Result Event - RESEV2"]
pub type RESEV2_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAG_SPEC, bool, O>;
#[doc = "Field `RESEV3` reader - Result Event - RESEV3"]
pub type RESEV3_R = crate::BitReader<bool>;
#[doc = "Field `RESEV3` writer - Result Event - RESEV3"]
pub type RESEV3_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAG_SPEC, bool, O>;
#[doc = "Field `RESEV4` reader - Result Event - RESEV4"]
pub type RESEV4_R = crate::BitReader<bool>;
#[doc = "Field `RESEV4` writer - Result Event - RESEV4"]
pub type RESEV4_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAG_SPEC, bool, O>;
#[doc = "Field `RESEV5` reader - Result Event - RESEV5"]
pub type RESEV5_R = crate::BitReader<bool>;
#[doc = "Field `RESEV5` writer - Result Event - RESEV5"]
pub type RESEV5_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAG_SPEC, bool, O>;
#[doc = "Field `ALEV0` reader - Alarm Event - ALEV0"]
pub type ALEV0_R = crate::BitReader<bool>;
#[doc = "Field `ALEV0` writer - Alarm Event - ALEV0"]
pub type ALEV0_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAG_SPEC, bool, O>;
#[doc = "Field `ALEV1` reader - Alarm Event - ALEV1"]
pub type ALEV1_R = crate::BitReader<bool>;
#[doc = "Field `ALEV1` writer - Alarm Event - ALEV1"]
pub type ALEV1_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAG_SPEC, bool, O>;
#[doc = "Field `ALEV2` reader - Alarm Event - ALEV2"]
pub type ALEV2_R = crate::BitReader<bool>;
#[doc = "Field `ALEV2` writer - Alarm Event - ALEV2"]
pub type ALEV2_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAG_SPEC, bool, O>;
#[doc = "Field `ALEV3` reader - Alarm Event - ALEV3"]
pub type ALEV3_R = crate::BitReader<bool>;
#[doc = "Field `ALEV3` writer - Alarm Event - ALEV3"]
pub type ALEV3_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAG_SPEC, bool, O>;
#[doc = "Field `ALEV4` reader - Alarm Event - ALEV4"]
pub type ALEV4_R = crate::BitReader<bool>;
#[doc = "Field `ALEV4` writer - Alarm Event - ALEV4"]
pub type ALEV4_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAG_SPEC, bool, O>;
#[doc = "Field `ALEV5` reader - Alarm Event - ALEV5"]
pub type ALEV5_R = crate::BitReader<bool>;
#[doc = "Field `ALEV5` writer - Alarm Event - ALEV5"]
pub type ALEV5_W<'a, const O: u8> = crate::BitWriter<'a, u32, EVFLAG_SPEC, bool, O>;
impl R {
    #[doc = "Bit 0 - Result Event - RESEV0"]
    #[inline(always)]
    pub fn resev0(&self) -> RESEV0_R {
        RESEV0_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - Result Event - RESEV1"]
    #[inline(always)]
    pub fn resev1(&self) -> RESEV1_R {
        RESEV1_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - Result Event - RESEV2"]
    #[inline(always)]
    pub fn resev2(&self) -> RESEV2_R {
        RESEV2_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - Result Event - RESEV3"]
    #[inline(always)]
    pub fn resev3(&self) -> RESEV3_R {
        RESEV3_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 4 - Result Event - RESEV4"]
    #[inline(always)]
    pub fn resev4(&self) -> RESEV4_R {
        RESEV4_R::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 5 - Result Event - RESEV5"]
    #[inline(always)]
    pub fn resev5(&self) -> RESEV5_R {
        RESEV5_R::new(((self.bits >> 5) & 1) != 0)
    }
    #[doc = "Bit 16 - Alarm Event - ALEV0"]
    #[inline(always)]
    pub fn alev0(&self) -> ALEV0_R {
        ALEV0_R::new(((self.bits >> 16) & 1) != 0)
    }
    #[doc = "Bit 17 - Alarm Event - ALEV1"]
    #[inline(always)]
    pub fn alev1(&self) -> ALEV1_R {
        ALEV1_R::new(((self.bits >> 17) & 1) != 0)
    }
    #[doc = "Bit 18 - Alarm Event - ALEV2"]
    #[inline(always)]
    pub fn alev2(&self) -> ALEV2_R {
        ALEV2_R::new(((self.bits >> 18) & 1) != 0)
    }
    #[doc = "Bit 19 - Alarm Event - ALEV3"]
    #[inline(always)]
    pub fn alev3(&self) -> ALEV3_R {
        ALEV3_R::new(((self.bits >> 19) & 1) != 0)
    }
    #[doc = "Bit 20 - Alarm Event - ALEV4"]
    #[inline(always)]
    pub fn alev4(&self) -> ALEV4_R {
        ALEV4_R::new(((self.bits >> 20) & 1) != 0)
    }
    #[doc = "Bit 21 - Alarm Event - ALEV5"]
    #[inline(always)]
    pub fn alev5(&self) -> ALEV5_R {
        ALEV5_R::new(((self.bits >> 21) & 1) != 0)
    }
}
impl W {
    #[doc = "Bit 0 - Result Event - RESEV0"]
    #[inline(always)]
    #[must_use]
    pub fn resev0(&mut self) -> RESEV0_W<0> {
        RESEV0_W::new(self)
    }
    #[doc = "Bit 1 - Result Event - RESEV1"]
    #[inline(always)]
    #[must_use]
    pub fn resev1(&mut self) -> RESEV1_W<1> {
        RESEV1_W::new(self)
    }
    #[doc = "Bit 2 - Result Event - RESEV2"]
    #[inline(always)]
    #[must_use]
    pub fn resev2(&mut self) -> RESEV2_W<2> {
        RESEV2_W::new(self)
    }
    #[doc = "Bit 3 - Result Event - RESEV3"]
    #[inline(always)]
    #[must_use]
    pub fn resev3(&mut self) -> RESEV3_W<3> {
        RESEV3_W::new(self)
    }
    #[doc = "Bit 4 - Result Event - RESEV4"]
    #[inline(always)]
    #[must_use]
    pub fn resev4(&mut self) -> RESEV4_W<4> {
        RESEV4_W::new(self)
    }
    #[doc = "Bit 5 - Result Event - RESEV5"]
    #[inline(always)]
    #[must_use]
    pub fn resev5(&mut self) -> RESEV5_W<5> {
        RESEV5_W::new(self)
    }
    #[doc = "Bit 16 - Alarm Event - ALEV0"]
    #[inline(always)]
    #[must_use]
    pub fn alev0(&mut self) -> ALEV0_W<16> {
        ALEV0_W::new(self)
    }
    #[doc = "Bit 17 - Alarm Event - ALEV1"]
    #[inline(always)]
    #[must_use]
    pub fn alev1(&mut self) -> ALEV1_W<17> {
        ALEV1_W::new(self)
    }
    #[doc = "Bit 18 - Alarm Event - ALEV2"]
    #[inline(always)]
    #[must_use]
    pub fn alev2(&mut self) -> ALEV2_W<18> {
        ALEV2_W::new(self)
    }
    #[doc = "Bit 19 - Alarm Event - ALEV3"]
    #[inline(always)]
    #[must_use]
    pub fn alev3(&mut self) -> ALEV3_W<19> {
        ALEV3_W::new(self)
    }
    #[doc = "Bit 20 - Alarm Event - ALEV4"]
    #[inline(always)]
    #[must_use]
    pub fn alev4(&mut self) -> ALEV4_W<20> {
        ALEV4_W::new(self)
    }
    #[doc = "Bit 21 - Alarm Event - ALEV5"]
    #[inline(always)]
    #[must_use]
    pub fn alev5(&mut self) -> ALEV5_W<21> {
        ALEV5_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Event Flag Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [evflag](index.html) module"]
pub struct EVFLAG_SPEC;
impl crate::RegisterSpec for EVFLAG_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [evflag::R](R) reader structure"]
impl crate::Readable for EVFLAG_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [evflag::W](W) writer structure"]
impl crate::Writable for EVFLAG_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets EVFLAG to value 0"]
impl crate::Resettable for EVFLAG_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
