// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `ENDADR3` reader"]
pub struct R(crate::R<ENDADR3_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<ENDADR3_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<ENDADR3_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<ENDADR3_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `ENDADR3` writer"]
pub struct W(crate::W<ENDADR3_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<ENDADR3_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<ENDADR3_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<ENDADR3_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `END` reader - Message RAM end - END"]
pub type END_R = crate::FieldReader<u16, u16>;
#[doc = "Field `END` writer - Message RAM end - END"]
pub type END_W<'a, const O: u8> = crate::FieldWriter<'a, u32, ENDADR3_SPEC, u16, u16, 14, O>;
impl R {
    #[doc = "Bits 2:15 - Message RAM end - END"]
    #[inline(always)]
    pub fn end(&self) -> END_R {
        END_R::new(((self.bits >> 2) & 0x3fff) as u16)
    }
}
impl W {
    #[doc = "Bits 2:15 - Message RAM end - END"]
    #[inline(always)]
    #[must_use]
    pub fn end(&mut self) -> END_W<2> {
        END_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "End Address Node 3\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [endadr3](index.html) module"]
pub struct ENDADR3_SPEC;
impl crate::RegisterSpec for ENDADR3_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [endadr3::R](R) reader structure"]
impl crate::Readable for ENDADR3_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [endadr3::W](W) writer structure"]
impl crate::Writable for ENDADR3_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets ENDADR3 to value 0"]
impl crate::Resettable for ENDADR3_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
