// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `MCR` reader"]
pub struct R(crate::R<MCR_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<MCR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<MCR_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<MCR_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `MCR` writer"]
pub struct W(crate::W<MCR_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<MCR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<MCR_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<MCR_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `CLKSEL0` reader - Clock Select 0 - CLKSEL0"]
pub type CLKSEL0_R = crate::FieldReader<u8, u8>;
#[doc = "Field `CLKSEL0` writer - Clock Select 0 - CLKSEL0"]
pub type CLKSEL0_W<'a, const O: u8> = crate::FieldWriter<'a, u32, MCR_SPEC, u8, u8, 2, O>;
#[doc = "Field `CLKSEL1` reader - Clock Select 1 - CLKSEL1"]
pub type CLKSEL1_R = crate::FieldReader<u8, u8>;
#[doc = "Field `CLKSEL1` writer - Clock Select 1 - CLKSEL1"]
pub type CLKSEL1_W<'a, const O: u8> = crate::FieldWriter<'a, u32, MCR_SPEC, u8, u8, 2, O>;
#[doc = "Field `CLKSEL2` reader - Clock Select 2 - CLKSEL2"]
pub type CLKSEL2_R = crate::FieldReader<u8, u8>;
#[doc = "Field `CLKSEL2` writer - Clock Select 2 - CLKSEL2"]
pub type CLKSEL2_W<'a, const O: u8> = crate::FieldWriter<'a, u32, MCR_SPEC, u8, u8, 2, O>;
#[doc = "Field `CLKSEL3` reader - Clock Select 3 - CLKSEL3"]
pub type CLKSEL3_R = crate::FieldReader<u8, u8>;
#[doc = "Field `CLKSEL3` writer - Clock Select 3 - CLKSEL3"]
pub type CLKSEL3_W<'a, const O: u8> = crate::FieldWriter<'a, u32, MCR_SPEC, u8, u8, 2, O>;
#[doc = "Field `NODE` reader - Node - NODE"]
pub type NODE_R = crate::FieldReader<u8, u8>;
#[doc = "Field `NODE` writer - Node - NODE"]
pub type NODE_W<'a, const O: u8> = crate::FieldWriter<'a, u32, MCR_SPEC, u8, u8, 3, O>;
#[doc = "Field `DXCM` reader - Debug Over CAN Messages Enable - DXCM"]
pub type DXCM_R = crate::BitReader<bool>;
#[doc = "Field `DXCM` writer - Debug Over CAN Messages Enable - DXCM"]
pub type DXCM_W<'a, const O: u8> = crate::BitWriter<'a, u32, MCR_SPEC, bool, O>;
#[doc = "Field `RBUSY` reader - RAM BUSY - RBUSY"]
pub type RBUSY_R = crate::BitReader<bool>;
#[doc = "Field `RINIT` reader - RAM Init - RINIT"]
pub type RINIT_R = crate::BitReader<bool>;
#[doc = "Field `RINIT` writer - RAM Init - RINIT"]
pub type RINIT_W<'a, const O: u8> = crate::BitWriter<'a, u32, MCR_SPEC, bool, O>;
#[doc = "Field `CI` reader - Change Init - CI"]
pub type CI_R = crate::BitReader<bool>;
#[doc = "Field `CI` writer - Change Init - CI"]
pub type CI_W<'a, const O: u8> = crate::BitWriter<'a, u32, MCR_SPEC, bool, O>;
#[doc = "Field `CCCE` reader - Clock and RAM Change Enable - CCCE"]
pub type CCCE_R = crate::BitReader<bool>;
#[doc = "Field `CCCE` writer - Clock and RAM Change Enable - CCCE"]
pub type CCCE_W<'a, const O: u8> = crate::BitWriter<'a, u32, MCR_SPEC, bool, O>;
impl R {
    #[doc = "Bits 0:1 - Clock Select 0 - CLKSEL0"]
    #[inline(always)]
    pub fn clksel0(&self) -> CLKSEL0_R {
        CLKSEL0_R::new((self.bits & 3) as u8)
    }
    #[doc = "Bits 2:3 - Clock Select 1 - CLKSEL1"]
    #[inline(always)]
    pub fn clksel1(&self) -> CLKSEL1_R {
        CLKSEL1_R::new(((self.bits >> 2) & 3) as u8)
    }
    #[doc = "Bits 4:5 - Clock Select 2 - CLKSEL2"]
    #[inline(always)]
    pub fn clksel2(&self) -> CLKSEL2_R {
        CLKSEL2_R::new(((self.bits >> 4) & 3) as u8)
    }
    #[doc = "Bits 6:7 - Clock Select 3 - CLKSEL3"]
    #[inline(always)]
    pub fn clksel3(&self) -> CLKSEL3_R {
        CLKSEL3_R::new(((self.bits >> 6) & 3) as u8)
    }
    #[doc = "Bits 24:26 - Node - NODE"]
    #[inline(always)]
    pub fn node(&self) -> NODE_R {
        NODE_R::new(((self.bits >> 24) & 7) as u8)
    }
    #[doc = "Bit 27 - Debug Over CAN Messages Enable - DXCM"]
    #[inline(always)]
    pub fn dxcm(&self) -> DXCM_R {
        DXCM_R::new(((self.bits >> 27) & 1) != 0)
    }
    #[doc = "Bit 28 - RAM BUSY - RBUSY"]
    #[inline(always)]
    pub fn rbusy(&self) -> RBUSY_R {
        RBUSY_R::new(((self.bits >> 28) & 1) != 0)
    }
    #[doc = "Bit 29 - RAM Init - RINIT"]
    #[inline(always)]
    pub fn rinit(&self) -> RINIT_R {
        RINIT_R::new(((self.bits >> 29) & 1) != 0)
    }
    #[doc = "Bit 30 - Change Init - CI"]
    #[inline(always)]
    pub fn ci(&self) -> CI_R {
        CI_R::new(((self.bits >> 30) & 1) != 0)
    }
    #[doc = "Bit 31 - Clock and RAM Change Enable - CCCE"]
    #[inline(always)]
    pub fn ccce(&self) -> CCCE_R {
        CCCE_R::new(((self.bits >> 31) & 1) != 0)
    }
}
impl W {
    #[doc = "Bits 0:1 - Clock Select 0 - CLKSEL0"]
    #[inline(always)]
    #[must_use]
    pub fn clksel0(&mut self) -> CLKSEL0_W<0> {
        CLKSEL0_W::new(self)
    }
    #[doc = "Bits 2:3 - Clock Select 1 - CLKSEL1"]
    #[inline(always)]
    #[must_use]
    pub fn clksel1(&mut self) -> CLKSEL1_W<2> {
        CLKSEL1_W::new(self)
    }
    #[doc = "Bits 4:5 - Clock Select 2 - CLKSEL2"]
    #[inline(always)]
    #[must_use]
    pub fn clksel2(&mut self) -> CLKSEL2_W<4> {
        CLKSEL2_W::new(self)
    }
    #[doc = "Bits 6:7 - Clock Select 3 - CLKSEL3"]
    #[inline(always)]
    #[must_use]
    pub fn clksel3(&mut self) -> CLKSEL3_W<6> {
        CLKSEL3_W::new(self)
    }
    #[doc = "Bits 24:26 - Node - NODE"]
    #[inline(always)]
    #[must_use]
    pub fn node(&mut self) -> NODE_W<24> {
        NODE_W::new(self)
    }
    #[doc = "Bit 27 - Debug Over CAN Messages Enable - DXCM"]
    #[inline(always)]
    #[must_use]
    pub fn dxcm(&mut self) -> DXCM_W<27> {
        DXCM_W::new(self)
    }
    #[doc = "Bit 29 - RAM Init - RINIT"]
    #[inline(always)]
    #[must_use]
    pub fn rinit(&mut self) -> RINIT_W<29> {
        RINIT_W::new(self)
    }
    #[doc = "Bit 30 - Change Init - CI"]
    #[inline(always)]
    #[must_use]
    pub fn ci(&mut self) -> CI_W<30> {
        CI_W::new(self)
    }
    #[doc = "Bit 31 - Clock and RAM Change Enable - CCCE"]
    #[inline(always)]
    #[must_use]
    pub fn ccce(&mut self) -> CCCE_W<31> {
        CCCE_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Module Control Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [mcr](index.html) module"]
pub struct MCR_SPEC;
impl crate::RegisterSpec for MCR_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [mcr::R](R) reader structure"]
impl crate::Readable for MCR_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [mcr::W](W) writer structure"]
impl crate::Writable for MCR_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets MCR to value 0"]
impl crate::Resettable for MCR_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
