// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `TTCR0` reader"]
pub struct R(crate::R<TTCR0_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<TTCR0_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<TTCR0_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<TTCR0_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `TTCR0` writer"]
pub struct W(crate::W<TTCR0_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<TTCR0_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<TTCR0_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<TTCR0_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `ETESEL` reader - External Trigger Event Selection - ETESEL"]
pub type ETESEL_R = crate::FieldReader<u8, u8>;
#[doc = "Field `ETESEL` writer - External Trigger Event Selection - ETESEL"]
pub type ETESEL_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TTCR0_SPEC, u8, u8, 2, O>;
#[doc = "Field `ETSSEL` reader - External Trigger Source Selection - ETSSEL"]
pub type ETSSEL_R = crate::FieldReader<u8, u8>;
#[doc = "Field `ETSSEL` writer - External Trigger Source Selection - ETSSEL"]
pub type ETSSEL_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TTCR0_SPEC, u8, u8, 3, O>;
#[doc = "Field `TTCTSS` reader - TTCapture Time Trigger Source Select - TTCTSS"]
pub type TTCTSS_R = crate::FieldReader<u8, u8>;
#[doc = "Field `TTCTSS` writer - TTCapture Time Trigger Source Select - TTCTSS"]
pub type TTCTSS_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TTCR0_SPEC, u8, u8, 3, O>;
impl R {
    #[doc = "Bits 2:3 - External Trigger Event Selection - ETESEL"]
    #[inline(always)]
    pub fn etesel(&self) -> ETESEL_R {
        ETESEL_R::new(((self.bits >> 2) & 3) as u8)
    }
    #[doc = "Bits 4:6 - External Trigger Source Selection - ETSSEL"]
    #[inline(always)]
    pub fn etssel(&self) -> ETSSEL_R {
        ETSSEL_R::new(((self.bits >> 4) & 7) as u8)
    }
    #[doc = "Bits 9:11 - TTCapture Time Trigger Source Select - TTCTSS"]
    #[inline(always)]
    pub fn ttctss(&self) -> TTCTSS_R {
        TTCTSS_R::new(((self.bits >> 9) & 7) as u8)
    }
}
impl W {
    #[doc = "Bits 2:3 - External Trigger Event Selection - ETESEL"]
    #[inline(always)]
    #[must_use]
    pub fn etesel(&mut self) -> ETESEL_W<2> {
        ETESEL_W::new(self)
    }
    #[doc = "Bits 4:6 - External Trigger Source Selection - ETSSEL"]
    #[inline(always)]
    #[must_use]
    pub fn etssel(&mut self) -> ETSSEL_W<4> {
        ETSSEL_W::new(self)
    }
    #[doc = "Bits 9:11 - TTCapture Time Trigger Source Select - TTCTSS"]
    #[inline(always)]
    #[must_use]
    pub fn ttctss(&mut self) -> TTCTSS_W<9> {
        TTCTSS_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Time Trigger Control Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [ttcr0](index.html) module"]
pub struct TTCR0_SPEC;
impl crate::RegisterSpec for TTCR0_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [ttcr0::R](R) reader structure"]
impl crate::Readable for TTCR0_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [ttcr0::W](W) writer structure"]
impl crate::Writable for TTCR0_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets TTCR0 to value 0"]
impl crate::Resettable for TTCR0_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
