// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `TTTMK0` reader"]
pub struct R(crate::R<TTTMK0_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<TTTMK0_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<TTTMK0_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<TTTMK0_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `TTTMK0` writer"]
pub struct W(crate::W<TTTMK0_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<TTTMK0_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<TTTMK0_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<TTTMK0_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `TM` reader - Time Mark - TM"]
pub type TM_R = crate::FieldReader<u16, u16>;
#[doc = "Field `TM` writer - Time Mark - TM"]
pub type TM_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TTTMK0_SPEC, u16, u16, 16, O>;
#[doc = "Field `TICC` reader - Time Mark Cycle Code - TICC"]
pub type TICC_R = crate::FieldReader<u8, u8>;
#[doc = "Field `TICC` writer - Time Mark Cycle Code - TICC"]
pub type TICC_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TTTMK0_SPEC, u8, u8, 7, O>;
#[doc = "Field `LCKM` reader - TT Time Mark Register Locked - LCKM"]
pub type LCKM_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bits 0:15 - Time Mark - TM"]
    #[inline(always)]
    pub fn tm(&self) -> TM_R {
        TM_R::new((self.bits & 0xffff) as u16)
    }
    #[doc = "Bits 16:22 - Time Mark Cycle Code - TICC"]
    #[inline(always)]
    pub fn ticc(&self) -> TICC_R {
        TICC_R::new(((self.bits >> 16) & 0x7f) as u8)
    }
    #[doc = "Bit 31 - TT Time Mark Register Locked - LCKM"]
    #[inline(always)]
    pub fn lckm(&self) -> LCKM_R {
        LCKM_R::new(((self.bits >> 31) & 1) != 0)
    }
}
impl W {
    #[doc = "Bits 0:15 - Time Mark - TM"]
    #[inline(always)]
    #[must_use]
    pub fn tm(&mut self) -> TM_W<0> {
        TM_W::new(self)
    }
    #[doc = "Bits 16:22 - Time Mark Cycle Code - TICC"]
    #[inline(always)]
    #[must_use]
    pub fn ticc(&mut self) -> TICC_W<16> {
        TICC_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "TT Time Mark 0\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [tttmk0](index.html) module"]
pub struct TTTMK0_SPEC;
impl crate::RegisterSpec for TTTMK0_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [tttmk0::R](R) reader structure"]
impl crate::Readable for TTTMK0_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [tttmk0::W](W) writer structure"]
impl crate::Writable for TTTMK0_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets TTTMK0 to value 0"]
impl crate::Resettable for TTTMK0_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
