// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `PISEL` reader"]
pub struct R(crate::R<PISEL_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<PISEL_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<PISEL_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<PISEL_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `PISEL` writer"]
pub struct W(crate::W<PISEL_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<PISEL_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<PISEL_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<PISEL_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `IST2IN` reader - Input Select for T2IN - IST2IN"]
pub type IST2IN_R = crate::BitReader<bool>;
#[doc = "Field `IST2IN` writer - Input Select for T2IN - IST2IN"]
pub type IST2IN_W<'a, const O: u8> = crate::BitWriter<'a, u32, PISEL_SPEC, bool, O>;
#[doc = "Field `IST2EUD` reader - Input Select for T2EUD - IST2EUD"]
pub type IST2EUD_R = crate::BitReader<bool>;
#[doc = "Field `IST2EUD` writer - Input Select for T2EUD - IST2EUD"]
pub type IST2EUD_W<'a, const O: u8> = crate::BitWriter<'a, u32, PISEL_SPEC, bool, O>;
#[doc = "Field `IST3IN` reader - Input Select for T3IN - IST3IN"]
pub type IST3IN_R = crate::FieldReader<u8, u8>;
#[doc = "Field `IST3IN` writer - Input Select for T3IN - IST3IN"]
pub type IST3IN_W<'a, const O: u8> = crate::FieldWriter<'a, u32, PISEL_SPEC, u8, u8, 2, O>;
#[doc = "Field `IST3EUD` reader - Input Select for T3EUD - IST3EUD"]
pub type IST3EUD_R = crate::FieldReader<u8, u8>;
#[doc = "Field `IST3EUD` writer - Input Select for T3EUD - IST3EUD"]
pub type IST3EUD_W<'a, const O: u8> = crate::FieldWriter<'a, u32, PISEL_SPEC, u8, u8, 2, O>;
#[doc = "Field `IST4IN` reader - Input Select for T4IN - IST4IN"]
pub type IST4IN_R = crate::FieldReader<u8, u8>;
#[doc = "Field `IST4IN` writer - Input Select for T4IN - IST4IN"]
pub type IST4IN_W<'a, const O: u8> = crate::FieldWriter<'a, u32, PISEL_SPEC, u8, u8, 2, O>;
#[doc = "Field `IST4EUD` reader - Input Select for T4EUD - IST4EUD"]
pub type IST4EUD_R = crate::FieldReader<u8, u8>;
#[doc = "Field `IST4EUD` writer - Input Select for T4EUD - IST4EUD"]
pub type IST4EUD_W<'a, const O: u8> = crate::FieldWriter<'a, u32, PISEL_SPEC, u8, u8, 2, O>;
#[doc = "Field `IST5IN` reader - Input Select for T5IN - IST5IN"]
pub type IST5IN_R = crate::BitReader<bool>;
#[doc = "Field `IST5IN` writer - Input Select for T5IN - IST5IN"]
pub type IST5IN_W<'a, const O: u8> = crate::BitWriter<'a, u32, PISEL_SPEC, bool, O>;
#[doc = "Field `IST5EUD` reader - Input Select for T5EUD - IST5EUD"]
pub type IST5EUD_R = crate::BitReader<bool>;
#[doc = "Field `IST5EUD` writer - Input Select for T5EUD - IST5EUD"]
pub type IST5EUD_W<'a, const O: u8> = crate::BitWriter<'a, u32, PISEL_SPEC, bool, O>;
#[doc = "Field `IST6IN` reader - Input Select for T6IN - IST6IN"]
pub type IST6IN_R = crate::BitReader<bool>;
#[doc = "Field `IST6IN` writer - Input Select for T6IN - IST6IN"]
pub type IST6IN_W<'a, const O: u8> = crate::BitWriter<'a, u32, PISEL_SPEC, bool, O>;
#[doc = "Field `IST6EUD` reader - Input Select for T6EUD - IST6EUD"]
pub type IST6EUD_R = crate::BitReader<bool>;
#[doc = "Field `IST6EUD` writer - Input Select for T6EUD - IST6EUD"]
pub type IST6EUD_W<'a, const O: u8> = crate::BitWriter<'a, u32, PISEL_SPEC, bool, O>;
#[doc = "Field `ISCAPIN` reader - Input Select for CAPIN - ISCAPIN"]
pub type ISCAPIN_R = crate::FieldReader<u8, u8>;
#[doc = "Field `ISCAPIN` writer - Input Select for CAPIN - ISCAPIN"]
pub type ISCAPIN_W<'a, const O: u8> = crate::FieldWriter<'a, u32, PISEL_SPEC, u8, u8, 2, O>;
impl R {
    #[doc = "Bit 0 - Input Select for T2IN - IST2IN"]
    #[inline(always)]
    pub fn ist2in(&self) -> IST2IN_R {
        IST2IN_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - Input Select for T2EUD - IST2EUD"]
    #[inline(always)]
    pub fn ist2eud(&self) -> IST2EUD_R {
        IST2EUD_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bits 2:3 - Input Select for T3IN - IST3IN"]
    #[inline(always)]
    pub fn ist3in(&self) -> IST3IN_R {
        IST3IN_R::new(((self.bits >> 2) & 3) as u8)
    }
    #[doc = "Bits 4:5 - Input Select for T3EUD - IST3EUD"]
    #[inline(always)]
    pub fn ist3eud(&self) -> IST3EUD_R {
        IST3EUD_R::new(((self.bits >> 4) & 3) as u8)
    }
    #[doc = "Bits 6:7 - Input Select for T4IN - IST4IN"]
    #[inline(always)]
    pub fn ist4in(&self) -> IST4IN_R {
        IST4IN_R::new(((self.bits >> 6) & 3) as u8)
    }
    #[doc = "Bits 8:9 - Input Select for T4EUD - IST4EUD"]
    #[inline(always)]
    pub fn ist4eud(&self) -> IST4EUD_R {
        IST4EUD_R::new(((self.bits >> 8) & 3) as u8)
    }
    #[doc = "Bit 10 - Input Select for T5IN - IST5IN"]
    #[inline(always)]
    pub fn ist5in(&self) -> IST5IN_R {
        IST5IN_R::new(((self.bits >> 10) & 1) != 0)
    }
    #[doc = "Bit 11 - Input Select for T5EUD - IST5EUD"]
    #[inline(always)]
    pub fn ist5eud(&self) -> IST5EUD_R {
        IST5EUD_R::new(((self.bits >> 11) & 1) != 0)
    }
    #[doc = "Bit 12 - Input Select for T6IN - IST6IN"]
    #[inline(always)]
    pub fn ist6in(&self) -> IST6IN_R {
        IST6IN_R::new(((self.bits >> 12) & 1) != 0)
    }
    #[doc = "Bit 13 - Input Select for T6EUD - IST6EUD"]
    #[inline(always)]
    pub fn ist6eud(&self) -> IST6EUD_R {
        IST6EUD_R::new(((self.bits >> 13) & 1) != 0)
    }
    #[doc = "Bits 14:15 - Input Select for CAPIN - ISCAPIN"]
    #[inline(always)]
    pub fn iscapin(&self) -> ISCAPIN_R {
        ISCAPIN_R::new(((self.bits >> 14) & 3) as u8)
    }
}
impl W {
    #[doc = "Bit 0 - Input Select for T2IN - IST2IN"]
    #[inline(always)]
    #[must_use]
    pub fn ist2in(&mut self) -> IST2IN_W<0> {
        IST2IN_W::new(self)
    }
    #[doc = "Bit 1 - Input Select for T2EUD - IST2EUD"]
    #[inline(always)]
    #[must_use]
    pub fn ist2eud(&mut self) -> IST2EUD_W<1> {
        IST2EUD_W::new(self)
    }
    #[doc = "Bits 2:3 - Input Select for T3IN - IST3IN"]
    #[inline(always)]
    #[must_use]
    pub fn ist3in(&mut self) -> IST3IN_W<2> {
        IST3IN_W::new(self)
    }
    #[doc = "Bits 4:5 - Input Select for T3EUD - IST3EUD"]
    #[inline(always)]
    #[must_use]
    pub fn ist3eud(&mut self) -> IST3EUD_W<4> {
        IST3EUD_W::new(self)
    }
    #[doc = "Bits 6:7 - Input Select for T4IN - IST4IN"]
    #[inline(always)]
    #[must_use]
    pub fn ist4in(&mut self) -> IST4IN_W<6> {
        IST4IN_W::new(self)
    }
    #[doc = "Bits 8:9 - Input Select for T4EUD - IST4EUD"]
    #[inline(always)]
    #[must_use]
    pub fn ist4eud(&mut self) -> IST4EUD_W<8> {
        IST4EUD_W::new(self)
    }
    #[doc = "Bit 10 - Input Select for T5IN - IST5IN"]
    #[inline(always)]
    #[must_use]
    pub fn ist5in(&mut self) -> IST5IN_W<10> {
        IST5IN_W::new(self)
    }
    #[doc = "Bit 11 - Input Select for T5EUD - IST5EUD"]
    #[inline(always)]
    #[must_use]
    pub fn ist5eud(&mut self) -> IST5EUD_W<11> {
        IST5EUD_W::new(self)
    }
    #[doc = "Bit 12 - Input Select for T6IN - IST6IN"]
    #[inline(always)]
    #[must_use]
    pub fn ist6in(&mut self) -> IST6IN_W<12> {
        IST6IN_W::new(self)
    }
    #[doc = "Bit 13 - Input Select for T6EUD - IST6EUD"]
    #[inline(always)]
    #[must_use]
    pub fn ist6eud(&mut self) -> IST6EUD_W<13> {
        IST6EUD_W::new(self)
    }
    #[doc = "Bits 14:15 - Input Select for CAPIN - ISCAPIN"]
    #[inline(always)]
    #[must_use]
    pub fn iscapin(&mut self) -> ISCAPIN_W<14> {
        ISCAPIN_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Port Input Select Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [pisel](index.html) module"]
pub struct PISEL_SPEC;
impl crate::RegisterSpec for PISEL_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [pisel::R](R) reader structure"]
impl crate::Readable for PISEL_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [pisel::W](W) writer structure"]
impl crate::Writable for PISEL_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets PISEL to value 0"]
impl crate::Resettable for PISEL_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
