// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `ME1CHSR` reader"]
pub struct R(crate::R<ME1CHSR_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<ME1CHSR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<ME1CHSR_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<ME1CHSR_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `TCOUNT` reader - Transfer Count Status - TCOUNT"]
pub type TCOUNT_R = crate::FieldReader<u16, u16>;
#[doc = "Field `LXO` reader - Old Value of Pattern Detection - LXO"]
pub type LXO_R = crate::BitReader<bool>;
#[doc = "Field `WRPS` reader - Wrap Source Buffer - WRPS"]
pub type WRPS_R = crate::BitReader<bool>;
#[doc = "Field `WRPD` reader - Wrap Destination Buffer - WRPD"]
pub type WRPD_R = crate::BitReader<bool>;
#[doc = "Field `ICH` reader - Interrupt from Channel - ICH"]
pub type ICH_R = crate::BitReader<bool>;
#[doc = "Field `IPM` reader - Pattern Detection from Channel - IPM"]
pub type IPM_R = crate::BitReader<bool>;
#[doc = "Field `BUFFER` reader - DMA Double Buffering Active Buffer - BUFFER"]
pub type BUFFER_R = crate::BitReader<bool>;
#[doc = "Field `FROZEN` reader - DMA Double Buffering Frozen Buffer - FROZEN"]
pub type FROZEN_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bits 0:13 - Transfer Count Status - TCOUNT"]
    #[inline(always)]
    pub fn tcount(&self) -> TCOUNT_R {
        TCOUNT_R::new((self.bits & 0x3fff) as u16)
    }
    #[doc = "Bit 15 - Old Value of Pattern Detection - LXO"]
    #[inline(always)]
    pub fn lxo(&self) -> LXO_R {
        LXO_R::new(((self.bits >> 15) & 1) != 0)
    }
    #[doc = "Bit 16 - Wrap Source Buffer - WRPS"]
    #[inline(always)]
    pub fn wrps(&self) -> WRPS_R {
        WRPS_R::new(((self.bits >> 16) & 1) != 0)
    }
    #[doc = "Bit 17 - Wrap Destination Buffer - WRPD"]
    #[inline(always)]
    pub fn wrpd(&self) -> WRPD_R {
        WRPD_R::new(((self.bits >> 17) & 1) != 0)
    }
    #[doc = "Bit 18 - Interrupt from Channel - ICH"]
    #[inline(always)]
    pub fn ich(&self) -> ICH_R {
        ICH_R::new(((self.bits >> 18) & 1) != 0)
    }
    #[doc = "Bit 19 - Pattern Detection from Channel - IPM"]
    #[inline(always)]
    pub fn ipm(&self) -> IPM_R {
        IPM_R::new(((self.bits >> 19) & 1) != 0)
    }
    #[doc = "Bit 22 - DMA Double Buffering Active Buffer - BUFFER"]
    #[inline(always)]
    pub fn buffer(&self) -> BUFFER_R {
        BUFFER_R::new(((self.bits >> 22) & 1) != 0)
    }
    #[doc = "Bit 23 - DMA Double Buffering Frozen Buffer - FROZEN"]
    #[inline(always)]
    pub fn frozen(&self) -> FROZEN_R {
        FROZEN_R::new(((self.bits >> 23) & 1) != 0)
    }
}
#[doc = "ME 1 Channel Status Register\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [me1chsr](index.html) module"]
pub struct ME1CHSR_SPEC;
impl crate::RegisterSpec for ME1CHSR_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [me1chsr::R](R) reader structure"]
impl crate::Readable for ME1CHSR_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets ME1CHSR to value 0"]
impl crate::Resettable for ME1CHSR_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
