// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `TSR058` reader"]
pub struct R(crate::R<TSR058_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<TSR058_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<TSR058_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<TSR058_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `TSR058` writer"]
pub struct W(crate::W<TSR058_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<TSR058_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<TSR058_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<TSR058_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `RST` reader - DMA Channel Reset - RST"]
pub type RST_R = crate::BitReader<bool>;
#[doc = "Field `RST` writer - DMA Channel Reset - RST"]
pub type RST_W<'a, const O: u8> = crate::BitWriter<'a, u32, TSR058_SPEC, bool, O>;
#[doc = "Field `HTRE` reader - DMA Channel Hardware Request Enable - HTRE"]
pub type HTRE_R = crate::BitReader<bool>;
#[doc = "Field `TRL` reader - DMA Channel Transaction/Transfer Request Lost - TRL"]
pub type TRL_R = crate::BitReader<bool>;
#[doc = "Field `CH` reader - DMA Channel Transaction Request State - CH"]
pub type CH_R = crate::BitReader<bool>;
#[doc = "Field `ETRL` reader - Enable DMA Channel Transaction/Transfer Request Lost Interrupt - ETRL"]
pub type ETRL_R = crate::BitReader<bool>;
#[doc = "Field `ETRL` writer - Enable DMA Channel Transaction/Transfer Request Lost Interrupt - ETRL"]
pub type ETRL_W<'a, const O: u8> = crate::BitWriter<'a, u32, TSR058_SPEC, bool, O>;
#[doc = "Field `HLTREQ` reader - DMA Channel Halt Request - HLTREQ"]
pub type HLTREQ_R = crate::BitReader<bool>;
#[doc = "Field `HLTREQ` writer - DMA Channel Halt Request - HLTREQ"]
pub type HLTREQ_W<'a, const O: u8> = crate::BitWriter<'a, u32, TSR058_SPEC, bool, O>;
#[doc = "Field `HLTACK` reader - DMA Channel Halt Acknowledge - HLTACK"]
pub type HLTACK_R = crate::BitReader<bool>;
#[doc = "Field `ECH` writer - Enable DMA Channel Hardware Transaction Request - ECH"]
pub type ECH_W<'a, const O: u8> = crate::BitWriter<'a, u32, TSR058_SPEC, bool, O>;
#[doc = "Field `DCH` writer - Disable DMA Channel Hardware Transaction Request - DCH"]
pub type DCH_W<'a, const O: u8> = crate::BitWriter<'a, u32, TSR058_SPEC, bool, O>;
#[doc = "Field `CTL` writer - Clear DMA Channel Transaction/Transfer Request Lost - CTL"]
pub type CTL_W<'a, const O: u8> = crate::BitWriter<'a, u32, TSR058_SPEC, bool, O>;
#[doc = "Field `HLTCLR` writer - Clear DMA Channel Halt Request and Acknowledge - HLTCLR"]
pub type HLTCLR_W<'a, const O: u8> = crate::BitWriter<'a, u32, TSR058_SPEC, bool, O>;
impl R {
    #[doc = "Bit 0 - DMA Channel Reset - RST"]
    #[inline(always)]
    pub fn rst(&self) -> RST_R {
        RST_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - DMA Channel Hardware Request Enable - HTRE"]
    #[inline(always)]
    pub fn htre(&self) -> HTRE_R {
        HTRE_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - DMA Channel Transaction/Transfer Request Lost - TRL"]
    #[inline(always)]
    pub fn trl(&self) -> TRL_R {
        TRL_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - DMA Channel Transaction Request State - CH"]
    #[inline(always)]
    pub fn ch(&self) -> CH_R {
        CH_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 4 - Enable DMA Channel Transaction/Transfer Request Lost Interrupt - ETRL"]
    #[inline(always)]
    pub fn etrl(&self) -> ETRL_R {
        ETRL_R::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 8 - DMA Channel Halt Request - HLTREQ"]
    #[inline(always)]
    pub fn hltreq(&self) -> HLTREQ_R {
        HLTREQ_R::new(((self.bits >> 8) & 1) != 0)
    }
    #[doc = "Bit 9 - DMA Channel Halt Acknowledge - HLTACK"]
    #[inline(always)]
    pub fn hltack(&self) -> HLTACK_R {
        HLTACK_R::new(((self.bits >> 9) & 1) != 0)
    }
}
impl W {
    #[doc = "Bit 0 - DMA Channel Reset - RST"]
    #[inline(always)]
    #[must_use]
    pub fn rst(&mut self) -> RST_W<0> {
        RST_W::new(self)
    }
    #[doc = "Bit 4 - Enable DMA Channel Transaction/Transfer Request Lost Interrupt - ETRL"]
    #[inline(always)]
    #[must_use]
    pub fn etrl(&mut self) -> ETRL_W<4> {
        ETRL_W::new(self)
    }
    #[doc = "Bit 8 - DMA Channel Halt Request - HLTREQ"]
    #[inline(always)]
    #[must_use]
    pub fn hltreq(&mut self) -> HLTREQ_W<8> {
        HLTREQ_W::new(self)
    }
    #[doc = "Bit 16 - Enable DMA Channel Hardware Transaction Request - ECH"]
    #[inline(always)]
    #[must_use]
    pub fn ech(&mut self) -> ECH_W<16> {
        ECH_W::new(self)
    }
    #[doc = "Bit 17 - Disable DMA Channel Hardware Transaction Request - DCH"]
    #[inline(always)]
    #[must_use]
    pub fn dch(&mut self) -> DCH_W<17> {
        DCH_W::new(self)
    }
    #[doc = "Bit 18 - Clear DMA Channel Transaction/Transfer Request Lost - CTL"]
    #[inline(always)]
    #[must_use]
    pub fn ctl(&mut self) -> CTL_W<18> {
        CTL_W::new(self)
    }
    #[doc = "Bit 24 - Clear DMA Channel Halt Request and Acknowledge - HLTCLR"]
    #[inline(always)]
    #[must_use]
    pub fn hltclr(&mut self) -> HLTCLR_W<24> {
        HLTCLR_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "DMA Channel 058 Transaction State Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [tsr058](index.html) module"]
pub struct TSR058_SPEC;
impl crate::RegisterSpec for TSR058_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [tsr058::R](R) reader structure"]
impl crate::Readable for TSR058_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [tsr058::W](W) writer structure"]
impl crate::Writable for TSR058_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets TSR058 to value 0"]
impl crate::Resettable for TSR058_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
