// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `MC46_ALMSRCS` reader"]
pub struct R(crate::R<MC46_ALMSRCS_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<MC46_ALMSRCS_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<MC46_ALMSRCS_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<MC46_ALMSRCS_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `MC46_ALMSRCS` writer"]
pub struct W(crate::W<MC46_ALMSRCS_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<MC46_ALMSRCS_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<MC46_ALMSRCS_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<MC46_ALMSRCS_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `SBE` reader - Single Bit Error Notification & Tracking Enable - SBE"]
pub type SBE_R = crate::BitReader<bool>;
#[doc = "Field `SBE` writer - Single Bit Error Notification & Tracking Enable - SBE"]
pub type SBE_W<'a, const O: u8> = crate::BitWriter<'a, u16, MC46_ALMSRCS_SPEC, bool, O>;
#[doc = "Field `DBE` reader - Double Bit Error Notification and Tracking Enable - DBE"]
pub type DBE_R = crate::BitReader<bool>;
#[doc = "Field `DBE` writer - Double Bit Error Notification and Tracking Enable - DBE"]
pub type DBE_W<'a, const O: u8> = crate::BitWriter<'a, u16, MC46_ALMSRCS_SPEC, bool, O>;
#[doc = "Field `ADDRE` reader - Address Error Notification Enable - ADDRE"]
pub type ADDRE_R = crate::BitReader<bool>;
#[doc = "Field `ADDRE` writer - Address Error Notification Enable - ADDRE"]
pub type ADDRE_W<'a, const O: u8> = crate::BitWriter<'a, u16, MC46_ALMSRCS_SPEC, bool, O>;
#[doc = "Field `OVFE` reader - ETRR Overflow notification enable- OVFE"]
pub type OVFE_R = crate::BitReader<bool>;
#[doc = "Field `OVFE` writer - ETRR Overflow notification enable- OVFE"]
pub type OVFE_W<'a, const O: u8> = crate::BitWriter<'a, u16, MC46_ALMSRCS_SPEC, bool, O>;
#[doc = "Field `OPENE` reader - SSH Operational Error Notification Enable - OPENE"]
pub type OPENE_R = crate::BitReader<bool>;
#[doc = "Field `OPENE` writer - SSH Operational Error Notification Enable - OPENE"]
pub type OPENE_W<'a, const O: u8> = crate::BitWriter<'a, u16, MC46_ALMSRCS_SPEC, bool, O>;
#[doc = "Field `MISCE` reader - SSH Misc. Errors Notification Enable - MISCE"]
pub type MISCE_R = crate::BitReader<bool>;
#[doc = "Field `MISCE` writer - SSH Misc. Errors Notification Enable - MISCE"]
pub type MISCE_W<'a, const O: u8> = crate::BitWriter<'a, u16, MC46_ALMSRCS_SPEC, bool, O>;
impl R {
    #[doc = "Bit 0 - Single Bit Error Notification & Tracking Enable - SBE"]
    #[inline(always)]
    pub fn sbe(&self) -> SBE_R {
        SBE_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - Double Bit Error Notification and Tracking Enable - DBE"]
    #[inline(always)]
    pub fn dbe(&self) -> DBE_R {
        DBE_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - Address Error Notification Enable - ADDRE"]
    #[inline(always)]
    pub fn addre(&self) -> ADDRE_R {
        ADDRE_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - ETRR Overflow notification enable- OVFE"]
    #[inline(always)]
    pub fn ovfe(&self) -> OVFE_R {
        OVFE_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 4 - SSH Operational Error Notification Enable - OPENE"]
    #[inline(always)]
    pub fn opene(&self) -> OPENE_R {
        OPENE_R::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 5 - SSH Misc. Errors Notification Enable - MISCE"]
    #[inline(always)]
    pub fn misce(&self) -> MISCE_R {
        MISCE_R::new(((self.bits >> 5) & 1) != 0)
    }
}
impl W {
    #[doc = "Bit 0 - Single Bit Error Notification & Tracking Enable - SBE"]
    #[inline(always)]
    #[must_use]
    pub fn sbe(&mut self) -> SBE_W<0> {
        SBE_W::new(self)
    }
    #[doc = "Bit 1 - Double Bit Error Notification and Tracking Enable - DBE"]
    #[inline(always)]
    #[must_use]
    pub fn dbe(&mut self) -> DBE_W<1> {
        DBE_W::new(self)
    }
    #[doc = "Bit 2 - Address Error Notification Enable - ADDRE"]
    #[inline(always)]
    #[must_use]
    pub fn addre(&mut self) -> ADDRE_W<2> {
        ADDRE_W::new(self)
    }
    #[doc = "Bit 3 - ETRR Overflow notification enable- OVFE"]
    #[inline(always)]
    #[must_use]
    pub fn ovfe(&mut self) -> OVFE_W<3> {
        OVFE_W::new(self)
    }
    #[doc = "Bit 4 - SSH Operational Error Notification Enable - OPENE"]
    #[inline(always)]
    #[must_use]
    pub fn opene(&mut self) -> OPENE_W<4> {
        OPENE_W::new(self)
    }
    #[doc = "Bit 5 - SSH Misc. Errors Notification Enable - MISCE"]
    #[inline(always)]
    #[must_use]
    pub fn misce(&mut self) -> MISCE_W<5> {
        MISCE_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u16) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Alarm Sources Configuration Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [mc46_almsrcs](index.html) module"]
pub struct MC46_ALMSRCS_SPEC;
impl crate::RegisterSpec for MC46_ALMSRCS_SPEC {
    type Ux = u16;
}
#[doc = "`read()` method returns [mc46_almsrcs::R](R) reader structure"]
impl crate::Readable for MC46_ALMSRCS_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [mc46_almsrcs::W](W) writer structure"]
impl crate::Writable for MC46_ALMSRCS_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets MC46_ALMSRCS to value 0x3f"]
impl crate::Resettable for MC46_ALMSRCS_SPEC {
    const RESET_VALUE: Self::Ux = 0x3f;
}
