// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `MEMDONE0` reader"]
pub struct R(crate::R<MEMDONE0_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<MEMDONE0_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<MEMDONE0_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<MEMDONE0_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `CPU0_DMEM_DONE` reader - CPU0 DMEM Test Done Status - CPU0_DMEM_DONE"]
pub type CPU0_DMEM_DONE_R = crate::BitReader<bool>;
#[doc = "Field `CPU0_DTAG_DONE` reader - CPU0 DTAG Test Done Status - CPU0_DTAG_DONE"]
pub type CPU0_DTAG_DONE_R = crate::BitReader<bool>;
#[doc = "Field `CPU0_PMEM_DONE` reader - CPU0 PMEM Test Done Status - CPU0_PMEM_DONE"]
pub type CPU0_PMEM_DONE_R = crate::BitReader<bool>;
#[doc = "Field `CPU0_PTAG_DONE` reader - CPU0 PTAG Test Done Status - CPU0_PTAG_DONE"]
pub type CPU0_PTAG_DONE_R = crate::BitReader<bool>;
#[doc = "Field `CPU0_DLMU_STBY_DONE` reader - CPU0 STANDBY DLMU Test Done Status - CPU0_DLMU_STBY_DONE"]
pub type CPU0_DLMU_STBY_DONE_R = crate::BitReader<bool>;
#[doc = "Field `CPU1_DMEM_DONE` reader - CPU1 DMEM Test Done Status - CPU1_DMEM_DONE"]
pub type CPU1_DMEM_DONE_R = crate::BitReader<bool>;
#[doc = "Field `CPU1_DTAG_DONE` reader - CPU1 DTAG Test Done Status - CPU1_DTAG_DONE"]
pub type CPU1_DTAG_DONE_R = crate::BitReader<bool>;
#[doc = "Field `CPU1_PMEM_DONE` reader - CPU1 PMEM Test Done Status - CPU1_PMEM_DONE"]
pub type CPU1_PMEM_DONE_R = crate::BitReader<bool>;
#[doc = "Field `CPU1_PTAG_DONE` reader - CPU1 PTAG Test Done Status - CPU1_PTAG_DONE"]
pub type CPU1_PTAG_DONE_R = crate::BitReader<bool>;
#[doc = "Field `CPU1_DLMU_STBY_DONE` reader - CPU1 STANDBY DLMU Test Done Status - CPU1_DLMU_STBY_DONE"]
pub type CPU1_DLMU_STBY_DONE_R = crate::BitReader<bool>;
#[doc = "Field `CPU2_DMEM_DONE` reader - CPU2 DMEM Test Done Status - CPU2_DMEM_DONE"]
pub type CPU2_DMEM_DONE_R = crate::BitReader<bool>;
#[doc = "Field `CPU2_DTAG_DONE` reader - CPU2 DTAG Test Done Status - CPU2_DTAG_DONE"]
pub type CPU2_DTAG_DONE_R = crate::BitReader<bool>;
#[doc = "Field `CPU2_PMEM_DONE` reader - CPU2 PMEM Test Done Status - CPU2_PMEM_DONE"]
pub type CPU2_PMEM_DONE_R = crate::BitReader<bool>;
#[doc = "Field `CPU2_PTAG_DONE` reader - CPU2 PTAG Test Done Status - CPU2_PTAG_DONE"]
pub type CPU2_PTAG_DONE_R = crate::BitReader<bool>;
#[doc = "Field `CPU2_DLMU_DONE` reader - CPU2 DLMU memory Test Done Status - CPU2_DLMU_DONE"]
pub type CPU2_DLMU_DONE_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bit 0 - CPU0 DMEM Test Done Status - CPU0_DMEM_DONE"]
    #[inline(always)]
    pub fn cpu0_dmem_done(&self) -> CPU0_DMEM_DONE_R {
        CPU0_DMEM_DONE_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - CPU0 DTAG Test Done Status - CPU0_DTAG_DONE"]
    #[inline(always)]
    pub fn cpu0_dtag_done(&self) -> CPU0_DTAG_DONE_R {
        CPU0_DTAG_DONE_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - CPU0 PMEM Test Done Status - CPU0_PMEM_DONE"]
    #[inline(always)]
    pub fn cpu0_pmem_done(&self) -> CPU0_PMEM_DONE_R {
        CPU0_PMEM_DONE_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - CPU0 PTAG Test Done Status - CPU0_PTAG_DONE"]
    #[inline(always)]
    pub fn cpu0_ptag_done(&self) -> CPU0_PTAG_DONE_R {
        CPU0_PTAG_DONE_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 4 - CPU0 STANDBY DLMU Test Done Status - CPU0_DLMU_STBY_DONE"]
    #[inline(always)]
    pub fn cpu0_dlmu_stby_done(&self) -> CPU0_DLMU_STBY_DONE_R {
        CPU0_DLMU_STBY_DONE_R::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 5 - CPU1 DMEM Test Done Status - CPU1_DMEM_DONE"]
    #[inline(always)]
    pub fn cpu1_dmem_done(&self) -> CPU1_DMEM_DONE_R {
        CPU1_DMEM_DONE_R::new(((self.bits >> 5) & 1) != 0)
    }
    #[doc = "Bit 6 - CPU1 DTAG Test Done Status - CPU1_DTAG_DONE"]
    #[inline(always)]
    pub fn cpu1_dtag_done(&self) -> CPU1_DTAG_DONE_R {
        CPU1_DTAG_DONE_R::new(((self.bits >> 6) & 1) != 0)
    }
    #[doc = "Bit 7 - CPU1 PMEM Test Done Status - CPU1_PMEM_DONE"]
    #[inline(always)]
    pub fn cpu1_pmem_done(&self) -> CPU1_PMEM_DONE_R {
        CPU1_PMEM_DONE_R::new(((self.bits >> 7) & 1) != 0)
    }
    #[doc = "Bit 8 - CPU1 PTAG Test Done Status - CPU1_PTAG_DONE"]
    #[inline(always)]
    pub fn cpu1_ptag_done(&self) -> CPU1_PTAG_DONE_R {
        CPU1_PTAG_DONE_R::new(((self.bits >> 8) & 1) != 0)
    }
    #[doc = "Bit 9 - CPU1 STANDBY DLMU Test Done Status - CPU1_DLMU_STBY_DONE"]
    #[inline(always)]
    pub fn cpu1_dlmu_stby_done(&self) -> CPU1_DLMU_STBY_DONE_R {
        CPU1_DLMU_STBY_DONE_R::new(((self.bits >> 9) & 1) != 0)
    }
    #[doc = "Bit 10 - CPU2 DMEM Test Done Status - CPU2_DMEM_DONE"]
    #[inline(always)]
    pub fn cpu2_dmem_done(&self) -> CPU2_DMEM_DONE_R {
        CPU2_DMEM_DONE_R::new(((self.bits >> 10) & 1) != 0)
    }
    #[doc = "Bit 11 - CPU2 DTAG Test Done Status - CPU2_DTAG_DONE"]
    #[inline(always)]
    pub fn cpu2_dtag_done(&self) -> CPU2_DTAG_DONE_R {
        CPU2_DTAG_DONE_R::new(((self.bits >> 11) & 1) != 0)
    }
    #[doc = "Bit 12 - CPU2 PMEM Test Done Status - CPU2_PMEM_DONE"]
    #[inline(always)]
    pub fn cpu2_pmem_done(&self) -> CPU2_PMEM_DONE_R {
        CPU2_PMEM_DONE_R::new(((self.bits >> 12) & 1) != 0)
    }
    #[doc = "Bit 13 - CPU2 PTAG Test Done Status - CPU2_PTAG_DONE"]
    #[inline(always)]
    pub fn cpu2_ptag_done(&self) -> CPU2_PTAG_DONE_R {
        CPU2_PTAG_DONE_R::new(((self.bits >> 13) & 1) != 0)
    }
    #[doc = "Bit 14 - CPU2 DLMU memory Test Done Status - CPU2_DLMU_DONE"]
    #[inline(always)]
    pub fn cpu2_dlmu_done(&self) -> CPU2_DLMU_DONE_R {
        CPU2_DLMU_DONE_R::new(((self.bits >> 14) & 1) != 0)
    }
}
#[doc = "Memory Test Done Status Register 0\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [memdone0](index.html) module"]
pub struct MEMDONE0_SPEC;
impl crate::RegisterSpec for MEMDONE0_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [memdone0::R](R) reader structure"]
impl crate::Readable for MEMDONE0_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets MEMDONE0 to value 0xffff_ffff"]
impl crate::Resettable for MEMDONE0_SPEC {
    const RESET_VALUE: Self::Ux = 0xffff_ffff;
}
