// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `MEMFDA1` reader"]
pub struct R(crate::R<MEMFDA1_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<MEMFDA1_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<MEMFDA1_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<MEMFDA1_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `CPU0_DMEM1_FDA` reader - CPU0 DMEM1 Test FDA Status - CPU0_DMEM1_FDA"]
pub type CPU0_DMEM1_FDA_R = crate::BitReader<bool>;
#[doc = "Field `CPU1_DMEM1_FDA` reader - CPU1 DMEM1 Test FDA Status - CPU1_DMEM1_FDA"]
pub type CPU1_DMEM1_FDA_R = crate::BitReader<bool>;
#[doc = "Field `DAM0_FDA` reader - DAM0 Test FDA Status - DAM0_FDA"]
pub type DAM0_FDA_R = crate::BitReader<bool>;
#[doc = "Field `SADMA_FDA` reader - Safety DMA Test FDA Status - SADMA_FDA"]
pub type SADMA_FDA_R = crate::BitReader<bool>;
#[doc = "Field `MINI_MCDS_FDA` reader - MINI MCDS memory Test FDA Status - MINI_MCDS_FDA"]
pub type MINI_MCDS_FDA_R = crate::BitReader<bool>;
#[doc = "Field `GTM_FIFO_FDA` reader - GTM FIFO memory Test FDA Status - GTM_FIFO_FDA"]
pub type GTM_FIFO_FDA_R = crate::BitReader<bool>;
#[doc = "Field `GTM_MCS0FAST_FDA` reader - GTM MCS0 FAST memory Test FDA Status - GTM_MCS0FAST_FDA"]
pub type GTM_MCS0FAST_FDA_R = crate::BitReader<bool>;
#[doc = "Field `GTM_MCS1FAST_FDA` reader - GTM MCS1 FAST memory Test FDA Status - GTM_MCS1FAST_FDA"]
pub type GTM_MCS1FAST_FDA_R = crate::BitReader<bool>;
#[doc = "Field `GTM_DPLL1A_FDA` reader - GTM DPLL1A memory Test FDA Status - GTM_DPLL1A_FDA"]
pub type GTM_DPLL1A_FDA_R = crate::BitReader<bool>;
#[doc = "Field `GTM_DPLL1BC_FDA` reader - GTM DPLL1BC memory Test FDA Status - GTM_DPLL1BC_FDA"]
pub type GTM_DPLL1BC_FDA_R = crate::BitReader<bool>;
#[doc = "Field `GTM_DPLL2_FDA` reader - GTM DPLL2 memory Test FDA Status - GTM_DPLL2_FDA"]
pub type GTM_DPLL2_FDA_R = crate::BitReader<bool>;
#[doc = "Field `MCAN10_FDA` reader - MCAN10 memory Test FDA Status - MCAN10_FDA"]
pub type MCAN10_FDA_R = crate::BitReader<bool>;
#[doc = "Field `MCAN20_FDA` reader - MCAN20 memory Test FDA Status - MCAN20_FDA"]
pub type MCAN20_FDA_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bit 2 - CPU0 DMEM1 Test FDA Status - CPU0_DMEM1_FDA"]
    #[inline(always)]
    pub fn cpu0_dmem1_fda(&self) -> CPU0_DMEM1_FDA_R {
        CPU0_DMEM1_FDA_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - CPU1 DMEM1 Test FDA Status - CPU1_DMEM1_FDA"]
    #[inline(always)]
    pub fn cpu1_dmem1_fda(&self) -> CPU1_DMEM1_FDA_R {
        CPU1_DMEM1_FDA_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 6 - DAM0 Test FDA Status - DAM0_FDA"]
    #[inline(always)]
    pub fn dam0_fda(&self) -> DAM0_FDA_R {
        DAM0_FDA_R::new(((self.bits >> 6) & 1) != 0)
    }
    #[doc = "Bit 9 - Safety DMA Test FDA Status - SADMA_FDA"]
    #[inline(always)]
    pub fn sadma_fda(&self) -> SADMA_FDA_R {
        SADMA_FDA_R::new(((self.bits >> 9) & 1) != 0)
    }
    #[doc = "Bit 10 - MINI MCDS memory Test FDA Status - MINI_MCDS_FDA"]
    #[inline(always)]
    pub fn mini_mcds_fda(&self) -> MINI_MCDS_FDA_R {
        MINI_MCDS_FDA_R::new(((self.bits >> 10) & 1) != 0)
    }
    #[doc = "Bit 21 - GTM FIFO memory Test FDA Status - GTM_FIFO_FDA"]
    #[inline(always)]
    pub fn gtm_fifo_fda(&self) -> GTM_FIFO_FDA_R {
        GTM_FIFO_FDA_R::new(((self.bits >> 21) & 1) != 0)
    }
    #[doc = "Bit 23 - GTM MCS0 FAST memory Test FDA Status - GTM_MCS0FAST_FDA"]
    #[inline(always)]
    pub fn gtm_mcs0fast_fda(&self) -> GTM_MCS0FAST_FDA_R {
        GTM_MCS0FAST_FDA_R::new(((self.bits >> 23) & 1) != 0)
    }
    #[doc = "Bit 25 - GTM MCS1 FAST memory Test FDA Status - GTM_MCS1FAST_FDA"]
    #[inline(always)]
    pub fn gtm_mcs1fast_fda(&self) -> GTM_MCS1FAST_FDA_R {
        GTM_MCS1FAST_FDA_R::new(((self.bits >> 25) & 1) != 0)
    }
    #[doc = "Bit 26 - GTM DPLL1A memory Test FDA Status - GTM_DPLL1A_FDA"]
    #[inline(always)]
    pub fn gtm_dpll1a_fda(&self) -> GTM_DPLL1A_FDA_R {
        GTM_DPLL1A_FDA_R::new(((self.bits >> 26) & 1) != 0)
    }
    #[doc = "Bit 27 - GTM DPLL1BC memory Test FDA Status - GTM_DPLL1BC_FDA"]
    #[inline(always)]
    pub fn gtm_dpll1bc_fda(&self) -> GTM_DPLL1BC_FDA_R {
        GTM_DPLL1BC_FDA_R::new(((self.bits >> 27) & 1) != 0)
    }
    #[doc = "Bit 28 - GTM DPLL2 memory Test FDA Status - GTM_DPLL2_FDA"]
    #[inline(always)]
    pub fn gtm_dpll2_fda(&self) -> GTM_DPLL2_FDA_R {
        GTM_DPLL2_FDA_R::new(((self.bits >> 28) & 1) != 0)
    }
    #[doc = "Bit 30 - MCAN10 memory Test FDA Status - MCAN10_FDA"]
    #[inline(always)]
    pub fn mcan10_fda(&self) -> MCAN10_FDA_R {
        MCAN10_FDA_R::new(((self.bits >> 30) & 1) != 0)
    }
    #[doc = "Bit 31 - MCAN20 memory Test FDA Status - MCAN20_FDA"]
    #[inline(always)]
    pub fn mcan20_fda(&self) -> MCAN20_FDA_R {
        MCAN20_FDA_R::new(((self.bits >> 31) & 1) != 0)
    }
}
#[doc = "Memory Test FDA Status Register 1\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [memfda1](index.html) module"]
pub struct MEMFDA1_SPEC;
impl crate::RegisterSpec for MEMFDA1_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [memfda1::R](R) reader structure"]
impl crate::Readable for MEMFDA1_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets MEMFDA1 to value 0"]
impl crate::Resettable for MEMFDA1_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
