// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `RXFIFOCON` reader"]
pub struct R(crate::R<RXFIFOCON_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<RXFIFOCON_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<RXFIFOCON_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<RXFIFOCON_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `RXFIFOCON` writer"]
pub struct W(crate::W<RXFIFOCON_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<RXFIFOCON_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<RXFIFOCON_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<RXFIFOCON_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `FLUSH` writer - Flush the receive FIFO - FLUSH"]
pub type FLUSH_W<'a, const O: u8> = crate::BitWriter<'a, u32, RXFIFOCON_SPEC, bool, O>;
#[doc = "Field `ENI` reader - Receive FIFO Inlet Enable - ENI"]
pub type ENI_R = crate::BitReader<bool>;
#[doc = "Field `ENI` writer - Receive FIFO Inlet Enable - ENI"]
pub type ENI_W<'a, const O: u8> = crate::BitWriter<'a, u32, RXFIFOCON_SPEC, bool, O>;
#[doc = "Field `FM` reader - RXFIFO Mode - FM"]
pub type FM_R = crate::FieldReader<u8, u8>;
#[doc = "Field `FM` writer - RXFIFO Mode - FM"]
pub type FM_W<'a, const O: u8> = crate::FieldWriter<'a, u32, RXFIFOCON_SPEC, u8, u8, 2, O>;
#[doc = "Field `OUTW` reader - Receive FIFO Outlet Width - OUTW"]
pub type OUTW_R = crate::FieldReader<u8, u8>;
#[doc = "Field `OUTW` writer - Receive FIFO Outlet Width - OUTW"]
pub type OUTW_W<'a, const O: u8> = crate::FieldWriter<'a, u32, RXFIFOCON_SPEC, u8, u8, 2, O>;
#[doc = "Field `INTLEVEL` reader - FIFO Interrupt Level - INTLEVEL"]
pub type INTLEVEL_R = crate::FieldReader<u8, u8>;
#[doc = "Field `INTLEVEL` writer - FIFO Interrupt Level - INTLEVEL"]
pub type INTLEVEL_W<'a, const O: u8> = crate::FieldWriter<'a, u32, RXFIFOCON_SPEC, u8, u8, 4, O>;
#[doc = "Field `FILL` reader - FIFO Filling Level - FILL"]
pub type FILL_R = crate::FieldReader<u8, u8>;
#[doc = "Field `BUF` reader - Receive Buffer Mode - BUF"]
pub type BUF_R = crate::BitReader<bool>;
#[doc = "Field `BUF` writer - Receive Buffer Mode - BUF"]
pub type BUF_W<'a, const O: u8> = crate::BitWriter<'a, u32, RXFIFOCON_SPEC, bool, O>;
impl R {
    #[doc = "Bit 1 - Receive FIFO Inlet Enable - ENI"]
    #[inline(always)]
    pub fn eni(&self) -> ENI_R {
        ENI_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bits 4:5 - RXFIFO Mode - FM"]
    #[inline(always)]
    pub fn fm(&self) -> FM_R {
        FM_R::new(((self.bits >> 4) & 3) as u8)
    }
    #[doc = "Bits 6:7 - Receive FIFO Outlet Width - OUTW"]
    #[inline(always)]
    pub fn outw(&self) -> OUTW_R {
        OUTW_R::new(((self.bits >> 6) & 3) as u8)
    }
    #[doc = "Bits 8:11 - FIFO Interrupt Level - INTLEVEL"]
    #[inline(always)]
    pub fn intlevel(&self) -> INTLEVEL_R {
        INTLEVEL_R::new(((self.bits >> 8) & 0x0f) as u8)
    }
    #[doc = "Bits 16:20 - FIFO Filling Level - FILL"]
    #[inline(always)]
    pub fn fill(&self) -> FILL_R {
        FILL_R::new(((self.bits >> 16) & 0x1f) as u8)
    }
    #[doc = "Bit 31 - Receive Buffer Mode - BUF"]
    #[inline(always)]
    pub fn buf(&self) -> BUF_R {
        BUF_R::new(((self.bits >> 31) & 1) != 0)
    }
}
impl W {
    #[doc = "Bit 0 - Flush the receive FIFO - FLUSH"]
    #[inline(always)]
    #[must_use]
    pub fn flush(&mut self) -> FLUSH_W<0> {
        FLUSH_W::new(self)
    }
    #[doc = "Bit 1 - Receive FIFO Inlet Enable - ENI"]
    #[inline(always)]
    #[must_use]
    pub fn eni(&mut self) -> ENI_W<1> {
        ENI_W::new(self)
    }
    #[doc = "Bits 4:5 - RXFIFO Mode - FM"]
    #[inline(always)]
    #[must_use]
    pub fn fm(&mut self) -> FM_W<4> {
        FM_W::new(self)
    }
    #[doc = "Bits 6:7 - Receive FIFO Outlet Width - OUTW"]
    #[inline(always)]
    #[must_use]
    pub fn outw(&mut self) -> OUTW_W<6> {
        OUTW_W::new(self)
    }
    #[doc = "Bits 8:11 - FIFO Interrupt Level - INTLEVEL"]
    #[inline(always)]
    #[must_use]
    pub fn intlevel(&mut self) -> INTLEVEL_W<8> {
        INTLEVEL_W::new(self)
    }
    #[doc = "Bit 31 - Receive Buffer Mode - BUF"]
    #[inline(always)]
    #[must_use]
    pub fn buf(&mut self) -> BUF_W<31> {
        BUF_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "RX FIFO Configuration Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [rxfifocon](index.html) module"]
pub struct RXFIFOCON_SPEC;
impl crate::RegisterSpec for RXFIFOCON_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [rxfifocon::R](R) reader structure"]
impl crate::Readable for RXFIFOCON_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [rxfifocon::W](W) writer structure"]
impl crate::Writable for RXFIFOCON_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets RXFIFOCON to value 0"]
impl crate::Resettable for RXFIFOCON_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
