// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `TXBCF3` reader"]
pub struct R(crate::R<TXBCF3_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<TXBCF3_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<TXBCF3_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<TXBCF3_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `CF0` reader - Cancellation Finished Tx Buffer 0 - CF"]
pub type CF0_R = crate::BitReader<bool>;
#[doc = "Field `CF1` reader - Cancellation Finished Tx Buffer 1 - CF"]
pub type CF1_R = crate::BitReader<bool>;
#[doc = "Field `CF2` reader - Cancellation Finished Tx Buffer 2 - CF"]
pub type CF2_R = crate::BitReader<bool>;
#[doc = "Field `CF3` reader - Cancellation Finished Tx Buffer 3 - CF"]
pub type CF3_R = crate::BitReader<bool>;
#[doc = "Field `CF4` reader - Cancellation Finished Tx Buffer 4 - CF"]
pub type CF4_R = crate::BitReader<bool>;
#[doc = "Field `CF5` reader - Cancellation Finished Tx Buffer 5 - CF"]
pub type CF5_R = crate::BitReader<bool>;
#[doc = "Field `CF6` reader - Cancellation Finished Tx Buffer 6 - CF"]
pub type CF6_R = crate::BitReader<bool>;
#[doc = "Field `CF7` reader - Cancellation Finished Tx Buffer 7 - CF"]
pub type CF7_R = crate::BitReader<bool>;
#[doc = "Field `CF8` reader - Cancellation Finished Tx Buffer 8 - CF"]
pub type CF8_R = crate::BitReader<bool>;
#[doc = "Field `CF9` reader - Cancellation Finished Tx Buffer 9 - CF"]
pub type CF9_R = crate::BitReader<bool>;
#[doc = "Field `CF10` reader - Cancellation Finished Tx Buffer 10 - CF"]
pub type CF10_R = crate::BitReader<bool>;
#[doc = "Field `CF11` reader - Cancellation Finished Tx Buffer 11 - CF"]
pub type CF11_R = crate::BitReader<bool>;
#[doc = "Field `CF12` reader - Cancellation Finished Tx Buffer 12 - CF"]
pub type CF12_R = crate::BitReader<bool>;
#[doc = "Field `CF13` reader - Cancellation Finished Tx Buffer 13 - CF"]
pub type CF13_R = crate::BitReader<bool>;
#[doc = "Field `CF14` reader - Cancellation Finished Tx Buffer 14 - CF"]
pub type CF14_R = crate::BitReader<bool>;
#[doc = "Field `CF15` reader - Cancellation Finished Tx Buffer 15 - CF"]
pub type CF15_R = crate::BitReader<bool>;
#[doc = "Field `CF16` reader - Cancellation Finished Tx Buffer 16 - CF"]
pub type CF16_R = crate::BitReader<bool>;
#[doc = "Field `CF17` reader - Cancellation Finished Tx Buffer 17 - CF"]
pub type CF17_R = crate::BitReader<bool>;
#[doc = "Field `CF18` reader - Cancellation Finished Tx Buffer 18 - CF"]
pub type CF18_R = crate::BitReader<bool>;
#[doc = "Field `CF19` reader - Cancellation Finished Tx Buffer 19 - CF"]
pub type CF19_R = crate::BitReader<bool>;
#[doc = "Field `CF20` reader - Cancellation Finished Tx Buffer 20 - CF"]
pub type CF20_R = crate::BitReader<bool>;
#[doc = "Field `CF21` reader - Cancellation Finished Tx Buffer 21 - CF"]
pub type CF21_R = crate::BitReader<bool>;
#[doc = "Field `CF22` reader - Cancellation Finished Tx Buffer 22 - CF"]
pub type CF22_R = crate::BitReader<bool>;
#[doc = "Field `CF23` reader - Cancellation Finished Tx Buffer 23 - CF"]
pub type CF23_R = crate::BitReader<bool>;
#[doc = "Field `CF24` reader - Cancellation Finished Tx Buffer 24 - CF"]
pub type CF24_R = crate::BitReader<bool>;
#[doc = "Field `CF25` reader - Cancellation Finished Tx Buffer 25 - CF"]
pub type CF25_R = crate::BitReader<bool>;
#[doc = "Field `CF26` reader - Cancellation Finished Tx Buffer 26 - CF"]
pub type CF26_R = crate::BitReader<bool>;
#[doc = "Field `CF27` reader - Cancellation Finished Tx Buffer 27 - CF"]
pub type CF27_R = crate::BitReader<bool>;
#[doc = "Field `CF28` reader - Cancellation Finished Tx Buffer 28 - CF"]
pub type CF28_R = crate::BitReader<bool>;
#[doc = "Field `CF29` reader - Cancellation Finished Tx Buffer 29 - CF"]
pub type CF29_R = crate::BitReader<bool>;
#[doc = "Field `CF30` reader - Cancellation Finished Tx Buffer 30 - CF"]
pub type CF30_R = crate::BitReader<bool>;
#[doc = "Field `CF31` reader - Cancellation Finished Tx Buffer 31 - CF"]
pub type CF31_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bit 0 - Cancellation Finished Tx Buffer 0 - CF"]
    #[inline(always)]
    pub fn cf0(&self) -> CF0_R {
        CF0_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - Cancellation Finished Tx Buffer 1 - CF"]
    #[inline(always)]
    pub fn cf1(&self) -> CF1_R {
        CF1_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - Cancellation Finished Tx Buffer 2 - CF"]
    #[inline(always)]
    pub fn cf2(&self) -> CF2_R {
        CF2_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - Cancellation Finished Tx Buffer 3 - CF"]
    #[inline(always)]
    pub fn cf3(&self) -> CF3_R {
        CF3_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 4 - Cancellation Finished Tx Buffer 4 - CF"]
    #[inline(always)]
    pub fn cf4(&self) -> CF4_R {
        CF4_R::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 5 - Cancellation Finished Tx Buffer 5 - CF"]
    #[inline(always)]
    pub fn cf5(&self) -> CF5_R {
        CF5_R::new(((self.bits >> 5) & 1) != 0)
    }
    #[doc = "Bit 6 - Cancellation Finished Tx Buffer 6 - CF"]
    #[inline(always)]
    pub fn cf6(&self) -> CF6_R {
        CF6_R::new(((self.bits >> 6) & 1) != 0)
    }
    #[doc = "Bit 7 - Cancellation Finished Tx Buffer 7 - CF"]
    #[inline(always)]
    pub fn cf7(&self) -> CF7_R {
        CF7_R::new(((self.bits >> 7) & 1) != 0)
    }
    #[doc = "Bit 8 - Cancellation Finished Tx Buffer 8 - CF"]
    #[inline(always)]
    pub fn cf8(&self) -> CF8_R {
        CF8_R::new(((self.bits >> 8) & 1) != 0)
    }
    #[doc = "Bit 9 - Cancellation Finished Tx Buffer 9 - CF"]
    #[inline(always)]
    pub fn cf9(&self) -> CF9_R {
        CF9_R::new(((self.bits >> 9) & 1) != 0)
    }
    #[doc = "Bit 10 - Cancellation Finished Tx Buffer 10 - CF"]
    #[inline(always)]
    pub fn cf10(&self) -> CF10_R {
        CF10_R::new(((self.bits >> 10) & 1) != 0)
    }
    #[doc = "Bit 11 - Cancellation Finished Tx Buffer 11 - CF"]
    #[inline(always)]
    pub fn cf11(&self) -> CF11_R {
        CF11_R::new(((self.bits >> 11) & 1) != 0)
    }
    #[doc = "Bit 12 - Cancellation Finished Tx Buffer 12 - CF"]
    #[inline(always)]
    pub fn cf12(&self) -> CF12_R {
        CF12_R::new(((self.bits >> 12) & 1) != 0)
    }
    #[doc = "Bit 13 - Cancellation Finished Tx Buffer 13 - CF"]
    #[inline(always)]
    pub fn cf13(&self) -> CF13_R {
        CF13_R::new(((self.bits >> 13) & 1) != 0)
    }
    #[doc = "Bit 14 - Cancellation Finished Tx Buffer 14 - CF"]
    #[inline(always)]
    pub fn cf14(&self) -> CF14_R {
        CF14_R::new(((self.bits >> 14) & 1) != 0)
    }
    #[doc = "Bit 15 - Cancellation Finished Tx Buffer 15 - CF"]
    #[inline(always)]
    pub fn cf15(&self) -> CF15_R {
        CF15_R::new(((self.bits >> 15) & 1) != 0)
    }
    #[doc = "Bit 16 - Cancellation Finished Tx Buffer 16 - CF"]
    #[inline(always)]
    pub fn cf16(&self) -> CF16_R {
        CF16_R::new(((self.bits >> 16) & 1) != 0)
    }
    #[doc = "Bit 17 - Cancellation Finished Tx Buffer 17 - CF"]
    #[inline(always)]
    pub fn cf17(&self) -> CF17_R {
        CF17_R::new(((self.bits >> 17) & 1) != 0)
    }
    #[doc = "Bit 18 - Cancellation Finished Tx Buffer 18 - CF"]
    #[inline(always)]
    pub fn cf18(&self) -> CF18_R {
        CF18_R::new(((self.bits >> 18) & 1) != 0)
    }
    #[doc = "Bit 19 - Cancellation Finished Tx Buffer 19 - CF"]
    #[inline(always)]
    pub fn cf19(&self) -> CF19_R {
        CF19_R::new(((self.bits >> 19) & 1) != 0)
    }
    #[doc = "Bit 20 - Cancellation Finished Tx Buffer 20 - CF"]
    #[inline(always)]
    pub fn cf20(&self) -> CF20_R {
        CF20_R::new(((self.bits >> 20) & 1) != 0)
    }
    #[doc = "Bit 21 - Cancellation Finished Tx Buffer 21 - CF"]
    #[inline(always)]
    pub fn cf21(&self) -> CF21_R {
        CF21_R::new(((self.bits >> 21) & 1) != 0)
    }
    #[doc = "Bit 22 - Cancellation Finished Tx Buffer 22 - CF"]
    #[inline(always)]
    pub fn cf22(&self) -> CF22_R {
        CF22_R::new(((self.bits >> 22) & 1) != 0)
    }
    #[doc = "Bit 23 - Cancellation Finished Tx Buffer 23 - CF"]
    #[inline(always)]
    pub fn cf23(&self) -> CF23_R {
        CF23_R::new(((self.bits >> 23) & 1) != 0)
    }
    #[doc = "Bit 24 - Cancellation Finished Tx Buffer 24 - CF"]
    #[inline(always)]
    pub fn cf24(&self) -> CF24_R {
        CF24_R::new(((self.bits >> 24) & 1) != 0)
    }
    #[doc = "Bit 25 - Cancellation Finished Tx Buffer 25 - CF"]
    #[inline(always)]
    pub fn cf25(&self) -> CF25_R {
        CF25_R::new(((self.bits >> 25) & 1) != 0)
    }
    #[doc = "Bit 26 - Cancellation Finished Tx Buffer 26 - CF"]
    #[inline(always)]
    pub fn cf26(&self) -> CF26_R {
        CF26_R::new(((self.bits >> 26) & 1) != 0)
    }
    #[doc = "Bit 27 - Cancellation Finished Tx Buffer 27 - CF"]
    #[inline(always)]
    pub fn cf27(&self) -> CF27_R {
        CF27_R::new(((self.bits >> 27) & 1) != 0)
    }
    #[doc = "Bit 28 - Cancellation Finished Tx Buffer 28 - CF"]
    #[inline(always)]
    pub fn cf28(&self) -> CF28_R {
        CF28_R::new(((self.bits >> 28) & 1) != 0)
    }
    #[doc = "Bit 29 - Cancellation Finished Tx Buffer 29 - CF"]
    #[inline(always)]
    pub fn cf29(&self) -> CF29_R {
        CF29_R::new(((self.bits >> 29) & 1) != 0)
    }
    #[doc = "Bit 30 - Cancellation Finished Tx Buffer 30 - CF"]
    #[inline(always)]
    pub fn cf30(&self) -> CF30_R {
        CF30_R::new(((self.bits >> 30) & 1) != 0)
    }
    #[doc = "Bit 31 - Cancellation Finished Tx Buffer 31 - CF"]
    #[inline(always)]
    pub fn cf31(&self) -> CF31_R {
        CF31_R::new(((self.bits >> 31) & 1) != 0)
    }
}
#[doc = "Tx Buffer Cancellation Finished 3\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [txbcf3](index.html) module"]
pub struct TXBCF3_SPEC;
impl crate::RegisterSpec for TXBCF3_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [txbcf3::R](R) reader structure"]
impl crate::Readable for TXBCF3_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets TXBCF3 to value 0"]
impl crate::Resettable for TXBCF3_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
