// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `ACCPROT1` reader"]
pub struct R(crate::R<ACCPROT1_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<ACCPROT1_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<ACCPROT1_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<ACCPROT1_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `ACCPROT1` writer"]
pub struct W(crate::W<ACCPROT1_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<ACCPROT1_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<ACCPROT1_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<ACCPROT1_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `APSP` reader - Access Protection Service Request, Primary Groups"]
pub type APSP_R = crate::FieldReader<u8, u8>;
#[doc = "Field `APSP` writer - Access Protection Service Request, Primary Groups"]
pub type APSP_W<'a, const O: u8> = crate::FieldWriter<'a, u32, ACCPROT1_SPEC, u8, u8, 4, O>;
#[doc = "Field `APSS` reader - Access Protection Service Request, Secondary Groups"]
pub type APSS_R = crate::FieldReader<u8, u8>;
#[doc = "Field `APSS` writer - Access Protection Service Request, Secondary Groups"]
pub type APSS_W<'a, const O: u8> = crate::FieldWriter<'a, u32, ACCPROT1_SPEC, u8, u8, 4, O>;
#[doc = "Field `APRP` reader - Access Protection Result Registers, Primary Groups"]
pub type APRP_R = crate::FieldReader<u8, u8>;
#[doc = "Field `APRP` writer - Access Protection Result Registers, Primary Groups"]
pub type APRP_W<'a, const O: u8> = crate::FieldWriter<'a, u32, ACCPROT1_SPEC, u8, u8, 4, O>;
#[doc = "Field `APRS` reader - Access Protection Result Registers, Secondary Groups"]
pub type APRS_R = crate::FieldReader<u8, u8>;
#[doc = "Field `APRS` writer - Access Protection Result Registers, Secondary Groups"]
pub type APRS_W<'a, const O: u8> = crate::FieldWriter<'a, u32, ACCPROT1_SPEC, u8, u8, 4, O>;
impl R {
    #[doc = "Bits 0:3 - Access Protection Service Request, Primary Groups"]
    #[inline(always)]
    pub fn apsp(&self) -> APSP_R {
        APSP_R::new((self.bits & 0x0f) as u8)
    }
    #[doc = "Bits 8:11 - Access Protection Service Request, Secondary Groups"]
    #[inline(always)]
    pub fn apss(&self) -> APSS_R {
        APSS_R::new(((self.bits >> 8) & 0x0f) as u8)
    }
    #[doc = "Bits 16:19 - Access Protection Result Registers, Primary Groups"]
    #[inline(always)]
    pub fn aprp(&self) -> APRP_R {
        APRP_R::new(((self.bits >> 16) & 0x0f) as u8)
    }
    #[doc = "Bits 24:27 - Access Protection Result Registers, Secondary Groups"]
    #[inline(always)]
    pub fn aprs(&self) -> APRS_R {
        APRS_R::new(((self.bits >> 24) & 0x0f) as u8)
    }
}
impl W {
    #[doc = "Bits 0:3 - Access Protection Service Request, Primary Groups"]
    #[inline(always)]
    #[must_use]
    pub fn apsp(&mut self) -> APSP_W<0> {
        APSP_W::new(self)
    }
    #[doc = "Bits 8:11 - Access Protection Service Request, Secondary Groups"]
    #[inline(always)]
    #[must_use]
    pub fn apss(&mut self) -> APSS_W<8> {
        APSS_W::new(self)
    }
    #[doc = "Bits 16:19 - Access Protection Result Registers, Primary Groups"]
    #[inline(always)]
    #[must_use]
    pub fn aprp(&mut self) -> APRP_W<16> {
        APRP_W::new(self)
    }
    #[doc = "Bits 24:27 - Access Protection Result Registers, Secondary Groups"]
    #[inline(always)]
    #[must_use]
    pub fn aprs(&mut self) -> APRS_W<24> {
        APRS_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Access Protection Register 1\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [accprot1](index.html) module"]
pub struct ACCPROT1_SPEC;
impl crate::RegisterSpec for ACCPROT1_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [accprot1::R](R) reader structure"]
impl crate::Readable for ACCPROT1_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [accprot1::W](W) writer structure"]
impl crate::Writable for ACCPROT1_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets ACCPROT1 to value 0"]
impl crate::Resettable for ACCPROT1_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
