// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `FC2FCM` reader"]
pub struct R(crate::R<FC2FCM_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<FC2FCM_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<FC2FCM_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<FC2FCM_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `FC2FCM` writer"]
pub struct W(crate::W<FC2FCM_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<FC2FCM_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<FC2FCM_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<FC2FCM_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `RUNCOMP` reader - Run Control for Compare Channel - RUNCOMP"]
pub type RUNCOMP_R = crate::FieldReader<u8, u8>;
#[doc = "Field `RUNCOMP` writer - Run Control for Compare Channel - RUNCOMP"]
pub type RUNCOMP_W<'a, const O: u8> = crate::FieldWriter<'a, u32, FC2FCM_SPEC, u8, u8, 2, O>;
#[doc = "Field `RUNRAMP` reader - Run Control for Ramp - RUNRAMP"]
pub type RUNRAMP_R = crate::FieldReader<u8, u8>;
#[doc = "Field `RUNRAMP` writer - Run Control for Ramp - RUNRAMP"]
pub type RUNRAMP_W<'a, const O: u8> = crate::FieldWriter<'a, u32, FC2FCM_SPEC, u8, u8, 2, O>;
#[doc = "Field `FCRDIR` reader - Fast Compare Ramp Direction - FCRDIR"]
pub type FCRDIR_R = crate::BitReader<bool>;
#[doc = "Field `FCRDIR` writer - Fast Compare Ramp Direction - FCRDIR"]
pub type FCRDIR_W<'a, const O: u8> = crate::BitWriter<'a, u32, FC2FCM_SPEC, bool, O>;
#[doc = "Field `ANON` reader - Analog Converter Control - ANON"]
pub type ANON_R = crate::BitReader<bool>;
#[doc = "Field `ANON` writer - Analog Converter Control - ANON"]
pub type ANON_W<'a, const O: u8> = crate::BitWriter<'a, u32, FC2FCM_SPEC, bool, O>;
#[doc = "Field `ACSD` reader - Analog Clock Synchronization Delay - ACSD"]
pub type ACSD_R = crate::FieldReader<u8, u8>;
#[doc = "Field `ACSD` writer - Analog Clock Synchronization Delay - ACSD"]
pub type ACSD_W<'a, const O: u8> = crate::FieldWriter<'a, u32, FC2FCM_SPEC, u8, u8, 2, O>;
#[doc = "Field `FCTRIV` reader - Fast Compare Trigger Interval - FCTRIV"]
pub type FCTRIV_R = crate::FieldReader<u8, u8>;
#[doc = "Field `FCTRIV` writer - Fast Compare Trigger Interval - FCTRIV"]
pub type FCTRIV_W<'a, const O: u8> = crate::FieldWriter<'a, u32, FC2FCM_SPEC, u8, u8, 8, O>;
#[doc = "Field `SRG` reader - Service Request Generation - SRG"]
pub type SRG_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SRG` writer - Service Request Generation - SRG"]
pub type SRG_W<'a, const O: u8> = crate::FieldWriter<'a, u32, FC2FCM_SPEC, u8, u8, 2, O>;
#[doc = "Field `AUE` reader - Automatic Update Enable - AUE"]
pub type AUE_R = crate::FieldReader<u8, u8>;
#[doc = "Field `AUE` writer - Automatic Update Enable - AUE"]
pub type AUE_W<'a, const O: u8> = crate::FieldWriter<'a, u32, FC2FCM_SPEC, u8, u8, 2, O>;
#[doc = "Field `SSE` reader - Sample Synchronization Enable - SSE"]
pub type SSE_R = crate::BitReader<bool>;
#[doc = "Field `SSE` writer - Sample Synchronization Enable - SSE"]
pub type SSE_W<'a, const O: u8> = crate::BitWriter<'a, u32, FC2FCM_SPEC, bool, O>;
#[doc = "Field `FCMWC` writer - Write Control for Fast Compare Mode Configuration - FCMWC"]
pub type FCMWC_W<'a, const O: u8> = crate::BitWriter<'a, u32, FC2FCM_SPEC, bool, O>;
#[doc = "Field `FCREF` reader - Fast Compare Reference Value - FCREF"]
pub type FCREF_R = crate::FieldReader<u16, u16>;
#[doc = "Field `FCREF` writer - Fast Compare Reference Value - FCREF"]
pub type FCREF_W<'a, const O: u8> = crate::FieldWriter<'a, u32, FC2FCM_SPEC, u16, u16, 10, O>;
impl R {
    #[doc = "Bits 0:1 - Run Control for Compare Channel - RUNCOMP"]
    #[inline(always)]
    pub fn runcomp(&self) -> RUNCOMP_R {
        RUNCOMP_R::new((self.bits & 3) as u8)
    }
    #[doc = "Bits 2:3 - Run Control for Ramp - RUNRAMP"]
    #[inline(always)]
    pub fn runramp(&self) -> RUNRAMP_R {
        RUNRAMP_R::new(((self.bits >> 2) & 3) as u8)
    }
    #[doc = "Bit 4 - Fast Compare Ramp Direction - FCRDIR"]
    #[inline(always)]
    pub fn fcrdir(&self) -> FCRDIR_R {
        FCRDIR_R::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 5 - Analog Converter Control - ANON"]
    #[inline(always)]
    pub fn anon(&self) -> ANON_R {
        ANON_R::new(((self.bits >> 5) & 1) != 0)
    }
    #[doc = "Bits 6:7 - Analog Clock Synchronization Delay - ACSD"]
    #[inline(always)]
    pub fn acsd(&self) -> ACSD_R {
        ACSD_R::new(((self.bits >> 6) & 3) as u8)
    }
    #[doc = "Bits 8:15 - Fast Compare Trigger Interval - FCTRIV"]
    #[inline(always)]
    pub fn fctriv(&self) -> FCTRIV_R {
        FCTRIV_R::new(((self.bits >> 8) & 0xff) as u8)
    }
    #[doc = "Bits 16:17 - Service Request Generation - SRG"]
    #[inline(always)]
    pub fn srg(&self) -> SRG_R {
        SRG_R::new(((self.bits >> 16) & 3) as u8)
    }
    #[doc = "Bits 18:19 - Automatic Update Enable - AUE"]
    #[inline(always)]
    pub fn aue(&self) -> AUE_R {
        AUE_R::new(((self.bits >> 18) & 3) as u8)
    }
    #[doc = "Bit 20 - Sample Synchronization Enable - SSE"]
    #[inline(always)]
    pub fn sse(&self) -> SSE_R {
        SSE_R::new(((self.bits >> 20) & 1) != 0)
    }
    #[doc = "Bits 22:31 - Fast Compare Reference Value - FCREF"]
    #[inline(always)]
    pub fn fcref(&self) -> FCREF_R {
        FCREF_R::new(((self.bits >> 22) & 0x03ff) as u16)
    }
}
impl W {
    #[doc = "Bits 0:1 - Run Control for Compare Channel - RUNCOMP"]
    #[inline(always)]
    #[must_use]
    pub fn runcomp(&mut self) -> RUNCOMP_W<0> {
        RUNCOMP_W::new(self)
    }
    #[doc = "Bits 2:3 - Run Control for Ramp - RUNRAMP"]
    #[inline(always)]
    #[must_use]
    pub fn runramp(&mut self) -> RUNRAMP_W<2> {
        RUNRAMP_W::new(self)
    }
    #[doc = "Bit 4 - Fast Compare Ramp Direction - FCRDIR"]
    #[inline(always)]
    #[must_use]
    pub fn fcrdir(&mut self) -> FCRDIR_W<4> {
        FCRDIR_W::new(self)
    }
    #[doc = "Bit 5 - Analog Converter Control - ANON"]
    #[inline(always)]
    #[must_use]
    pub fn anon(&mut self) -> ANON_W<5> {
        ANON_W::new(self)
    }
    #[doc = "Bits 6:7 - Analog Clock Synchronization Delay - ACSD"]
    #[inline(always)]
    #[must_use]
    pub fn acsd(&mut self) -> ACSD_W<6> {
        ACSD_W::new(self)
    }
    #[doc = "Bits 8:15 - Fast Compare Trigger Interval - FCTRIV"]
    #[inline(always)]
    #[must_use]
    pub fn fctriv(&mut self) -> FCTRIV_W<8> {
        FCTRIV_W::new(self)
    }
    #[doc = "Bits 16:17 - Service Request Generation - SRG"]
    #[inline(always)]
    #[must_use]
    pub fn srg(&mut self) -> SRG_W<16> {
        SRG_W::new(self)
    }
    #[doc = "Bits 18:19 - Automatic Update Enable - AUE"]
    #[inline(always)]
    #[must_use]
    pub fn aue(&mut self) -> AUE_W<18> {
        AUE_W::new(self)
    }
    #[doc = "Bit 20 - Sample Synchronization Enable - SSE"]
    #[inline(always)]
    #[must_use]
    pub fn sse(&mut self) -> SSE_W<20> {
        SSE_W::new(self)
    }
    #[doc = "Bit 21 - Write Control for Fast Compare Mode Configuration - FCMWC"]
    #[inline(always)]
    #[must_use]
    pub fn fcmwc(&mut self) -> FCMWC_W<21> {
        FCMWC_W::new(self)
    }
    #[doc = "Bits 22:31 - Fast Compare Reference Value - FCREF"]
    #[inline(always)]
    #[must_use]
    pub fn fcref(&mut self) -> FCREF_W<22> {
        FCREF_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Fast Compare Mode Register, FC Channel 2\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [fc2fcm](index.html) module"]
pub struct FC2FCM_SPEC;
impl crate::RegisterSpec for FC2FCM_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [fc2fcm::R](R) reader structure"]
impl crate::Readable for FC2FCM_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [fc2fcm::W](W) writer structure"]
impl crate::Writable for FC2FCM_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets FC2FCM to value 0"]
impl crate::Resettable for FC2FCM_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
