// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `G1EMUXCTR` reader"]
pub struct R(crate::R<G1EMUXCTR_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<G1EMUXCTR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<G1EMUXCTR_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<G1EMUXCTR_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `G1EMUXCTR` writer"]
pub struct W(crate::W<G1EMUXCTR_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<G1EMUXCTR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<G1EMUXCTR_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<G1EMUXCTR_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `EMUXSET` reader - External Multiplexer Start Selection - EMUXSET"]
pub type EMUXSET_R = crate::FieldReader<u8, u8>;
#[doc = "Field `EMUXSET` writer - External Multiplexer Start Selection - EMUXSET"]
pub type EMUXSET_W<'a, const O: u8> = crate::FieldWriter<'a, u32, G1EMUXCTR_SPEC, u8, u8, 3, O>;
#[doc = "Field `EMUXMODE` reader - External Multiplexer Mode - EMUXMODE"]
pub type EMUXMODE_R = crate::FieldReader<u8, u8>;
#[doc = "Field `EMUXMODE` writer - External Multiplexer Mode - EMUXMODE"]
pub type EMUXMODE_W<'a, const O: u8> = crate::FieldWriter<'a, u32, G1EMUXCTR_SPEC, u8, u8, 3, O>;
#[doc = "Field `EMXCOD` reader - External Multiplexer Coding Scheme - EMXCOD"]
pub type EMXCOD_R = crate::BitReader<bool>;
#[doc = "Field `EMXCOD` writer - External Multiplexer Coding Scheme - EMXCOD"]
pub type EMXCOD_W<'a, const O: u8> = crate::BitWriter<'a, u32, G1EMUXCTR_SPEC, bool, O>;
#[doc = "Field `EMXST` reader - External Multiplexer Sample Time Control - EMXST"]
pub type EMXST_R = crate::BitReader<bool>;
#[doc = "Field `EMXST` writer - External Multiplexer Sample Time Control - EMXST"]
pub type EMXST_W<'a, const O: u8> = crate::BitWriter<'a, u32, G1EMUXCTR_SPEC, bool, O>;
#[doc = "Field `EMXCSS` reader - External Multiplexer Channel Selection Style - EMXCSS"]
pub type EMXCSS_R = crate::BitReader<bool>;
#[doc = "Field `EMXCSS` writer - External Multiplexer Channel Selection Style - EMXCSS"]
pub type EMXCSS_W<'a, const O: u8> = crate::BitWriter<'a, u32, G1EMUXCTR_SPEC, bool, O>;
#[doc = "Field `EMXWC` writer - Write Control for EMUX Configuration - EMXWC"]
pub type EMXWC_W<'a, const O: u8> = crate::BitWriter<'a, u32, G1EMUXCTR_SPEC, bool, O>;
#[doc = "Field `EMUXACT` reader - External Multiplexer Actual Selection - EMUXACT"]
pub type EMUXACT_R = crate::FieldReader<u8, u8>;
#[doc = "Field `EMUXCCB` reader - External Multiplexer Channel Selection for Block Mode - EMUXCCB"]
pub type EMUXCCB_R = crate::FieldReader<u8, u8>;
#[doc = "Field `EMUXCCB` writer - External Multiplexer Channel Selection for Block Mode - EMUXCCB"]
pub type EMUXCCB_W<'a, const O: u8> = crate::FieldWriter<'a, u32, G1EMUXCTR_SPEC, u8, u8, 5, O>;
impl R {
    #[doc = "Bits 0:2 - External Multiplexer Start Selection - EMUXSET"]
    #[inline(always)]
    pub fn emuxset(&self) -> EMUXSET_R {
        EMUXSET_R::new((self.bits & 7) as u8)
    }
    #[doc = "Bits 4:6 - External Multiplexer Mode - EMUXMODE"]
    #[inline(always)]
    pub fn emuxmode(&self) -> EMUXMODE_R {
        EMUXMODE_R::new(((self.bits >> 4) & 7) as u8)
    }
    #[doc = "Bit 12 - External Multiplexer Coding Scheme - EMXCOD"]
    #[inline(always)]
    pub fn emxcod(&self) -> EMXCOD_R {
        EMXCOD_R::new(((self.bits >> 12) & 1) != 0)
    }
    #[doc = "Bit 13 - External Multiplexer Sample Time Control - EMXST"]
    #[inline(always)]
    pub fn emxst(&self) -> EMXST_R {
        EMXST_R::new(((self.bits >> 13) & 1) != 0)
    }
    #[doc = "Bit 14 - External Multiplexer Channel Selection Style - EMXCSS"]
    #[inline(always)]
    pub fn emxcss(&self) -> EMXCSS_R {
        EMXCSS_R::new(((self.bits >> 14) & 1) != 0)
    }
    #[doc = "Bits 16:18 - External Multiplexer Actual Selection - EMUXACT"]
    #[inline(always)]
    pub fn emuxact(&self) -> EMUXACT_R {
        EMUXACT_R::new(((self.bits >> 16) & 7) as u8)
    }
    #[doc = "Bits 20:24 - External Multiplexer Channel Selection for Block Mode - EMUXCCB"]
    #[inline(always)]
    pub fn emuxccb(&self) -> EMUXCCB_R {
        EMUXCCB_R::new(((self.bits >> 20) & 0x1f) as u8)
    }
}
impl W {
    #[doc = "Bits 0:2 - External Multiplexer Start Selection - EMUXSET"]
    #[inline(always)]
    #[must_use]
    pub fn emuxset(&mut self) -> EMUXSET_W<0> {
        EMUXSET_W::new(self)
    }
    #[doc = "Bits 4:6 - External Multiplexer Mode - EMUXMODE"]
    #[inline(always)]
    #[must_use]
    pub fn emuxmode(&mut self) -> EMUXMODE_W<4> {
        EMUXMODE_W::new(self)
    }
    #[doc = "Bit 12 - External Multiplexer Coding Scheme - EMXCOD"]
    #[inline(always)]
    #[must_use]
    pub fn emxcod(&mut self) -> EMXCOD_W<12> {
        EMXCOD_W::new(self)
    }
    #[doc = "Bit 13 - External Multiplexer Sample Time Control - EMXST"]
    #[inline(always)]
    #[must_use]
    pub fn emxst(&mut self) -> EMXST_W<13> {
        EMXST_W::new(self)
    }
    #[doc = "Bit 14 - External Multiplexer Channel Selection Style - EMXCSS"]
    #[inline(always)]
    #[must_use]
    pub fn emxcss(&mut self) -> EMXCSS_W<14> {
        EMXCSS_W::new(self)
    }
    #[doc = "Bit 15 - Write Control for EMUX Configuration - EMXWC"]
    #[inline(always)]
    #[must_use]
    pub fn emxwc(&mut self) -> EMXWC_W<15> {
        EMXWC_W::new(self)
    }
    #[doc = "Bits 20:24 - External Multiplexer Channel Selection for Block Mode - EMUXCCB"]
    #[inline(always)]
    #[must_use]
    pub fn emuxccb(&mut self) -> EMUXCCB_W<20> {
        EMUXCCB_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "External Multiplexer Control Reg., Group 1\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [g1emuxctr](index.html) module"]
pub struct G1EMUXCTR_SPEC;
impl crate::RegisterSpec for G1EMUXCTR_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [g1emuxctr::R](R) reader structure"]
impl crate::Readable for G1EMUXCTR_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [g1emuxctr::W](W) writer structure"]
impl crate::Writable for G1EMUXCTR_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets G1EMUXCTR to value 0"]
impl crate::Resettable for G1EMUXCTR_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
