// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `G3QSR2` reader"]
pub struct R(crate::R<G3QSR2_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<G3QSR2_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<G3QSR2_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<G3QSR2_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `FILL` reader - Filling Level for Queue - FILL"]
pub type FILL_R = crate::FieldReader<u8, u8>;
#[doc = "Field `EMPTY` reader - Queue Empty - EMPTY"]
pub type EMPTY_R = crate::BitReader<bool>;
#[doc = "Field `REQGT` reader - Request Gate Level - REQGT"]
pub type REQGT_R = crate::BitReader<bool>;
#[doc = "Field `EV` reader - Event Detected - EV"]
pub type EV_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bits 0:3 - Filling Level for Queue - FILL"]
    #[inline(always)]
    pub fn fill(&self) -> FILL_R {
        FILL_R::new((self.bits & 0x0f) as u8)
    }
    #[doc = "Bit 5 - Queue Empty - EMPTY"]
    #[inline(always)]
    pub fn empty(&self) -> EMPTY_R {
        EMPTY_R::new(((self.bits >> 5) & 1) != 0)
    }
    #[doc = "Bit 7 - Request Gate Level - REQGT"]
    #[inline(always)]
    pub fn reqgt(&self) -> REQGT_R {
        REQGT_R::new(((self.bits >> 7) & 1) != 0)
    }
    #[doc = "Bit 8 - Event Detected - EV"]
    #[inline(always)]
    pub fn ev(&self) -> EV_R {
        EV_R::new(((self.bits >> 8) & 1) != 0)
    }
}
#[doc = "Queue 2 Status Register, Group 3\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [g3qsr2](index.html) module"]
pub struct G3QSR2_SPEC;
impl crate::RegisterSpec for G3QSR2_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [g3qsr2::R](R) reader structure"]
impl crate::Readable for G3QSR2_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets G3QSR2 to value 0x20"]
impl crate::Resettable for G3QSR2_SPEC {
    const RESET_VALUE: Self::Ux = 0x20;
}
