// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `INP` reader"]
pub struct R(crate::R<INP_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<INP_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<INP_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<INP_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `INP` writer"]
pub struct W(crate::W<INP_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<INP_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<INP_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<INP_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `INPCC60` reader - Interrupt Node Pointer for Channel CC6x Interrupts INPCC6x (x=0,1,2)"]
pub type INPCC60_R = crate::FieldReader<u8, u8>;
#[doc = "Field `INPCC60` writer - Interrupt Node Pointer for Channel CC6x Interrupts INPCC6x (x=0,1,2)"]
pub type INPCC60_W<'a, const O: u8> = crate::FieldWriter<'a, u32, INP_SPEC, u8, u8, 2, O>;
#[doc = "Field `INPCC61` reader - Interrupt Node Pointer for Channel CC6x Interrupts INPCC6x (x=0,1,2)"]
pub type INPCC61_R = crate::FieldReader<u8, u8>;
#[doc = "Field `INPCC61` writer - Interrupt Node Pointer for Channel CC6x Interrupts INPCC6x (x=0,1,2)"]
pub type INPCC61_W<'a, const O: u8> = crate::FieldWriter<'a, u32, INP_SPEC, u8, u8, 2, O>;
#[doc = "Field `INPCC62` reader - Interrupt Node Pointer for Channel CC6x Interrupts INPCC6x (x=0,1,2)"]
pub type INPCC62_R = crate::FieldReader<u8, u8>;
#[doc = "Field `INPCC62` writer - Interrupt Node Pointer for Channel CC6x Interrupts INPCC6x (x=0,1,2)"]
pub type INPCC62_W<'a, const O: u8> = crate::FieldWriter<'a, u32, INP_SPEC, u8, u8, 2, O>;
#[doc = "Field `INPCHE` reader - Interrupt Node Pointer for the CHE Interrupt - INPCHE"]
pub type INPCHE_R = crate::FieldReader<u8, u8>;
#[doc = "Field `INPCHE` writer - Interrupt Node Pointer for the CHE Interrupt - INPCHE"]
pub type INPCHE_W<'a, const O: u8> = crate::FieldWriter<'a, u32, INP_SPEC, u8, u8, 2, O>;
#[doc = "Field `INPERR` reader - Interrupt Node Pointer for Error Interrupts - INPERR"]
pub type INPERR_R = crate::FieldReader<u8, u8>;
#[doc = "Field `INPERR` writer - Interrupt Node Pointer for Error Interrupts - INPERR"]
pub type INPERR_W<'a, const O: u8> = crate::FieldWriter<'a, u32, INP_SPEC, u8, u8, 2, O>;
#[doc = "Field `INPT12` reader - Interrupt Node Pointer for Timer12 Interrupts - INPT12"]
pub type INPT12_R = crate::FieldReader<u8, u8>;
#[doc = "Field `INPT12` writer - Interrupt Node Pointer for Timer12 Interrupts - INPT12"]
pub type INPT12_W<'a, const O: u8> = crate::FieldWriter<'a, u32, INP_SPEC, u8, u8, 2, O>;
#[doc = "Field `INPT13` reader - Interrupt Node Pointer for Timer13 Interrupt - INPT13"]
pub type INPT13_R = crate::FieldReader<u8, u8>;
#[doc = "Field `INPT13` writer - Interrupt Node Pointer for Timer13 Interrupt - INPT13"]
pub type INPT13_W<'a, const O: u8> = crate::FieldWriter<'a, u32, INP_SPEC, u8, u8, 2, O>;
impl R {
    #[doc = "Bits 0:1 - Interrupt Node Pointer for Channel CC6x Interrupts INPCC6x (x=0,1,2)"]
    #[inline(always)]
    pub fn inpcc60(&self) -> INPCC60_R {
        INPCC60_R::new((self.bits & 3) as u8)
    }
    #[doc = "Bits 2:3 - Interrupt Node Pointer for Channel CC6x Interrupts INPCC6x (x=0,1,2)"]
    #[inline(always)]
    pub fn inpcc61(&self) -> INPCC61_R {
        INPCC61_R::new(((self.bits >> 2) & 3) as u8)
    }
    #[doc = "Bits 4:5 - Interrupt Node Pointer for Channel CC6x Interrupts INPCC6x (x=0,1,2)"]
    #[inline(always)]
    pub fn inpcc62(&self) -> INPCC62_R {
        INPCC62_R::new(((self.bits >> 4) & 3) as u8)
    }
    #[doc = "Bits 6:7 - Interrupt Node Pointer for the CHE Interrupt - INPCHE"]
    #[inline(always)]
    pub fn inpche(&self) -> INPCHE_R {
        INPCHE_R::new(((self.bits >> 6) & 3) as u8)
    }
    #[doc = "Bits 8:9 - Interrupt Node Pointer for Error Interrupts - INPERR"]
    #[inline(always)]
    pub fn inperr(&self) -> INPERR_R {
        INPERR_R::new(((self.bits >> 8) & 3) as u8)
    }
    #[doc = "Bits 10:11 - Interrupt Node Pointer for Timer12 Interrupts - INPT12"]
    #[inline(always)]
    pub fn inpt12(&self) -> INPT12_R {
        INPT12_R::new(((self.bits >> 10) & 3) as u8)
    }
    #[doc = "Bits 12:13 - Interrupt Node Pointer for Timer13 Interrupt - INPT13"]
    #[inline(always)]
    pub fn inpt13(&self) -> INPT13_R {
        INPT13_R::new(((self.bits >> 12) & 3) as u8)
    }
}
impl W {
    #[doc = "Bits 0:1 - Interrupt Node Pointer for Channel CC6x Interrupts INPCC6x (x=0,1,2)"]
    #[inline(always)]
    #[must_use]
    pub fn inpcc60(&mut self) -> INPCC60_W<0> {
        INPCC60_W::new(self)
    }
    #[doc = "Bits 2:3 - Interrupt Node Pointer for Channel CC6x Interrupts INPCC6x (x=0,1,2)"]
    #[inline(always)]
    #[must_use]
    pub fn inpcc61(&mut self) -> INPCC61_W<2> {
        INPCC61_W::new(self)
    }
    #[doc = "Bits 4:5 - Interrupt Node Pointer for Channel CC6x Interrupts INPCC6x (x=0,1,2)"]
    #[inline(always)]
    #[must_use]
    pub fn inpcc62(&mut self) -> INPCC62_W<4> {
        INPCC62_W::new(self)
    }
    #[doc = "Bits 6:7 - Interrupt Node Pointer for the CHE Interrupt - INPCHE"]
    #[inline(always)]
    #[must_use]
    pub fn inpche(&mut self) -> INPCHE_W<6> {
        INPCHE_W::new(self)
    }
    #[doc = "Bits 8:9 - Interrupt Node Pointer for Error Interrupts - INPERR"]
    #[inline(always)]
    #[must_use]
    pub fn inperr(&mut self) -> INPERR_W<8> {
        INPERR_W::new(self)
    }
    #[doc = "Bits 10:11 - Interrupt Node Pointer for Timer12 Interrupts - INPT12"]
    #[inline(always)]
    #[must_use]
    pub fn inpt12(&mut self) -> INPT12_W<10> {
        INPT12_W::new(self)
    }
    #[doc = "Bits 12:13 - Interrupt Node Pointer for Timer13 Interrupt - INPT13"]
    #[inline(always)]
    #[must_use]
    pub fn inpt13(&mut self) -> INPT13_W<12> {
        INPT13_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Interrupt Node Pointer Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [inp](index.html) module"]
pub struct INP_SPEC;
impl crate::RegisterSpec for INP_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [inp::R](R) reader structure"]
impl crate::Readable for INP_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [inp::W](W) writer structure"]
impl crate::Writable for INP_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets INP to value 0x3940"]
impl crate::Resettable for INP_SPEC {
    const RESET_VALUE: Self::Ux = 0x3940;
}
