// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `MCMOUT` reader"]
pub struct R(crate::R<MCMOUT_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<MCMOUT_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<MCMOUT_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<MCMOUT_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `MCMP` reader - Multi-Channel PWM Pattern - MCMP"]
pub type MCMP_R = crate::FieldReader<u8, u8>;
#[doc = "Field `R` reader - Reminder Flag - R"]
pub type R_R = crate::BitReader<bool>;
#[doc = "Field `EXPH` reader - Expected Hall Pattern - EXPH"]
pub type EXPH_R = crate::FieldReader<u8, u8>;
#[doc = "Field `CURH` reader - Current Hall Pattern - CURH"]
pub type CURH_R = crate::FieldReader<u8, u8>;
impl R {
    #[doc = "Bits 0:5 - Multi-Channel PWM Pattern - MCMP"]
    #[inline(always)]
    pub fn mcmp(&self) -> MCMP_R {
        MCMP_R::new((self.bits & 0x3f) as u8)
    }
    #[doc = "Bit 6 - Reminder Flag - R"]
    #[inline(always)]
    pub fn r(&self) -> R_R {
        R_R::new(((self.bits >> 6) & 1) != 0)
    }
    #[doc = "Bits 8:10 - Expected Hall Pattern - EXPH"]
    #[inline(always)]
    pub fn exph(&self) -> EXPH_R {
        EXPH_R::new(((self.bits >> 8) & 7) as u8)
    }
    #[doc = "Bits 11:13 - Current Hall Pattern - CURH"]
    #[inline(always)]
    pub fn curh(&self) -> CURH_R {
        CURH_R::new(((self.bits >> 11) & 7) as u8)
    }
}
#[doc = "Multi-Channel Mode Output Register\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [mcmout](index.html) module"]
pub struct MCMOUT_SPEC;
impl crate::RegisterSpec for MCMOUT_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [mcmout::R](R) reader structure"]
impl crate::Readable for MCMOUT_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets MCMOUT to value 0"]
impl crate::Resettable for MCMOUT_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
