// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `T12DTC` reader"]
pub struct R(crate::R<T12DTC_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<T12DTC_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<T12DTC_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<T12DTC_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `T12DTC` writer"]
pub struct W(crate::W<T12DTC_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<T12DTC_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<T12DTC_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<T12DTC_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `DTM` reader - Dead-Time - DTM"]
pub type DTM_R = crate::FieldReader<u8, u8>;
#[doc = "Field `DTM` writer - Dead-Time - DTM"]
pub type DTM_W<'a, const O: u8> = crate::FieldWriter<'a, u32, T12DTC_SPEC, u8, u8, 8, O>;
#[doc = "Field `DTE0` reader - Dead Time Enable Bits DTEx (x=0,1,2)"]
pub type DTE0_R = crate::BitReader<bool>;
#[doc = "Field `DTE0` writer - Dead Time Enable Bits DTEx (x=0,1,2)"]
pub type DTE0_W<'a, const O: u8> = crate::BitWriter<'a, u32, T12DTC_SPEC, bool, O>;
#[doc = "Field `DTE1` reader - Dead Time Enable Bits DTEx (x=0,1,2)"]
pub type DTE1_R = crate::BitReader<bool>;
#[doc = "Field `DTE1` writer - Dead Time Enable Bits DTEx (x=0,1,2)"]
pub type DTE1_W<'a, const O: u8> = crate::BitWriter<'a, u32, T12DTC_SPEC, bool, O>;
#[doc = "Field `DTE2` reader - Dead Time Enable Bits DTEx (x=0,1,2)"]
pub type DTE2_R = crate::BitReader<bool>;
#[doc = "Field `DTE2` writer - Dead Time Enable Bits DTEx (x=0,1,2)"]
pub type DTE2_W<'a, const O: u8> = crate::BitWriter<'a, u32, T12DTC_SPEC, bool, O>;
#[doc = "Field `DTR0` reader - Dead Time Run Indication Bits DTRx (x=1,2,3)"]
pub type DTR0_R = crate::BitReader<bool>;
#[doc = "Field `DTR1` reader - Dead Time Run Indication Bits DTRx (x=1,2,3)"]
pub type DTR1_R = crate::BitReader<bool>;
#[doc = "Field `DTR2` reader - Dead Time Run Indication Bits DTRx (x=1,2,3)"]
pub type DTR2_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bits 0:7 - Dead-Time - DTM"]
    #[inline(always)]
    pub fn dtm(&self) -> DTM_R {
        DTM_R::new((self.bits & 0xff) as u8)
    }
    #[doc = "Bit 8 - Dead Time Enable Bits DTEx (x=0,1,2)"]
    #[inline(always)]
    pub fn dte0(&self) -> DTE0_R {
        DTE0_R::new(((self.bits >> 8) & 1) != 0)
    }
    #[doc = "Bit 9 - Dead Time Enable Bits DTEx (x=0,1,2)"]
    #[inline(always)]
    pub fn dte1(&self) -> DTE1_R {
        DTE1_R::new(((self.bits >> 9) & 1) != 0)
    }
    #[doc = "Bit 10 - Dead Time Enable Bits DTEx (x=0,1,2)"]
    #[inline(always)]
    pub fn dte2(&self) -> DTE2_R {
        DTE2_R::new(((self.bits >> 10) & 1) != 0)
    }
    #[doc = "Bit 12 - Dead Time Run Indication Bits DTRx (x=1,2,3)"]
    #[inline(always)]
    pub fn dtr0(&self) -> DTR0_R {
        DTR0_R::new(((self.bits >> 12) & 1) != 0)
    }
    #[doc = "Bit 13 - Dead Time Run Indication Bits DTRx (x=1,2,3)"]
    #[inline(always)]
    pub fn dtr1(&self) -> DTR1_R {
        DTR1_R::new(((self.bits >> 13) & 1) != 0)
    }
    #[doc = "Bit 14 - Dead Time Run Indication Bits DTRx (x=1,2,3)"]
    #[inline(always)]
    pub fn dtr2(&self) -> DTR2_R {
        DTR2_R::new(((self.bits >> 14) & 1) != 0)
    }
}
impl W {
    #[doc = "Bits 0:7 - Dead-Time - DTM"]
    #[inline(always)]
    #[must_use]
    pub fn dtm(&mut self) -> DTM_W<0> {
        DTM_W::new(self)
    }
    #[doc = "Bit 8 - Dead Time Enable Bits DTEx (x=0,1,2)"]
    #[inline(always)]
    #[must_use]
    pub fn dte0(&mut self) -> DTE0_W<8> {
        DTE0_W::new(self)
    }
    #[doc = "Bit 9 - Dead Time Enable Bits DTEx (x=0,1,2)"]
    #[inline(always)]
    #[must_use]
    pub fn dte1(&mut self) -> DTE1_W<9> {
        DTE1_W::new(self)
    }
    #[doc = "Bit 10 - Dead Time Enable Bits DTEx (x=0,1,2)"]
    #[inline(always)]
    #[must_use]
    pub fn dte2(&mut self) -> DTE2_W<10> {
        DTE2_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Dead-Time Control Register for Timer12\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [t12dtc](index.html) module"]
pub struct T12DTC_SPEC;
impl crate::RegisterSpec for T12DTC_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [t12dtc::R](R) reader structure"]
impl crate::Readable for T12DTC_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [t12dtc::W](W) writer structure"]
impl crate::Writable for T12DTC_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets T12DTC to value 0"]
impl crate::Resettable for T12DTC_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
