// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `TCTR2` reader"]
pub struct R(crate::R<TCTR2_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<TCTR2_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<TCTR2_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<TCTR2_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `TCTR2` writer"]
pub struct W(crate::W<TCTR2_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<TCTR2_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<TCTR2_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<TCTR2_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `T12SSC` reader - Timer T12 Single Shot Control - T12SSC"]
pub type T12SSC_R = crate::BitReader<bool>;
#[doc = "Field `T12SSC` writer - Timer T12 Single Shot Control - T12SSC"]
pub type T12SSC_W<'a, const O: u8> = crate::BitWriter<'a, u32, TCTR2_SPEC, bool, O>;
#[doc = "Field `T13SSC` reader - Timer T13 Single Shot Control - T13SSC"]
pub type T13SSC_R = crate::BitReader<bool>;
#[doc = "Field `T13SSC` writer - Timer T13 Single Shot Control - T13SSC"]
pub type T13SSC_W<'a, const O: u8> = crate::BitWriter<'a, u32, TCTR2_SPEC, bool, O>;
#[doc = "Field `T13TEC` reader - T13 Trigger Event Control - T13TEC"]
pub type T13TEC_R = crate::FieldReader<u8, u8>;
#[doc = "Field `T13TEC` writer - T13 Trigger Event Control - T13TEC"]
pub type T13TEC_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TCTR2_SPEC, u8, u8, 3, O>;
#[doc = "Field `T13TED` reader - Timer T13 Trigger Event Direction - T13TED"]
pub type T13TED_R = crate::FieldReader<u8, u8>;
#[doc = "Field `T13TED` writer - Timer T13 Trigger Event Direction - T13TED"]
pub type T13TED_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TCTR2_SPEC, u8, u8, 2, O>;
#[doc = "Field `T12RSEL` reader - Timer T12 External Run Selection - T12RSEL"]
pub type T12RSEL_R = crate::FieldReader<u8, u8>;
#[doc = "Field `T12RSEL` writer - Timer T12 External Run Selection - T12RSEL"]
pub type T12RSEL_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TCTR2_SPEC, u8, u8, 2, O>;
#[doc = "Field `T13RSEL` reader - Timer T13 External Run Selection - T13RSEL"]
pub type T13RSEL_R = crate::FieldReader<u8, u8>;
#[doc = "Field `T13RSEL` writer - Timer T13 External Run Selection - T13RSEL"]
pub type T13RSEL_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TCTR2_SPEC, u8, u8, 2, O>;
impl R {
    #[doc = "Bit 0 - Timer T12 Single Shot Control - T12SSC"]
    #[inline(always)]
    pub fn t12ssc(&self) -> T12SSC_R {
        T12SSC_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - Timer T13 Single Shot Control - T13SSC"]
    #[inline(always)]
    pub fn t13ssc(&self) -> T13SSC_R {
        T13SSC_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bits 2:4 - T13 Trigger Event Control - T13TEC"]
    #[inline(always)]
    pub fn t13tec(&self) -> T13TEC_R {
        T13TEC_R::new(((self.bits >> 2) & 7) as u8)
    }
    #[doc = "Bits 5:6 - Timer T13 Trigger Event Direction - T13TED"]
    #[inline(always)]
    pub fn t13ted(&self) -> T13TED_R {
        T13TED_R::new(((self.bits >> 5) & 3) as u8)
    }
    #[doc = "Bits 8:9 - Timer T12 External Run Selection - T12RSEL"]
    #[inline(always)]
    pub fn t12rsel(&self) -> T12RSEL_R {
        T12RSEL_R::new(((self.bits >> 8) & 3) as u8)
    }
    #[doc = "Bits 10:11 - Timer T13 External Run Selection - T13RSEL"]
    #[inline(always)]
    pub fn t13rsel(&self) -> T13RSEL_R {
        T13RSEL_R::new(((self.bits >> 10) & 3) as u8)
    }
}
impl W {
    #[doc = "Bit 0 - Timer T12 Single Shot Control - T12SSC"]
    #[inline(always)]
    #[must_use]
    pub fn t12ssc(&mut self) -> T12SSC_W<0> {
        T12SSC_W::new(self)
    }
    #[doc = "Bit 1 - Timer T13 Single Shot Control - T13SSC"]
    #[inline(always)]
    #[must_use]
    pub fn t13ssc(&mut self) -> T13SSC_W<1> {
        T13SSC_W::new(self)
    }
    #[doc = "Bits 2:4 - T13 Trigger Event Control - T13TEC"]
    #[inline(always)]
    #[must_use]
    pub fn t13tec(&mut self) -> T13TEC_W<2> {
        T13TEC_W::new(self)
    }
    #[doc = "Bits 5:6 - Timer T13 Trigger Event Direction - T13TED"]
    #[inline(always)]
    #[must_use]
    pub fn t13ted(&mut self) -> T13TED_W<5> {
        T13TED_W::new(self)
    }
    #[doc = "Bits 8:9 - Timer T12 External Run Selection - T12RSEL"]
    #[inline(always)]
    #[must_use]
    pub fn t12rsel(&mut self) -> T12RSEL_W<8> {
        T12RSEL_W::new(self)
    }
    #[doc = "Bits 10:11 - Timer T13 External Run Selection - T13RSEL"]
    #[inline(always)]
    #[must_use]
    pub fn t13rsel(&mut self) -> T13RSEL_W<10> {
        T13RSEL_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Timer Control Register 2\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [tctr2](index.html) module"]
pub struct TCTR2_SPEC;
impl crate::RegisterSpec for TCTR2_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [tctr2::R](R) reader structure"]
impl crate::Readable for TCTR2_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [tctr2::W](W) writer structure"]
impl crate::Writable for TCTR2_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets TCTR2 to value 0"]
impl crate::Resettable for TCTR2_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
