// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `MEMCON` reader"]
pub struct R(crate::R<MEMCON_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<MEMCON_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<MEMCON_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<MEMCON_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `MEMCON` writer"]
pub struct W(crate::W<MEMCON_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<MEMCON_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<MEMCON_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<MEMCON_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `ROM` reader - Read Only Memory - ROM"]
pub type ROM_R = crate::BitReader<bool>;
#[doc = "Field `ROM` writer - Read Only Memory - ROM"]
pub type ROM_W<'a, const O: u8> = crate::BitWriter<'a, u32, MEMCON_SPEC, bool, O>;
#[doc = "Field `INTERR` reader - Internal ECC Error - INTERR"]
pub type INTERR_R = crate::BitReader<bool>;
#[doc = "Field `INTERR` writer - Internal ECC Error - INTERR"]
pub type INTERR_W<'a, const O: u8> = crate::BitWriter<'a, u32, MEMCON_SPEC, bool, O>;
#[doc = "Field `RMWERR` reader - Internal Read Modify Write Error - RMWERR"]
pub type RMWERR_R = crate::BitReader<bool>;
#[doc = "Field `RMWERR` writer - Internal Read Modify Write Error - RMWERR"]
pub type RMWERR_W<'a, const O: u8> = crate::BitWriter<'a, u32, MEMCON_SPEC, bool, O>;
#[doc = "Field `DATAERR` reader - SRI Data Phase ECC Error - DATAERR"]
pub type DATAERR_R = crate::BitReader<bool>;
#[doc = "Field `DATAERR` writer - SRI Data Phase ECC Error - DATAERR"]
pub type DATAERR_W<'a, const O: u8> = crate::BitWriter<'a, u32, MEMCON_SPEC, bool, O>;
#[doc = "Field `ADDERR` reader - SRI Address Phase ECC Error - ADDERR"]
pub type ADDERR_R = crate::BitReader<bool>;
#[doc = "Field `ADDERR` writer - SRI Address Phase ECC Error - ADDERR"]
pub type ADDERR_W<'a, const O: u8> = crate::BitWriter<'a, u32, MEMCON_SPEC, bool, O>;
#[doc = "Field `PMIC` writer - Protection Bit for Memory Integrity Control Bit - PMIC"]
pub type PMIC_W<'a, const O: u8> = crate::BitWriter<'a, u32, MEMCON_SPEC, bool, O>;
#[doc = "Field `ERRDIS` reader - ECC Error Disable - ERRDIS"]
pub type ERRDIS_R = crate::BitReader<bool>;
#[doc = "Field `ERRDIS` writer - ECC Error Disable - ERRDIS"]
pub type ERRDIS_W<'a, const O: u8> = crate::BitWriter<'a, u32, MEMCON_SPEC, bool, O>;
impl R {
    #[doc = "Bit 0 - Read Only Memory - ROM"]
    #[inline(always)]
    pub fn rom(&self) -> ROM_R {
        ROM_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 2 - Internal ECC Error - INTERR"]
    #[inline(always)]
    pub fn interr(&self) -> INTERR_R {
        INTERR_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 4 - Internal Read Modify Write Error - RMWERR"]
    #[inline(always)]
    pub fn rmwerr(&self) -> RMWERR_R {
        RMWERR_R::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 6 - SRI Data Phase ECC Error - DATAERR"]
    #[inline(always)]
    pub fn dataerr(&self) -> DATAERR_R {
        DATAERR_R::new(((self.bits >> 6) & 1) != 0)
    }
    #[doc = "Bit 7 - SRI Address Phase ECC Error - ADDERR"]
    #[inline(always)]
    pub fn adderr(&self) -> ADDERR_R {
        ADDERR_R::new(((self.bits >> 7) & 1) != 0)
    }
    #[doc = "Bit 9 - ECC Error Disable - ERRDIS"]
    #[inline(always)]
    pub fn errdis(&self) -> ERRDIS_R {
        ERRDIS_R::new(((self.bits >> 9) & 1) != 0)
    }
}
impl W {
    #[doc = "Bit 0 - Read Only Memory - ROM"]
    #[inline(always)]
    #[must_use]
    pub fn rom(&mut self) -> ROM_W<0> {
        ROM_W::new(self)
    }
    #[doc = "Bit 2 - Internal ECC Error - INTERR"]
    #[inline(always)]
    #[must_use]
    pub fn interr(&mut self) -> INTERR_W<2> {
        INTERR_W::new(self)
    }
    #[doc = "Bit 4 - Internal Read Modify Write Error - RMWERR"]
    #[inline(always)]
    #[must_use]
    pub fn rmwerr(&mut self) -> RMWERR_W<4> {
        RMWERR_W::new(self)
    }
    #[doc = "Bit 6 - SRI Data Phase ECC Error - DATAERR"]
    #[inline(always)]
    #[must_use]
    pub fn dataerr(&mut self) -> DATAERR_W<6> {
        DATAERR_W::new(self)
    }
    #[doc = "Bit 7 - SRI Address Phase ECC Error - ADDERR"]
    #[inline(always)]
    #[must_use]
    pub fn adderr(&mut self) -> ADDERR_W<7> {
        ADDERR_W::new(self)
    }
    #[doc = "Bit 8 - Protection Bit for Memory Integrity Control Bit - PMIC"]
    #[inline(always)]
    #[must_use]
    pub fn pmic(&mut self) -> PMIC_W<8> {
        PMIC_W::new(self)
    }
    #[doc = "Bit 9 - ECC Error Disable - ERRDIS"]
    #[inline(always)]
    #[must_use]
    pub fn errdis(&mut self) -> ERRDIS_W<9> {
        ERRDIS_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "DAM Memory Control Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [memcon](index.html) module"]
pub struct MEMCON_SPEC;
impl crate::RegisterSpec for MEMCON_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [memcon::R](R) reader structure"]
impl crate::Readable for MEMCON_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [memcon::W](W) writer structure"]
impl crate::Writable for MEMCON_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets MEMCON to value 0"]
impl crate::Resettable for MEMCON_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
