// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `EVRRSTSTAT` reader"]
pub struct R(crate::R<EVRRSTSTAT_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<EVRRSTSTAT_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<EVRRSTSTAT_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<EVRRSTSTAT_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `RSTC` reader - VDD Supply Reset Value Status - RSTC"]
pub type RSTC_R = crate::FieldReader<u8, u8>;
#[doc = "Field `RST33` reader - VDDP3 Supply Reset Value Status - RST33"]
pub type RST33_R = crate::FieldReader<u8, u8>;
#[doc = "Field `RSTSWD` reader - VEXT Supply Reset Value Status - RSTSWD"]
pub type RSTSWD_R = crate::FieldReader<u8, u8>;
#[doc = "Field `RSTCOFF` reader - EVRC Reset Enable Status - RSTCOFF"]
pub type RSTCOFF_R = crate::BitReader<bool>;
#[doc = "Field `RST33OFF` reader - EVR33 Reset Enable Status - RST33OFF"]
pub type RST33OFF_R = crate::BitReader<bool>;
#[doc = "Field `RSTSWDOFF` reader - EVR SWD Reset Enable - RSTSWDOFF"]
pub type RSTSWDOFF_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bits 0:7 - VDD Supply Reset Value Status - RSTC"]
    #[inline(always)]
    pub fn rstc(&self) -> RSTC_R {
        RSTC_R::new((self.bits & 0xff) as u8)
    }
    #[doc = "Bits 8:15 - VDDP3 Supply Reset Value Status - RST33"]
    #[inline(always)]
    pub fn rst33(&self) -> RST33_R {
        RST33_R::new(((self.bits >> 8) & 0xff) as u8)
    }
    #[doc = "Bits 16:23 - VEXT Supply Reset Value Status - RSTSWD"]
    #[inline(always)]
    pub fn rstswd(&self) -> RSTSWD_R {
        RSTSWD_R::new(((self.bits >> 16) & 0xff) as u8)
    }
    #[doc = "Bit 24 - EVRC Reset Enable Status - RSTCOFF"]
    #[inline(always)]
    pub fn rstcoff(&self) -> RSTCOFF_R {
        RSTCOFF_R::new(((self.bits >> 24) & 1) != 0)
    }
    #[doc = "Bit 26 - EVR33 Reset Enable Status - RST33OFF"]
    #[inline(always)]
    pub fn rst33off(&self) -> RST33OFF_R {
        RST33OFF_R::new(((self.bits >> 26) & 1) != 0)
    }
    #[doc = "Bit 28 - EVR SWD Reset Enable - RSTSWDOFF"]
    #[inline(always)]
    pub fn rstswdoff(&self) -> RSTSWDOFF_R {
        RSTSWDOFF_R::new(((self.bits >> 28) & 1) != 0)
    }
}
#[doc = "EVR Reset Status Register\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [evrrststat](index.html) module"]
pub struct EVRRSTSTAT_SPEC;
impl crate::RegisterSpec for EVRRSTSTAT_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [evrrststat::R](R) reader structure"]
impl crate::Readable for EVRRSTSTAT_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets EVRRSTSTAT to value 0"]
impl crate::Resettable for EVRRSTSTAT_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
