// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `EVRSDCOEFF7` reader"]
pub struct R(crate::R<EVRSDCOEFF7_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<EVRSDCOEFF7_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<EVRSDCOEFF7_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<EVRSDCOEFF7_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `EVRSDCOEFF7` writer"]
pub struct W(crate::W<EVRSDCOEFF7_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<EVRSDCOEFF7_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<EVRSDCOEFF7_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<EVRSDCOEFF7_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `CT5REG3` reader - Commutation trimming(drv5v3_trim_i) - CT5REG3"]
pub type CT5REG3_R = crate::FieldReader<u8, u8>;
#[doc = "Field `CT5REG3` writer - Commutation trimming(drv5v3_trim_i) - CT5REG3"]
pub type CT5REG3_W<'a, const O: u8> = crate::FieldWriter<'a, u32, EVRSDCOEFF7_SPEC, u8, u8, 8, O>;
#[doc = "Field `CT5REG4` reader - Commutation trimming(drv5v4_trim_i) - CT5REG4"]
pub type CT5REG4_R = crate::FieldReader<u8, u8>;
#[doc = "Field `CT5REG4` writer - Commutation trimming(drv5v4_trim_i) - CT5REG4"]
pub type CT5REG4_W<'a, const O: u8> = crate::FieldWriter<'a, u32, EVRSDCOEFF7_SPEC, u8, u8, 8, O>;
#[doc = "Field `LCK` reader - Lock Status - LCK"]
pub type LCK_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bits 0:7 - Commutation trimming(drv5v3_trim_i) - CT5REG3"]
    #[inline(always)]
    pub fn ct5reg3(&self) -> CT5REG3_R {
        CT5REG3_R::new((self.bits & 0xff) as u8)
    }
    #[doc = "Bits 8:15 - Commutation trimming(drv5v4_trim_i) - CT5REG4"]
    #[inline(always)]
    pub fn ct5reg4(&self) -> CT5REG4_R {
        CT5REG4_R::new(((self.bits >> 8) & 0xff) as u8)
    }
    #[doc = "Bit 31 - Lock Status - LCK"]
    #[inline(always)]
    pub fn lck(&self) -> LCK_R {
        LCK_R::new(((self.bits >> 31) & 1) != 0)
    }
}
impl W {
    #[doc = "Bits 0:7 - Commutation trimming(drv5v3_trim_i) - CT5REG3"]
    #[inline(always)]
    #[must_use]
    pub fn ct5reg3(&mut self) -> CT5REG3_W<0> {
        CT5REG3_W::new(self)
    }
    #[doc = "Bits 8:15 - Commutation trimming(drv5v4_trim_i) - CT5REG4"]
    #[inline(always)]
    #[must_use]
    pub fn ct5reg4(&mut self) -> CT5REG4_W<8> {
        CT5REG4_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "EVRC SD Coefficient Register 7\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [evrsdcoeff7](index.html) module"]
pub struct EVRSDCOEFF7_SPEC;
impl crate::RegisterSpec for EVRSDCOEFF7_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [evrsdcoeff7::R](R) reader structure"]
impl crate::Readable for EVRSDCOEFF7_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [evrsdcoeff7::W](W) writer structure"]
impl crate::Writable for EVRSDCOEFF7_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets EVRSDCOEFF7 to value 0x8000_d8f7"]
impl crate::Resettable for EVRSDCOEFF7_SPEC {
    const RESET_VALUE: Self::Ux = 0x8000_d8f7;
}
