// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `EVRTRIMSTAT` reader"]
pub struct R(crate::R<EVRTRIMSTAT_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<EVRTRIMSTAT_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<EVRTRIMSTAT_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<EVRTRIMSTAT_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `EVR33VOUTSEL` reader - EVR33 Regulator Output Voltage Target Value - EVR33VOUTSEL"]
pub type EVR33VOUTSEL_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SDVOUTSEL` reader - EVRC Regulator Output Voltage Target Value - SDVOUTSEL"]
pub type SDVOUTSEL_R = crate::FieldReader<u8, u8>;
#[doc = "Field `EVR33VOUTTRIM` reader - EVR33 Regulator Output Voltage Trim Value - EVR33VOUTTRIM"]
pub type EVR33VOUTTRIM_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SDVOUTTRIM` reader - EVRC Regulator Output Voltage Trim Value(vtrim_trim_o) - SDVOUTTRIM"]
pub type SDVOUTTRIM_R = crate::FieldReader<u8, u8>;
impl R {
    #[doc = "Bits 0:7 - EVR33 Regulator Output Voltage Target Value - EVR33VOUTSEL"]
    #[inline(always)]
    pub fn evr33voutsel(&self) -> EVR33VOUTSEL_R {
        EVR33VOUTSEL_R::new((self.bits & 0xff) as u8)
    }
    #[doc = "Bits 8:15 - EVRC Regulator Output Voltage Target Value - SDVOUTSEL"]
    #[inline(always)]
    pub fn sdvoutsel(&self) -> SDVOUTSEL_R {
        SDVOUTSEL_R::new(((self.bits >> 8) & 0xff) as u8)
    }
    #[doc = "Bits 16:21 - EVR33 Regulator Output Voltage Trim Value - EVR33VOUTTRIM"]
    #[inline(always)]
    pub fn evr33vouttrim(&self) -> EVR33VOUTTRIM_R {
        EVR33VOUTTRIM_R::new(((self.bits >> 16) & 0x3f) as u8)
    }
    #[doc = "Bits 24:29 - EVRC Regulator Output Voltage Trim Value(vtrim_trim_o) - SDVOUTTRIM"]
    #[inline(always)]
    pub fn sdvouttrim(&self) -> SDVOUTTRIM_R {
        SDVOUTTRIM_R::new(((self.bits >> 24) & 0x3f) as u8)
    }
}
#[doc = "EVR Trim Status Register\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [evrtrimstat](index.html) module"]
pub struct EVRTRIMSTAT_SPEC;
impl crate::RegisterSpec for EVRTRIMSTAT_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [evrtrimstat::R](R) reader structure"]
impl crate::Readable for EVRTRIMSTAT_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets EVRTRIMSTAT to value 0x6c9e"]
impl crate::Resettable for EVRTRIMSTAT_SPEC {
    const RESET_VALUE: Self::Ux = 0x6c9e;
}
