// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `PMSWSTAT` reader"]
pub struct R(crate::R<PMSWSTAT_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<PMSWSTAT_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<PMSWSTAT_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<PMSWSTAT_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `HWCFGEVR` reader - EVR Hardware Configuration status - HWCFGEVR"]
pub type HWCFGEVR_R = crate::FieldReader<u8, u8>;
#[doc = "Field `HWCFG4` reader - Hardware Configuration Pin 4 status - HWCFG4"]
pub type HWCFG4_R = crate::BitReader<bool>;
#[doc = "Field `HWCFG5` reader - Hardware Configuration Pin 5 status - HWCFG5"]
pub type HWCFG5_R = crate::BitReader<bool>;
#[doc = "Field `TRIST` reader - Pad Tristate / Pull-up status - TRIST"]
pub type TRIST_R = crate::BitReader<bool>;
#[doc = "Field `TESTMODE` reader - TESTMODE Pin status - TESTMODE"]
pub type TESTMODE_R = crate::BitReader<bool>;
#[doc = "Field `ESR0TRIST` reader - ESR0 pin status during Standby - ESR0TRIST"]
pub type ESR0TRIST_R = crate::BitReader<bool>;
#[doc = "Field `PORSTDF` reader - PORST Digital Filter status - PORSTDF"]
pub type PORSTDF_R = crate::BitReader<bool>;
#[doc = "Field `SCR` reader - Standby Controller status - SCR"]
pub type SCR_R = crate::BitReader<bool>;
#[doc = "Field `SCRST` reader - Standby Controller Reset Indication flag - SCRST"]
pub type SCRST_R = crate::BitReader<bool>;
#[doc = "Field `SCRCLK` reader - Current Clock configuration for SCR before Standby Mode Entry - SCRCLK"]
pub type SCRCLK_R = crate::BitReader<bool>;
#[doc = "Field `PORSTREQ` reader - Standby Controller Reset on warm PORST - PORSTREQ"]
pub type PORSTREQ_R = crate::BitReader<bool>;
#[doc = "Field `WUTEN` reader - WUT Enable status - WUTEN"]
pub type WUTEN_R = crate::BitReader<bool>;
#[doc = "Field `WUTRUN` reader - WUT Run status - WUTRUN"]
pub type WUTRUN_R = crate::BitReader<bool>;
#[doc = "Field `WUTMODE` reader - WUT Mode status - WUTMODE"]
pub type WUTMODE_R = crate::BitReader<bool>;
#[doc = "Field `ESR0INT` reader - ESR0 Interrupt flag - ESR0INT"]
pub type ESR0INT_R = crate::BitReader<bool>;
#[doc = "Field `ESR1INT` reader - ESR1 Interrupt flag - ESR1INT"]
pub type ESR1INT_R = crate::BitReader<bool>;
#[doc = "Field `PINAINT` reader - Pin A Interrupt flag - PINAINT"]
pub type PINAINT_R = crate::BitReader<bool>;
#[doc = "Field `PINBINT` reader - Pin B Interrupt flag - PINBINT"]
pub type PINBINT_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bits 1:2 - EVR Hardware Configuration status - HWCFGEVR"]
    #[inline(always)]
    pub fn hwcfgevr(&self) -> HWCFGEVR_R {
        HWCFGEVR_R::new(((self.bits >> 1) & 3) as u8)
    }
    #[doc = "Bit 4 - Hardware Configuration Pin 4 status - HWCFG4"]
    #[inline(always)]
    pub fn hwcfg4(&self) -> HWCFG4_R {
        HWCFG4_R::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 5 - Hardware Configuration Pin 5 status - HWCFG5"]
    #[inline(always)]
    pub fn hwcfg5(&self) -> HWCFG5_R {
        HWCFG5_R::new(((self.bits >> 5) & 1) != 0)
    }
    #[doc = "Bit 6 - Pad Tristate / Pull-up status - TRIST"]
    #[inline(always)]
    pub fn trist(&self) -> TRIST_R {
        TRIST_R::new(((self.bits >> 6) & 1) != 0)
    }
    #[doc = "Bit 7 - TESTMODE Pin status - TESTMODE"]
    #[inline(always)]
    pub fn testmode(&self) -> TESTMODE_R {
        TESTMODE_R::new(((self.bits >> 7) & 1) != 0)
    }
    #[doc = "Bit 8 - ESR0 pin status during Standby - ESR0TRIST"]
    #[inline(always)]
    pub fn esr0trist(&self) -> ESR0TRIST_R {
        ESR0TRIST_R::new(((self.bits >> 8) & 1) != 0)
    }
    #[doc = "Bit 11 - PORST Digital Filter status - PORSTDF"]
    #[inline(always)]
    pub fn porstdf(&self) -> PORSTDF_R {
        PORSTDF_R::new(((self.bits >> 11) & 1) != 0)
    }
    #[doc = "Bit 16 - Standby Controller status - SCR"]
    #[inline(always)]
    pub fn scr(&self) -> SCR_R {
        SCR_R::new(((self.bits >> 16) & 1) != 0)
    }
    #[doc = "Bit 17 - Standby Controller Reset Indication flag - SCRST"]
    #[inline(always)]
    pub fn scrst(&self) -> SCRST_R {
        SCRST_R::new(((self.bits >> 17) & 1) != 0)
    }
    #[doc = "Bit 18 - Current Clock configuration for SCR before Standby Mode Entry - SCRCLK"]
    #[inline(always)]
    pub fn scrclk(&self) -> SCRCLK_R {
        SCRCLK_R::new(((self.bits >> 18) & 1) != 0)
    }
    #[doc = "Bit 19 - Standby Controller Reset on warm PORST - PORSTREQ"]
    #[inline(always)]
    pub fn porstreq(&self) -> PORSTREQ_R {
        PORSTREQ_R::new(((self.bits >> 19) & 1) != 0)
    }
    #[doc = "Bit 24 - WUT Enable status - WUTEN"]
    #[inline(always)]
    pub fn wuten(&self) -> WUTEN_R {
        WUTEN_R::new(((self.bits >> 24) & 1) != 0)
    }
    #[doc = "Bit 25 - WUT Run status - WUTRUN"]
    #[inline(always)]
    pub fn wutrun(&self) -> WUTRUN_R {
        WUTRUN_R::new(((self.bits >> 25) & 1) != 0)
    }
    #[doc = "Bit 26 - WUT Mode status - WUTMODE"]
    #[inline(always)]
    pub fn wutmode(&self) -> WUTMODE_R {
        WUTMODE_R::new(((self.bits >> 26) & 1) != 0)
    }
    #[doc = "Bit 28 - ESR0 Interrupt flag - ESR0INT"]
    #[inline(always)]
    pub fn esr0int(&self) -> ESR0INT_R {
        ESR0INT_R::new(((self.bits >> 28) & 1) != 0)
    }
    #[doc = "Bit 29 - ESR1 Interrupt flag - ESR1INT"]
    #[inline(always)]
    pub fn esr1int(&self) -> ESR1INT_R {
        ESR1INT_R::new(((self.bits >> 29) & 1) != 0)
    }
    #[doc = "Bit 30 - Pin A Interrupt flag - PINAINT"]
    #[inline(always)]
    pub fn pinaint(&self) -> PINAINT_R {
        PINAINT_R::new(((self.bits >> 30) & 1) != 0)
    }
    #[doc = "Bit 31 - Pin B Interrupt flag - PINBINT"]
    #[inline(always)]
    pub fn pinbint(&self) -> PINBINT_R {
        PINBINT_R::new(((self.bits >> 31) & 1) != 0)
    }
}
#[doc = "Standby and Wake-up Status Register\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [pmswstat](index.html) module"]
pub struct PMSWSTAT_SPEC;
impl crate::RegisterSpec for PMSWSTAT_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [pmswstat::R](R) reader structure"]
impl crate::Readable for PMSWSTAT_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets PMSWSTAT to value 0x000a_0000"]
impl crate::Resettable for PMSWSTAT_SPEC {
    const RESET_VALUE: Self::Ux = 0x000a_0000;
}
