// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `TLC` reader"]
pub struct R(crate::R<TLC_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<TLC_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<TLC_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<TLC_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `TLC` writer"]
pub struct W(crate::W<TLC_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<TLC_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<TLC_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<TLC_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `TLSP1` reader - TG Line Signal Processing - TLSP1"]
pub type TLSP1_R = crate::FieldReader<u8, u8>;
#[doc = "Field `TLSP1` writer - TG Line Signal Processing - TLSP1"]
pub type TLSP1_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TLC_SPEC, u8, u8, 4, O>;
#[doc = "Field `TLSP2` reader - TG Line Signal Processing - TLSP2"]
pub type TLSP2_R = crate::FieldReader<u8, u8>;
#[doc = "Field `TLSP2` writer - TG Line Signal Processing - TLSP2"]
pub type TLSP2_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TLC_SPEC, u8, u8, 4, O>;
#[doc = "Field `TLSP3` reader - TG Line Signal Processing - TLSP3"]
pub type TLSP3_R = crate::FieldReader<u8, u8>;
#[doc = "Field `TLSP3` writer - TG Line Signal Processing - TLSP3"]
pub type TLSP3_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TLC_SPEC, u8, u8, 4, O>;
#[doc = "Field `TLSP4` reader - TG Line Signal Processing - TLSP4"]
pub type TLSP4_R = crate::FieldReader<u8, u8>;
#[doc = "Field `TLSP4` writer - TG Line Signal Processing - TLSP4"]
pub type TLSP4_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TLC_SPEC, u8, u8, 4, O>;
#[doc = "Field `TLSP5` reader - TG Line Signal Processing - TLSP5"]
pub type TLSP5_R = crate::FieldReader<u8, u8>;
#[doc = "Field `TLSP5` writer - TG Line Signal Processing - TLSP5"]
pub type TLSP5_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TLC_SPEC, u8, u8, 4, O>;
#[doc = "Field `TLSP6` reader - TG Line Signal Processing - TLSP6"]
pub type TLSP6_R = crate::FieldReader<u8, u8>;
#[doc = "Field `TLSP6` writer - TG Line Signal Processing - TLSP6"]
pub type TLSP6_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TLC_SPEC, u8, u8, 4, O>;
#[doc = "Field `TLSP7` reader - TG Line Signal Processing - TLSP7"]
pub type TLSP7_R = crate::FieldReader<u8, u8>;
#[doc = "Field `TLSP7` writer - TG Line Signal Processing - TLSP7"]
pub type TLSP7_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TLC_SPEC, u8, u8, 4, O>;
impl R {
    #[doc = "Bits 4:7 - TG Line Signal Processing - TLSP1"]
    #[inline(always)]
    pub fn tlsp1(&self) -> TLSP1_R {
        TLSP1_R::new(((self.bits >> 4) & 0x0f) as u8)
    }
    #[doc = "Bits 8:11 - TG Line Signal Processing - TLSP2"]
    #[inline(always)]
    pub fn tlsp2(&self) -> TLSP2_R {
        TLSP2_R::new(((self.bits >> 8) & 0x0f) as u8)
    }
    #[doc = "Bits 12:15 - TG Line Signal Processing - TLSP3"]
    #[inline(always)]
    pub fn tlsp3(&self) -> TLSP3_R {
        TLSP3_R::new(((self.bits >> 12) & 0x0f) as u8)
    }
    #[doc = "Bits 16:19 - TG Line Signal Processing - TLSP4"]
    #[inline(always)]
    pub fn tlsp4(&self) -> TLSP4_R {
        TLSP4_R::new(((self.bits >> 16) & 0x0f) as u8)
    }
    #[doc = "Bits 20:23 - TG Line Signal Processing - TLSP5"]
    #[inline(always)]
    pub fn tlsp5(&self) -> TLSP5_R {
        TLSP5_R::new(((self.bits >> 20) & 0x0f) as u8)
    }
    #[doc = "Bits 24:27 - TG Line Signal Processing - TLSP6"]
    #[inline(always)]
    pub fn tlsp6(&self) -> TLSP6_R {
        TLSP6_R::new(((self.bits >> 24) & 0x0f) as u8)
    }
    #[doc = "Bits 28:31 - TG Line Signal Processing - TLSP7"]
    #[inline(always)]
    pub fn tlsp7(&self) -> TLSP7_R {
        TLSP7_R::new(((self.bits >> 28) & 0x0f) as u8)
    }
}
impl W {
    #[doc = "Bits 4:7 - TG Line Signal Processing - TLSP1"]
    #[inline(always)]
    #[must_use]
    pub fn tlsp1(&mut self) -> TLSP1_W<4> {
        TLSP1_W::new(self)
    }
    #[doc = "Bits 8:11 - TG Line Signal Processing - TLSP2"]
    #[inline(always)]
    #[must_use]
    pub fn tlsp2(&mut self) -> TLSP2_W<8> {
        TLSP2_W::new(self)
    }
    #[doc = "Bits 12:15 - TG Line Signal Processing - TLSP3"]
    #[inline(always)]
    #[must_use]
    pub fn tlsp3(&mut self) -> TLSP3_W<12> {
        TLSP3_W::new(self)
    }
    #[doc = "Bits 16:19 - TG Line Signal Processing - TLSP4"]
    #[inline(always)]
    #[must_use]
    pub fn tlsp4(&mut self) -> TLSP4_W<16> {
        TLSP4_W::new(self)
    }
    #[doc = "Bits 20:23 - TG Line Signal Processing - TLSP5"]
    #[inline(always)]
    #[must_use]
    pub fn tlsp5(&mut self) -> TLSP5_W<20> {
        TLSP5_W::new(self)
    }
    #[doc = "Bits 24:27 - TG Line Signal Processing - TLSP6"]
    #[inline(always)]
    #[must_use]
    pub fn tlsp6(&mut self) -> TLSP6_W<24> {
        TLSP6_W::new(self)
    }
    #[doc = "Bits 28:31 - TG Line Signal Processing - TLSP7"]
    #[inline(always)]
    #[must_use]
    pub fn tlsp7(&mut self) -> TLSP7_W<28> {
        TLSP7_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "TG Line Control\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [tlc](index.html) module"]
pub struct TLC_SPEC;
impl crate::RegisterSpec for TLC_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [tlc::R](R) reader structure"]
impl crate::Readable for TLC_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [tlc::W](W) writer structure"]
impl crate::Writable for TLC_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets TLC to value 0"]
impl crate::Resettable for TLC_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
