// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `TLCHE` reader"]
pub struct R(crate::R<TLCHE_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<TLCHE_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<TLCHE_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<TLCHE_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `TLCHE` writer"]
pub struct W(crate::W<TLCHE_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<TLCHE_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<TLCHE_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<TLCHE_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `TL1` reader - Capture and Hold Enable for Trigger Line 1 - TL1"]
pub type TL1_R = crate::BitReader<bool>;
#[doc = "Field `TL1` writer - Capture and Hold Enable for Trigger Line 1 - TL1"]
pub type TL1_W<'a, const O: u8> = crate::BitWriter<'a, u32, TLCHE_SPEC, bool, O>;
#[doc = "Field `TL2` reader - Capture and Hold Enable for Trigger Line 2 - TL2"]
pub type TL2_R = crate::BitReader<bool>;
#[doc = "Field `TL2` writer - Capture and Hold Enable for Trigger Line 2 - TL2"]
pub type TL2_W<'a, const O: u8> = crate::BitWriter<'a, u32, TLCHE_SPEC, bool, O>;
#[doc = "Field `TL3` reader - Capture and Hold Enable for Trigger Line 3 - TL3"]
pub type TL3_R = crate::BitReader<bool>;
#[doc = "Field `TL3` writer - Capture and Hold Enable for Trigger Line 3 - TL3"]
pub type TL3_W<'a, const O: u8> = crate::BitWriter<'a, u32, TLCHE_SPEC, bool, O>;
impl R {
    #[doc = "Bit 1 - Capture and Hold Enable for Trigger Line 1 - TL1"]
    #[inline(always)]
    pub fn tl1(&self) -> TL1_R {
        TL1_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - Capture and Hold Enable for Trigger Line 2 - TL2"]
    #[inline(always)]
    pub fn tl2(&self) -> TL2_R {
        TL2_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - Capture and Hold Enable for Trigger Line 3 - TL3"]
    #[inline(always)]
    pub fn tl3(&self) -> TL3_R {
        TL3_R::new(((self.bits >> 3) & 1) != 0)
    }
}
impl W {
    #[doc = "Bit 1 - Capture and Hold Enable for Trigger Line 1 - TL1"]
    #[inline(always)]
    #[must_use]
    pub fn tl1(&mut self) -> TL1_W<1> {
        TL1_W::new(self)
    }
    #[doc = "Bit 2 - Capture and Hold Enable for Trigger Line 2 - TL2"]
    #[inline(always)]
    #[must_use]
    pub fn tl2(&mut self) -> TL2_W<2> {
        TL2_W::new(self)
    }
    #[doc = "Bit 3 - Capture and Hold Enable for Trigger Line 3 - TL3"]
    #[inline(always)]
    #[must_use]
    pub fn tl3(&mut self) -> TL3_W<3> {
        TL3_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "TG Line Capture and Hold Enable\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [tlche](index.html) module"]
pub struct TLCHE_SPEC;
impl crate::RegisterSpec for TLCHE_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [tlche::R](R) reader structure"]
impl crate::Readable for TLCHE_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [tlche::W](W) writer structure"]
impl crate::Writable for TLCHE_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets TLCHE to value 0"]
impl crate::Resettable for TLCHE_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
