// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `TRC3` reader"]
pub struct R(crate::R<TRC3_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<TRC3_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<TRC3_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<TRC3_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `TRC3` writer"]
pub struct W(crate::W<TRC3_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<TRC3_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<TRC3_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<TRC3_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `HALT` reader - HALT to Trigger Line Routing - HALT"]
pub type HALT_R = crate::FieldReader<u8, u8>;
#[doc = "Field `HALT` writer - HALT to Trigger Line Routing - HALT"]
pub type HALT_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TRC3_SPEC, u8, u8, 4, O>;
#[doc = "Field `BRKOUT` reader - BRKOUT to Trigger Line Routing - BRKOUT"]
pub type BRKOUT_R = crate::FieldReader<u8, u8>;
#[doc = "Field `BRKOUT` writer - BRKOUT to Trigger Line Routing - BRKOUT"]
pub type BRKOUT_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TRC3_SPEC, u8, u8, 4, O>;
#[doc = "Field `BT1` reader - BRKOUT to Trigger Line 1 Routing - BT1"]
pub type BT1_R = crate::BitReader<bool>;
#[doc = "Field `BT1` writer - BRKOUT to Trigger Line 1 Routing - BT1"]
pub type BT1_W<'a, const O: u8> = crate::BitWriter<'a, u32, TRC3_SPEC, bool, O>;
#[doc = "Field `BRKIN` reader - Trigger Line to BRKIN Routing - BRKIN"]
pub type BRKIN_R = crate::FieldReader<u8, u8>;
#[doc = "Field `BRKIN` writer - Trigger Line to BRKIN Routing - BRKIN"]
pub type BRKIN_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TRC3_SPEC, u8, u8, 4, O>;
#[doc = "Field `SUSIN` reader - Trigger Line to SUSIN Routing - SUSIN"]
pub type SUSIN_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SUSIN` writer - Trigger Line to SUSIN Routing - SUSIN"]
pub type SUSIN_W<'a, const O: u8> = crate::FieldWriter<'a, u32, TRC3_SPEC, u8, u8, 4, O>;
impl R {
    #[doc = "Bits 0:3 - HALT to Trigger Line Routing - HALT"]
    #[inline(always)]
    pub fn halt(&self) -> HALT_R {
        HALT_R::new((self.bits & 0x0f) as u8)
    }
    #[doc = "Bits 4:7 - BRKOUT to Trigger Line Routing - BRKOUT"]
    #[inline(always)]
    pub fn brkout(&self) -> BRKOUT_R {
        BRKOUT_R::new(((self.bits >> 4) & 0x0f) as u8)
    }
    #[doc = "Bit 8 - BRKOUT to Trigger Line 1 Routing - BT1"]
    #[inline(always)]
    pub fn bt1(&self) -> BT1_R {
        BT1_R::new(((self.bits >> 8) & 1) != 0)
    }
    #[doc = "Bits 20:23 - Trigger Line to BRKIN Routing - BRKIN"]
    #[inline(always)]
    pub fn brkin(&self) -> BRKIN_R {
        BRKIN_R::new(((self.bits >> 20) & 0x0f) as u8)
    }
    #[doc = "Bits 24:27 - Trigger Line to SUSIN Routing - SUSIN"]
    #[inline(always)]
    pub fn susin(&self) -> SUSIN_R {
        SUSIN_R::new(((self.bits >> 24) & 0x0f) as u8)
    }
}
impl W {
    #[doc = "Bits 0:3 - HALT to Trigger Line Routing - HALT"]
    #[inline(always)]
    #[must_use]
    pub fn halt(&mut self) -> HALT_W<0> {
        HALT_W::new(self)
    }
    #[doc = "Bits 4:7 - BRKOUT to Trigger Line Routing - BRKOUT"]
    #[inline(always)]
    #[must_use]
    pub fn brkout(&mut self) -> BRKOUT_W<4> {
        BRKOUT_W::new(self)
    }
    #[doc = "Bit 8 - BRKOUT to Trigger Line 1 Routing - BT1"]
    #[inline(always)]
    #[must_use]
    pub fn bt1(&mut self) -> BT1_W<8> {
        BT1_W::new(self)
    }
    #[doc = "Bits 20:23 - Trigger Line to BRKIN Routing - BRKIN"]
    #[inline(always)]
    #[must_use]
    pub fn brkin(&mut self) -> BRKIN_W<20> {
        BRKIN_W::new(self)
    }
    #[doc = "Bits 24:27 - Trigger Line to SUSIN Routing - SUSIN"]
    #[inline(always)]
    #[must_use]
    pub fn susin(&mut self) -> SUSIN_W<24> {
        SUSIN_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "TG Routing for CPU3\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [trc3](index.html) module"]
pub struct TRC3_SPEC;
impl crate::RegisterSpec for TRC3_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [trc3::R](R) reader structure"]
impl crate::Readable for TRC3_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [trc3::W](W) writer structure"]
impl crate::Writable for TRC3_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets TRC3 to value 0"]
impl crate::Resettable for TRC3_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
