// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `DSDSL` reader"]
pub struct R(crate::R<DSDSL_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<DSDSL_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<DSDSL_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<DSDSL_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `DSDSL` writer"]
pub struct W(crate::W<DSDSL_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<DSDSL_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<DSDSL_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<DSDSL_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `SL0` reader - Select Source for SRL - SL0"]
pub type SL0_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL0` writer - Select Source for SRL - SL0"]
pub type SL0_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
#[doc = "Field `SL1` reader - Select Source for SRL - SL1"]
pub type SL1_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL1` writer - Select Source for SRL - SL1"]
pub type SL1_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
#[doc = "Field `SL2` reader - Select Source for SRL - SL2"]
pub type SL2_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL2` writer - Select Source for SRL - SL2"]
pub type SL2_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
#[doc = "Field `SL3` reader - Select Source for SRL - SL3"]
pub type SL3_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL3` writer - Select Source for SRL - SL3"]
pub type SL3_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
#[doc = "Field `SL4` reader - Select Source for SRL - SL4"]
pub type SL4_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL4` writer - Select Source for SRL - SL4"]
pub type SL4_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
#[doc = "Field `SL5` reader - Select Source for SRL - SL5"]
pub type SL5_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL5` writer - Select Source for SRL - SL5"]
pub type SL5_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
#[doc = "Field `SL6` reader - Select Source for SRL - SL6"]
pub type SL6_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL6` writer - Select Source for SRL - SL6"]
pub type SL6_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
#[doc = "Field `SL7` reader - Select Source for SRL - SL7"]
pub type SL7_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL7` writer - Select Source for SRL - SL7"]
pub type SL7_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
#[doc = "Field `SL8` reader - Select Source for SRL - SL8"]
pub type SL8_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL8` writer - Select Source for SRL - SL8"]
pub type SL8_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
#[doc = "Field `SL9` reader - Select Source for SRL - SL9"]
pub type SL9_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL9` writer - Select Source for SRL - SL9"]
pub type SL9_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
#[doc = "Field `SL10` reader - Select Source for SRL - SL10"]
pub type SL10_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL10` writer - Select Source for SRL - SL10"]
pub type SL10_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
#[doc = "Field `SL11` reader - Select Source for SRL - SL11"]
pub type SL11_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL11` writer - Select Source for SRL - SL11"]
pub type SL11_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
#[doc = "Field `SL12` reader - Select Source for SRL - SL12"]
pub type SL12_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL12` writer - Select Source for SRL - SL12"]
pub type SL12_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
#[doc = "Field `SL13` reader - Select Source for SRL - SL13"]
pub type SL13_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL13` writer - Select Source for SRL - SL13"]
pub type SL13_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
#[doc = "Field `SL14` reader - Select Source for SRL - SL14"]
pub type SL14_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL14` writer - Select Source for SRL - SL14"]
pub type SL14_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
#[doc = "Field `SL15` reader - Select Source for SRL - SL15"]
pub type SL15_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SL15` writer - Select Source for SRL - SL15"]
pub type SL15_W<'a, const O: u8> = crate::FieldWriter<'a, u32, DSDSL_SPEC, u8, u8, 2, O>;
impl R {
    #[doc = "Bits 0:1 - Select Source for SRL - SL0"]
    #[inline(always)]
    pub fn sl0(&self) -> SL0_R {
        SL0_R::new((self.bits & 3) as u8)
    }
    #[doc = "Bits 2:3 - Select Source for SRL - SL1"]
    #[inline(always)]
    pub fn sl1(&self) -> SL1_R {
        SL1_R::new(((self.bits >> 2) & 3) as u8)
    }
    #[doc = "Bits 4:5 - Select Source for SRL - SL2"]
    #[inline(always)]
    pub fn sl2(&self) -> SL2_R {
        SL2_R::new(((self.bits >> 4) & 3) as u8)
    }
    #[doc = "Bits 6:7 - Select Source for SRL - SL3"]
    #[inline(always)]
    pub fn sl3(&self) -> SL3_R {
        SL3_R::new(((self.bits >> 6) & 3) as u8)
    }
    #[doc = "Bits 8:9 - Select Source for SRL - SL4"]
    #[inline(always)]
    pub fn sl4(&self) -> SL4_R {
        SL4_R::new(((self.bits >> 8) & 3) as u8)
    }
    #[doc = "Bits 10:11 - Select Source for SRL - SL5"]
    #[inline(always)]
    pub fn sl5(&self) -> SL5_R {
        SL5_R::new(((self.bits >> 10) & 3) as u8)
    }
    #[doc = "Bits 12:13 - Select Source for SRL - SL6"]
    #[inline(always)]
    pub fn sl6(&self) -> SL6_R {
        SL6_R::new(((self.bits >> 12) & 3) as u8)
    }
    #[doc = "Bits 14:15 - Select Source for SRL - SL7"]
    #[inline(always)]
    pub fn sl7(&self) -> SL7_R {
        SL7_R::new(((self.bits >> 14) & 3) as u8)
    }
    #[doc = "Bits 16:17 - Select Source for SRL - SL8"]
    #[inline(always)]
    pub fn sl8(&self) -> SL8_R {
        SL8_R::new(((self.bits >> 16) & 3) as u8)
    }
    #[doc = "Bits 18:19 - Select Source for SRL - SL9"]
    #[inline(always)]
    pub fn sl9(&self) -> SL9_R {
        SL9_R::new(((self.bits >> 18) & 3) as u8)
    }
    #[doc = "Bits 20:21 - Select Source for SRL - SL10"]
    #[inline(always)]
    pub fn sl10(&self) -> SL10_R {
        SL10_R::new(((self.bits >> 20) & 3) as u8)
    }
    #[doc = "Bits 22:23 - Select Source for SRL - SL11"]
    #[inline(always)]
    pub fn sl11(&self) -> SL11_R {
        SL11_R::new(((self.bits >> 22) & 3) as u8)
    }
    #[doc = "Bits 24:25 - Select Source for SRL - SL12"]
    #[inline(always)]
    pub fn sl12(&self) -> SL12_R {
        SL12_R::new(((self.bits >> 24) & 3) as u8)
    }
    #[doc = "Bits 26:27 - Select Source for SRL - SL13"]
    #[inline(always)]
    pub fn sl13(&self) -> SL13_R {
        SL13_R::new(((self.bits >> 26) & 3) as u8)
    }
    #[doc = "Bits 28:29 - Select Source for SRL - SL14"]
    #[inline(always)]
    pub fn sl14(&self) -> SL14_R {
        SL14_R::new(((self.bits >> 28) & 3) as u8)
    }
    #[doc = "Bits 30:31 - Select Source for SRL - SL15"]
    #[inline(always)]
    pub fn sl15(&self) -> SL15_R {
        SL15_R::new(((self.bits >> 30) & 3) as u8)
    }
}
impl W {
    #[doc = "Bits 0:1 - Select Source for SRL - SL0"]
    #[inline(always)]
    #[must_use]
    pub fn sl0(&mut self) -> SL0_W<0> {
        SL0_W::new(self)
    }
    #[doc = "Bits 2:3 - Select Source for SRL - SL1"]
    #[inline(always)]
    #[must_use]
    pub fn sl1(&mut self) -> SL1_W<2> {
        SL1_W::new(self)
    }
    #[doc = "Bits 4:5 - Select Source for SRL - SL2"]
    #[inline(always)]
    #[must_use]
    pub fn sl2(&mut self) -> SL2_W<4> {
        SL2_W::new(self)
    }
    #[doc = "Bits 6:7 - Select Source for SRL - SL3"]
    #[inline(always)]
    #[must_use]
    pub fn sl3(&mut self) -> SL3_W<6> {
        SL3_W::new(self)
    }
    #[doc = "Bits 8:9 - Select Source for SRL - SL4"]
    #[inline(always)]
    #[must_use]
    pub fn sl4(&mut self) -> SL4_W<8> {
        SL4_W::new(self)
    }
    #[doc = "Bits 10:11 - Select Source for SRL - SL5"]
    #[inline(always)]
    #[must_use]
    pub fn sl5(&mut self) -> SL5_W<10> {
        SL5_W::new(self)
    }
    #[doc = "Bits 12:13 - Select Source for SRL - SL6"]
    #[inline(always)]
    #[must_use]
    pub fn sl6(&mut self) -> SL6_W<12> {
        SL6_W::new(self)
    }
    #[doc = "Bits 14:15 - Select Source for SRL - SL7"]
    #[inline(always)]
    #[must_use]
    pub fn sl7(&mut self) -> SL7_W<14> {
        SL7_W::new(self)
    }
    #[doc = "Bits 16:17 - Select Source for SRL - SL8"]
    #[inline(always)]
    #[must_use]
    pub fn sl8(&mut self) -> SL8_W<16> {
        SL8_W::new(self)
    }
    #[doc = "Bits 18:19 - Select Source for SRL - SL9"]
    #[inline(always)]
    #[must_use]
    pub fn sl9(&mut self) -> SL9_W<18> {
        SL9_W::new(self)
    }
    #[doc = "Bits 20:21 - Select Source for SRL - SL10"]
    #[inline(always)]
    #[must_use]
    pub fn sl10(&mut self) -> SL10_W<20> {
        SL10_W::new(self)
    }
    #[doc = "Bits 22:23 - Select Source for SRL - SL11"]
    #[inline(always)]
    #[must_use]
    pub fn sl11(&mut self) -> SL11_W<22> {
        SL11_W::new(self)
    }
    #[doc = "Bits 24:25 - Select Source for SRL - SL12"]
    #[inline(always)]
    #[must_use]
    pub fn sl12(&mut self) -> SL12_W<24> {
        SL12_W::new(self)
    }
    #[doc = "Bits 26:27 - Select Source for SRL - SL13"]
    #[inline(always)]
    #[must_use]
    pub fn sl13(&mut self) -> SL13_W<26> {
        SL13_W::new(self)
    }
    #[doc = "Bits 28:29 - Select Source for SRL - SL14"]
    #[inline(always)]
    #[must_use]
    pub fn sl14(&mut self) -> SL14_W<28> {
        SL14_W::new(self)
    }
    #[doc = "Bits 30:31 - Select Source for SRL - SL15"]
    #[inline(always)]
    #[must_use]
    pub fn sl15(&mut self) -> SL15_W<30> {
        SL15_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Downstream Select Data Source Low Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [dsdsl](index.html) module"]
pub struct DSDSL_SPEC;
impl crate::RegisterSpec for DSDSL_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [dsdsl::R](R) reader structure"]
impl crate::Readable for DSDSL_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [dsdsl::W](W) writer structure"]
impl crate::Writable for DSDSL_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets DSDSL to value 0"]
impl crate::Resettable for DSDSL_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
