// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `ICR` reader"]
pub struct R(crate::R<ICR_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<ICR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<ICR_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<ICR_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `ICR` writer"]
pub struct W(crate::W<ICR_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<ICR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<ICR_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<ICR_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `EDIP` reader - Data Frame Interrupt Node Pointer - EDIP"]
pub type EDIP_R = crate::FieldReader<u8, u8>;
#[doc = "Field `EDIP` writer - Data Frame Interrupt Node Pointer - EDIP"]
pub type EDIP_W<'a, const O: u8> = crate::FieldWriter<'a, u32, ICR_SPEC, u8, u8, 2, O>;
#[doc = "Field `EDIE` reader - Data Frame Interrupt Enable - EDIE"]
pub type EDIE_R = crate::FieldReader<u8, u8>;
#[doc = "Field `EDIE` writer - Data Frame Interrupt Enable - EDIE"]
pub type EDIE_W<'a, const O: u8> = crate::FieldWriter<'a, u32, ICR_SPEC, u8, u8, 2, O>;
#[doc = "Field `ECIP` reader - Command Frame Interrupt Node Pointer - ECIP"]
pub type ECIP_R = crate::FieldReader<u8, u8>;
#[doc = "Field `ECIP` writer - Command Frame Interrupt Node Pointer - ECIP"]
pub type ECIP_W<'a, const O: u8> = crate::FieldWriter<'a, u32, ICR_SPEC, u8, u8, 2, O>;
#[doc = "Field `ECIE` reader - Command Frame Interrupt Enable - ECIE"]
pub type ECIE_R = crate::BitReader<bool>;
#[doc = "Field `ECIE` writer - Command Frame Interrupt Enable - ECIE"]
pub type ECIE_W<'a, const O: u8> = crate::BitWriter<'a, u32, ICR_SPEC, bool, O>;
#[doc = "Field `TFIP` reader - Time Frame Interrupt Pointer - TFIP"]
pub type TFIP_R = crate::FieldReader<u8, u8>;
#[doc = "Field `TFIP` writer - Time Frame Interrupt Pointer - TFIP"]
pub type TFIP_W<'a, const O: u8> = crate::FieldWriter<'a, u32, ICR_SPEC, u8, u8, 2, O>;
#[doc = "Field `TFIE` reader - Time Frame Interrupt Enable - TFIE"]
pub type TFIE_R = crate::BitReader<bool>;
#[doc = "Field `TFIE` writer - Time Frame Interrupt Enable - TFIE"]
pub type TFIE_W<'a, const O: u8> = crate::BitWriter<'a, u32, ICR_SPEC, bool, O>;
#[doc = "Field `RDIP` reader - Receive Data Interrupt Pointer - RDIP"]
pub type RDIP_R = crate::FieldReader<u8, u8>;
#[doc = "Field `RDIP` writer - Receive Data Interrupt Pointer - RDIP"]
pub type RDIP_W<'a, const O: u8> = crate::FieldWriter<'a, u32, ICR_SPEC, u8, u8, 2, O>;
#[doc = "Field `RDIE` reader - Receive Data Interrupt Enable - RDIE"]
pub type RDIE_R = crate::FieldReader<u8, u8>;
#[doc = "Field `RDIE` writer - Receive Data Interrupt Enable - RDIE"]
pub type RDIE_W<'a, const O: u8> = crate::FieldWriter<'a, u32, ICR_SPEC, u8, u8, 2, O>;
impl R {
    #[doc = "Bits 0:1 - Data Frame Interrupt Node Pointer - EDIP"]
    #[inline(always)]
    pub fn edip(&self) -> EDIP_R {
        EDIP_R::new((self.bits & 3) as u8)
    }
    #[doc = "Bits 2:3 - Data Frame Interrupt Enable - EDIE"]
    #[inline(always)]
    pub fn edie(&self) -> EDIE_R {
        EDIE_R::new(((self.bits >> 2) & 3) as u8)
    }
    #[doc = "Bits 4:5 - Command Frame Interrupt Node Pointer - ECIP"]
    #[inline(always)]
    pub fn ecip(&self) -> ECIP_R {
        ECIP_R::new(((self.bits >> 4) & 3) as u8)
    }
    #[doc = "Bit 7 - Command Frame Interrupt Enable - ECIE"]
    #[inline(always)]
    pub fn ecie(&self) -> ECIE_R {
        ECIE_R::new(((self.bits >> 7) & 1) != 0)
    }
    #[doc = "Bits 8:9 - Time Frame Interrupt Pointer - TFIP"]
    #[inline(always)]
    pub fn tfip(&self) -> TFIP_R {
        TFIP_R::new(((self.bits >> 8) & 3) as u8)
    }
    #[doc = "Bit 11 - Time Frame Interrupt Enable - TFIE"]
    #[inline(always)]
    pub fn tfie(&self) -> TFIE_R {
        TFIE_R::new(((self.bits >> 11) & 1) != 0)
    }
    #[doc = "Bits 12:13 - Receive Data Interrupt Pointer - RDIP"]
    #[inline(always)]
    pub fn rdip(&self) -> RDIP_R {
        RDIP_R::new(((self.bits >> 12) & 3) as u8)
    }
    #[doc = "Bits 14:15 - Receive Data Interrupt Enable - RDIE"]
    #[inline(always)]
    pub fn rdie(&self) -> RDIE_R {
        RDIE_R::new(((self.bits >> 14) & 3) as u8)
    }
}
impl W {
    #[doc = "Bits 0:1 - Data Frame Interrupt Node Pointer - EDIP"]
    #[inline(always)]
    #[must_use]
    pub fn edip(&mut self) -> EDIP_W<0> {
        EDIP_W::new(self)
    }
    #[doc = "Bits 2:3 - Data Frame Interrupt Enable - EDIE"]
    #[inline(always)]
    #[must_use]
    pub fn edie(&mut self) -> EDIE_W<2> {
        EDIE_W::new(self)
    }
    #[doc = "Bits 4:5 - Command Frame Interrupt Node Pointer - ECIP"]
    #[inline(always)]
    #[must_use]
    pub fn ecip(&mut self) -> ECIP_W<4> {
        ECIP_W::new(self)
    }
    #[doc = "Bit 7 - Command Frame Interrupt Enable - ECIE"]
    #[inline(always)]
    #[must_use]
    pub fn ecie(&mut self) -> ECIE_W<7> {
        ECIE_W::new(self)
    }
    #[doc = "Bits 8:9 - Time Frame Interrupt Pointer - TFIP"]
    #[inline(always)]
    #[must_use]
    pub fn tfip(&mut self) -> TFIP_W<8> {
        TFIP_W::new(self)
    }
    #[doc = "Bit 11 - Time Frame Interrupt Enable - TFIE"]
    #[inline(always)]
    #[must_use]
    pub fn tfie(&mut self) -> TFIE_W<11> {
        TFIE_W::new(self)
    }
    #[doc = "Bits 12:13 - Receive Data Interrupt Pointer - RDIP"]
    #[inline(always)]
    #[must_use]
    pub fn rdip(&mut self) -> RDIP_W<12> {
        RDIP_W::new(self)
    }
    #[doc = "Bits 14:15 - Receive Data Interrupt Enable - RDIE"]
    #[inline(always)]
    #[must_use]
    pub fn rdie(&mut self) -> RDIE_W<14> {
        RDIE_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Interrupt Control Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [icr](index.html) module"]
pub struct ICR_SPEC;
impl crate::RegisterSpec for ICR_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [icr::R](R) reader structure"]
impl crate::Readable for ICR_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [icr::W](W) writer structure"]
impl crate::Writable for ICR_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets ICR to value 0"]
impl crate::Resettable for ICR_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
