// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `HSMCOMM_1` reader"]
pub struct R(crate::R<HSMCOMM_1_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<HSMCOMM_1_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<HSMCOMM_1_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<HSMCOMM_1_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `HSMCOMM_1` writer"]
pub struct W(crate::W<HSMCOMM_1_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<HSMCOMM_1_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<HSMCOMM_1_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<HSMCOMM_1_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `HSMCOMM1` reader - HSM FSI Communication 1 - HSMCOMM1"]
pub type HSMCOMM1_R = crate::FieldReader<u8, u8>;
#[doc = "Field `HSMCOMM1` writer - HSM FSI Communication 1 - HSMCOMM1"]
pub type HSMCOMM1_W<'a, const O: u8> = crate::FieldWriter<'a, u8, HSMCOMM_1_SPEC, u8, u8, 8, O>;
impl R {
    #[doc = "Bits 0:7 - HSM FSI Communication 1 - HSMCOMM1"]
    #[inline(always)]
    pub fn hsmcomm1(&self) -> HSMCOMM1_R {
        HSMCOMM1_R::new(self.bits)
    }
}
impl W {
    #[doc = "Bits 0:7 - HSM FSI Communication 1 - HSMCOMM1"]
    #[inline(always)]
    #[must_use]
    pub fn hsmcomm1(&mut self) -> HSMCOMM1_W<0> {
        HSMCOMM1_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u8) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "HSM Communication Register 1\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [hsmcomm_1](index.html) module"]
pub struct HSMCOMM_1_SPEC;
impl crate::RegisterSpec for HSMCOMM_1_SPEC {
    type Ux = u8;
}
#[doc = "`read()` method returns [hsmcomm_1::R](R) reader structure"]
impl crate::Readable for HSMCOMM_1_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [hsmcomm_1::W](W) writer structure"]
impl crate::Writable for HSMCOMM_1_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets HSMCOMM_1 to value 0"]
impl crate::Resettable for HSMCOMM_1_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
