// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `PESTAT` reader"]
pub struct R(crate::R<PESTAT_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<PESTAT_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<PESTAT_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<PESTAT_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `PESTAT` writer"]
pub struct W(crate::W<PESTAT_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<PESTAT_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<PESTAT_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<PESTAT_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `PESCI0` reader - Protocol Error status of SCI0 - PESCI0"]
pub type PESCI0_R = crate::BitReader<bool>;
#[doc = "Field `PESCI0` writer - Protocol Error status of SCI0 - PESCI0"]
pub type PESCI0_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
#[doc = "Field `PESCI1` reader - Protocol Error status of SCI1 - PESCI1"]
pub type PESCI1_R = crate::BitReader<bool>;
#[doc = "Field `PESCI1` writer - Protocol Error status of SCI1 - PESCI1"]
pub type PESCI1_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
#[doc = "Field `PESCI2` reader - Protocol Error status of SCI2 - PESCI2"]
pub type PESCI2_R = crate::BitReader<bool>;
#[doc = "Field `PESCI2` writer - Protocol Error status of SCI2 - PESCI2"]
pub type PESCI2_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
#[doc = "Field `PESCI3` reader - Protocol Error status of SCI3 - PESCI3"]
pub type PESCI3_R = crate::BitReader<bool>;
#[doc = "Field `PESCI3` writer - Protocol Error status of SCI3 - PESCI3"]
pub type PESCI3_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
#[doc = "Field `PESCI4` reader - Protocol Error status of SCI4 - PESCI4"]
pub type PESCI4_R = crate::BitReader<bool>;
#[doc = "Field `PESCI4` writer - Protocol Error status of SCI4 - PESCI4"]
pub type PESCI4_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
#[doc = "Field `PESCI5` reader - Protocol Error status of SCI5 - PESCI5"]
pub type PESCI5_R = crate::BitReader<bool>;
#[doc = "Field `PESCI5` writer - Protocol Error status of SCI5 - PESCI5"]
pub type PESCI5_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
#[doc = "Field `PESCI6` reader - Protocol Error status of SCI6 - PESCI6"]
pub type PESCI6_R = crate::BitReader<bool>;
#[doc = "Field `PESCI6` writer - Protocol Error status of SCI6 - PESCI6"]
pub type PESCI6_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
#[doc = "Field `PESCI7` reader - Protocol Error status of SCI7 - PESCI7"]
pub type PESCI7_R = crate::BitReader<bool>;
#[doc = "Field `PESCI7` writer - Protocol Error status of SCI7 - PESCI7"]
pub type PESCI7_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
#[doc = "Field `PESCI8` reader - Protocol Error status of SCI8 - PESCI8"]
pub type PESCI8_R = crate::BitReader<bool>;
#[doc = "Field `PESCI8` writer - Protocol Error status of SCI8 - PESCI8"]
pub type PESCI8_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
#[doc = "Field `PESCI9` reader - Protocol Error status of SCI9 - PESCI9"]
pub type PESCI9_R = crate::BitReader<bool>;
#[doc = "Field `PESCI9` writer - Protocol Error status of SCI9 - PESCI9"]
pub type PESCI9_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
#[doc = "Field `PESCI10` reader - Protocol Error status of SCI10 - PESCI10"]
pub type PESCI10_R = crate::BitReader<bool>;
#[doc = "Field `PESCI10` writer - Protocol Error status of SCI10 - PESCI10"]
pub type PESCI10_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
#[doc = "Field `PESCI11` reader - Protocol Error status of SCI11 - PESCI11"]
pub type PESCI11_R = crate::BitReader<bool>;
#[doc = "Field `PESCI11` writer - Protocol Error status of SCI11 - PESCI11"]
pub type PESCI11_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
#[doc = "Field `PESCI12` reader - Protocol Error status of SCI12 - PESCI12"]
pub type PESCI12_R = crate::BitReader<bool>;
#[doc = "Field `PESCI12` writer - Protocol Error status of SCI12 - PESCI12"]
pub type PESCI12_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
#[doc = "Field `PESCI13` reader - Protocol Error status of SCI13 - PESCI13"]
pub type PESCI13_R = crate::BitReader<bool>;
#[doc = "Field `PESCI13` writer - Protocol Error status of SCI13 - PESCI13"]
pub type PESCI13_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
#[doc = "Field `PESCI14` reader - Protocol Error status of SCI14 - PESCI14"]
pub type PESCI14_R = crate::BitReader<bool>;
#[doc = "Field `PESCI14` writer - Protocol Error status of SCI14 - PESCI14"]
pub type PESCI14_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
#[doc = "Field `PESCI15` reader - Protocol Error status of SCI15 - PESCI15"]
pub type PESCI15_R = crate::BitReader<bool>;
#[doc = "Field `PESCI15` writer - Protocol Error status of SCI15 - PESCI15"]
pub type PESCI15_W<'a, const O: u8> = crate::BitWriter<'a, u32, PESTAT_SPEC, bool, O>;
impl R {
    #[doc = "Bit 16 - Protocol Error status of SCI0 - PESCI0"]
    #[inline(always)]
    pub fn pesci0(&self) -> PESCI0_R {
        PESCI0_R::new(((self.bits >> 16) & 1) != 0)
    }
    #[doc = "Bit 17 - Protocol Error status of SCI1 - PESCI1"]
    #[inline(always)]
    pub fn pesci1(&self) -> PESCI1_R {
        PESCI1_R::new(((self.bits >> 17) & 1) != 0)
    }
    #[doc = "Bit 18 - Protocol Error status of SCI2 - PESCI2"]
    #[inline(always)]
    pub fn pesci2(&self) -> PESCI2_R {
        PESCI2_R::new(((self.bits >> 18) & 1) != 0)
    }
    #[doc = "Bit 19 - Protocol Error status of SCI3 - PESCI3"]
    #[inline(always)]
    pub fn pesci3(&self) -> PESCI3_R {
        PESCI3_R::new(((self.bits >> 19) & 1) != 0)
    }
    #[doc = "Bit 20 - Protocol Error status of SCI4 - PESCI4"]
    #[inline(always)]
    pub fn pesci4(&self) -> PESCI4_R {
        PESCI4_R::new(((self.bits >> 20) & 1) != 0)
    }
    #[doc = "Bit 21 - Protocol Error status of SCI5 - PESCI5"]
    #[inline(always)]
    pub fn pesci5(&self) -> PESCI5_R {
        PESCI5_R::new(((self.bits >> 21) & 1) != 0)
    }
    #[doc = "Bit 22 - Protocol Error status of SCI6 - PESCI6"]
    #[inline(always)]
    pub fn pesci6(&self) -> PESCI6_R {
        PESCI6_R::new(((self.bits >> 22) & 1) != 0)
    }
    #[doc = "Bit 23 - Protocol Error status of SCI7 - PESCI7"]
    #[inline(always)]
    pub fn pesci7(&self) -> PESCI7_R {
        PESCI7_R::new(((self.bits >> 23) & 1) != 0)
    }
    #[doc = "Bit 24 - Protocol Error status of SCI8 - PESCI8"]
    #[inline(always)]
    pub fn pesci8(&self) -> PESCI8_R {
        PESCI8_R::new(((self.bits >> 24) & 1) != 0)
    }
    #[doc = "Bit 25 - Protocol Error status of SCI9 - PESCI9"]
    #[inline(always)]
    pub fn pesci9(&self) -> PESCI9_R {
        PESCI9_R::new(((self.bits >> 25) & 1) != 0)
    }
    #[doc = "Bit 26 - Protocol Error status of SCI10 - PESCI10"]
    #[inline(always)]
    pub fn pesci10(&self) -> PESCI10_R {
        PESCI10_R::new(((self.bits >> 26) & 1) != 0)
    }
    #[doc = "Bit 27 - Protocol Error status of SCI11 - PESCI11"]
    #[inline(always)]
    pub fn pesci11(&self) -> PESCI11_R {
        PESCI11_R::new(((self.bits >> 27) & 1) != 0)
    }
    #[doc = "Bit 28 - Protocol Error status of SCI12 - PESCI12"]
    #[inline(always)]
    pub fn pesci12(&self) -> PESCI12_R {
        PESCI12_R::new(((self.bits >> 28) & 1) != 0)
    }
    #[doc = "Bit 29 - Protocol Error status of SCI13 - PESCI13"]
    #[inline(always)]
    pub fn pesci13(&self) -> PESCI13_R {
        PESCI13_R::new(((self.bits >> 29) & 1) != 0)
    }
    #[doc = "Bit 30 - Protocol Error status of SCI14 - PESCI14"]
    #[inline(always)]
    pub fn pesci14(&self) -> PESCI14_R {
        PESCI14_R::new(((self.bits >> 30) & 1) != 0)
    }
    #[doc = "Bit 31 - Protocol Error status of SCI15 - PESCI15"]
    #[inline(always)]
    pub fn pesci15(&self) -> PESCI15_R {
        PESCI15_R::new(((self.bits >> 31) & 1) != 0)
    }
}
impl W {
    #[doc = "Bit 16 - Protocol Error status of SCI0 - PESCI0"]
    #[inline(always)]
    #[must_use]
    pub fn pesci0(&mut self) -> PESCI0_W<16> {
        PESCI0_W::new(self)
    }
    #[doc = "Bit 17 - Protocol Error status of SCI1 - PESCI1"]
    #[inline(always)]
    #[must_use]
    pub fn pesci1(&mut self) -> PESCI1_W<17> {
        PESCI1_W::new(self)
    }
    #[doc = "Bit 18 - Protocol Error status of SCI2 - PESCI2"]
    #[inline(always)]
    #[must_use]
    pub fn pesci2(&mut self) -> PESCI2_W<18> {
        PESCI2_W::new(self)
    }
    #[doc = "Bit 19 - Protocol Error status of SCI3 - PESCI3"]
    #[inline(always)]
    #[must_use]
    pub fn pesci3(&mut self) -> PESCI3_W<19> {
        PESCI3_W::new(self)
    }
    #[doc = "Bit 20 - Protocol Error status of SCI4 - PESCI4"]
    #[inline(always)]
    #[must_use]
    pub fn pesci4(&mut self) -> PESCI4_W<20> {
        PESCI4_W::new(self)
    }
    #[doc = "Bit 21 - Protocol Error status of SCI5 - PESCI5"]
    #[inline(always)]
    #[must_use]
    pub fn pesci5(&mut self) -> PESCI5_W<21> {
        PESCI5_W::new(self)
    }
    #[doc = "Bit 22 - Protocol Error status of SCI6 - PESCI6"]
    #[inline(always)]
    #[must_use]
    pub fn pesci6(&mut self) -> PESCI6_W<22> {
        PESCI6_W::new(self)
    }
    #[doc = "Bit 23 - Protocol Error status of SCI7 - PESCI7"]
    #[inline(always)]
    #[must_use]
    pub fn pesci7(&mut self) -> PESCI7_W<23> {
        PESCI7_W::new(self)
    }
    #[doc = "Bit 24 - Protocol Error status of SCI8 - PESCI8"]
    #[inline(always)]
    #[must_use]
    pub fn pesci8(&mut self) -> PESCI8_W<24> {
        PESCI8_W::new(self)
    }
    #[doc = "Bit 25 - Protocol Error status of SCI9 - PESCI9"]
    #[inline(always)]
    #[must_use]
    pub fn pesci9(&mut self) -> PESCI9_W<25> {
        PESCI9_W::new(self)
    }
    #[doc = "Bit 26 - Protocol Error status of SCI10 - PESCI10"]
    #[inline(always)]
    #[must_use]
    pub fn pesci10(&mut self) -> PESCI10_W<26> {
        PESCI10_W::new(self)
    }
    #[doc = "Bit 27 - Protocol Error status of SCI11 - PESCI11"]
    #[inline(always)]
    #[must_use]
    pub fn pesci11(&mut self) -> PESCI11_W<27> {
        PESCI11_W::new(self)
    }
    #[doc = "Bit 28 - Protocol Error status of SCI12 - PESCI12"]
    #[inline(always)]
    #[must_use]
    pub fn pesci12(&mut self) -> PESCI12_W<28> {
        PESCI12_W::new(self)
    }
    #[doc = "Bit 29 - Protocol Error status of SCI13 - PESCI13"]
    #[inline(always)]
    #[must_use]
    pub fn pesci13(&mut self) -> PESCI13_W<29> {
        PESCI13_W::new(self)
    }
    #[doc = "Bit 30 - Protocol Error status of SCI14 - PESCI14"]
    #[inline(always)]
    #[must_use]
    pub fn pesci14(&mut self) -> PESCI14_W<30> {
        PESCI14_W::new(self)
    }
    #[doc = "Bit 31 - Protocol Error status of SCI15 - PESCI15"]
    #[inline(always)]
    #[must_use]
    pub fn pesci15(&mut self) -> PESCI15_W<31> {
        PESCI15_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Protocol Error Status Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [pestat](index.html) module"]
pub struct PESTAT_SPEC;
impl crate::RegisterSpec for PESTAT_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [pestat::R](R) reader structure"]
impl crate::Readable for PESTAT_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [pestat::W](W) writer structure"]
impl crate::Writable for PESTAT_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets PESTAT to value 0"]
impl crate::Resettable for PESTAT_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
