// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `ESROCFG` reader"]
pub struct R(crate::R<ESROCFG_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<ESROCFG_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<ESROCFG_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<ESROCFG_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `ESROCFG` writer"]
pub struct W(crate::W<ESROCFG_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<ESROCFG_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<ESROCFG_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<ESROCFG_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `ARI` reader - Application Reset Indicator - ARI"]
pub type ARI_R = crate::BitReader<bool>;
#[doc = "Field `ARC` writer - Application Reset Indicator Clear - ARC"]
pub type ARC_W<'a, const O: u8> = crate::BitWriter<'a, u32, ESROCFG_SPEC, bool, O>;
impl R {
    #[doc = "Bit 0 - Application Reset Indicator - ARI"]
    #[inline(always)]
    pub fn ari(&self) -> ARI_R {
        ARI_R::new((self.bits & 1) != 0)
    }
}
impl W {
    #[doc = "Bit 1 - Application Reset Indicator Clear - ARC"]
    #[inline(always)]
    #[must_use]
    pub fn arc(&mut self) -> ARC_W<1> {
        ARC_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "ESR Output Configuration Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [esrocfg](index.html) module"]
pub struct ESROCFG_SPEC;
impl crate::RegisterSpec for ESROCFG_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [esrocfg::R](R) reader structure"]
impl crate::Readable for ESROCFG_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [esrocfg::W](W) writer structure"]
impl crate::Writable for ESROCFG_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets ESROCFG to value 0"]
impl crate::Resettable for ESROCFG_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
