// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `OMR` writer"]
pub struct W(crate::W<OMR_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<OMR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<OMR_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<OMR_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `PS0` writer - ESRx Pin Set Bit 0 - PS0"]
pub type PS0_W<'a, const O: u8> = crate::BitWriter<'a, u32, OMR_SPEC, bool, O>;
#[doc = "Field `PS1` writer - ESRx Pin Set Bit 1 - PS1"]
pub type PS1_W<'a, const O: u8> = crate::BitWriter<'a, u32, OMR_SPEC, bool, O>;
#[doc = "Field `PCL0` writer - ESRx Pin Clear Bit 0 - PCL0"]
pub type PCL0_W<'a, const O: u8> = crate::BitWriter<'a, u32, OMR_SPEC, bool, O>;
#[doc = "Field `PCL1` writer - ESRx Pin Clear Bit 1 - PCL1"]
pub type PCL1_W<'a, const O: u8> = crate::BitWriter<'a, u32, OMR_SPEC, bool, O>;
impl W {
    #[doc = "Bit 0 - ESRx Pin Set Bit 0 - PS0"]
    #[inline(always)]
    #[must_use]
    pub fn ps0(&mut self) -> PS0_W<0> {
        PS0_W::new(self)
    }
    #[doc = "Bit 1 - ESRx Pin Set Bit 1 - PS1"]
    #[inline(always)]
    #[must_use]
    pub fn ps1(&mut self) -> PS1_W<1> {
        PS1_W::new(self)
    }
    #[doc = "Bit 16 - ESRx Pin Clear Bit 0 - PCL0"]
    #[inline(always)]
    #[must_use]
    pub fn pcl0(&mut self) -> PCL0_W<16> {
        PCL0_W::new(self)
    }
    #[doc = "Bit 17 - ESRx Pin Clear Bit 1 - PCL1"]
    #[inline(always)]
    #[must_use]
    pub fn pcl1(&mut self) -> PCL1_W<17> {
        PCL1_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "ESR Output Modification Register\n\nThis register you can [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [omr](index.html) module"]
pub struct OMR_SPEC;
impl crate::RegisterSpec for OMR_SPEC {
    type Ux = u32;
}
#[doc = "`write(|w| ..)` method takes [omr::W](W) writer structure"]
impl crate::Writable for OMR_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets OMR to value 0"]
impl crate::Resettable for OMR_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
