// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `PERPLLCON1` reader"]
pub struct R(crate::R<PERPLLCON1_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<PERPLLCON1_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<PERPLLCON1_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<PERPLLCON1_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `PERPLLCON1` writer"]
pub struct W(crate::W<PERPLLCON1_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<PERPLLCON1_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<PERPLLCON1_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<PERPLLCON1_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `K2DIV` reader - K2-Divider Value - K2DIV"]
pub type K2DIV_R = crate::FieldReader<u8, u8>;
#[doc = "Field `K2DIV` writer - K2-Divider Value - K2DIV"]
pub type K2DIV_W<'a, const O: u8> = crate::FieldWriter<'a, u32, PERPLLCON1_SPEC, u8, u8, 3, O>;
#[doc = "Field `K3DIV` reader - K3-Divider Value - K3DIV"]
pub type K3DIV_R = crate::FieldReader<u8, u8>;
#[doc = "Field `K3DIV` writer - K3-Divider Value - K3DIV"]
pub type K3DIV_W<'a, const O: u8> = crate::FieldWriter<'a, u32, PERPLLCON1_SPEC, u8, u8, 3, O>;
impl R {
    #[doc = "Bits 0:2 - K2-Divider Value - K2DIV"]
    #[inline(always)]
    pub fn k2div(&self) -> K2DIV_R {
        K2DIV_R::new((self.bits & 7) as u8)
    }
    #[doc = "Bits 8:10 - K3-Divider Value - K3DIV"]
    #[inline(always)]
    pub fn k3div(&self) -> K3DIV_R {
        K3DIV_R::new(((self.bits >> 8) & 7) as u8)
    }
}
impl W {
    #[doc = "Bits 0:2 - K2-Divider Value - K2DIV"]
    #[inline(always)]
    #[must_use]
    pub fn k2div(&mut self) -> K2DIV_W<0> {
        K2DIV_W::new(self)
    }
    #[doc = "Bits 8:10 - K3-Divider Value - K3DIV"]
    #[inline(always)]
    #[must_use]
    pub fn k3div(&mut self) -> K3DIV_W<8> {
        K3DIV_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Peripheral PLL Configuration 1 Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [perpllcon1](index.html) module"]
pub struct PERPLLCON1_SPEC;
impl crate::RegisterSpec for PERPLLCON1_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [perpllcon1::R](R) reader structure"]
impl crate::Readable for PERPLLCON1_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [perpllcon1::W](W) writer structure"]
impl crate::Writable for PERPLLCON1_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets PERPLLCON1 to value 0x01"]
impl crate::Resettable for PERPLLCON1_SPEC {
    const RESET_VALUE: Self::Ux = 0x01;
}
