// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `RSTCON` reader"]
pub struct R(crate::R<RSTCON_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<RSTCON_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<RSTCON_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<RSTCON_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `RSTCON` writer"]
pub struct W(crate::W<RSTCON_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<RSTCON_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<RSTCON_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<RSTCON_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `ESR0` reader - ESR0 Reset Request Trigger Reset Configuration - ESR0"]
pub type ESR0_R = crate::FieldReader<u8, u8>;
#[doc = "Field `ESR0` writer - ESR0 Reset Request Trigger Reset Configuration - ESR0"]
pub type ESR0_W<'a, const O: u8> = crate::FieldWriter<'a, u32, RSTCON_SPEC, u8, u8, 2, O>;
#[doc = "Field `ESR1` reader - ESR1 Reset Request Trigger Reset Configuration - ESR1"]
pub type ESR1_R = crate::FieldReader<u8, u8>;
#[doc = "Field `ESR1` writer - ESR1 Reset Request Trigger Reset Configuration - ESR1"]
pub type ESR1_W<'a, const O: u8> = crate::FieldWriter<'a, u32, RSTCON_SPEC, u8, u8, 2, O>;
#[doc = "Field `SMU` reader - SMU Reset Request Trigger Reset Configuration - SMU"]
pub type SMU_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SMU` writer - SMU Reset Request Trigger Reset Configuration - SMU"]
pub type SMU_W<'a, const O: u8> = crate::FieldWriter<'a, u32, RSTCON_SPEC, u8, u8, 2, O>;
#[doc = "Field `SW` reader - SW Reset Request Trigger Reset Configuration - SW"]
pub type SW_R = crate::FieldReader<u8, u8>;
#[doc = "Field `SW` writer - SW Reset Request Trigger Reset Configuration - SW"]
pub type SW_W<'a, const O: u8> = crate::FieldWriter<'a, u32, RSTCON_SPEC, u8, u8, 2, O>;
#[doc = "Field `STM0` reader - STM0 Reset Request Trigger Reset Configuration - STM0"]
pub type STM0_R = crate::FieldReader<u8, u8>;
#[doc = "Field `STM0` writer - STM0 Reset Request Trigger Reset Configuration - STM0"]
pub type STM0_W<'a, const O: u8> = crate::FieldWriter<'a, u32, RSTCON_SPEC, u8, u8, 2, O>;
#[doc = "Field `STM1` reader - STM1 Reset Request Trigger Reset Configuration (If Product has STM1) - STM1"]
pub type STM1_R = crate::FieldReader<u8, u8>;
#[doc = "Field `STM1` writer - STM1 Reset Request Trigger Reset Configuration (If Product has STM1) - STM1"]
pub type STM1_W<'a, const O: u8> = crate::FieldWriter<'a, u32, RSTCON_SPEC, u8, u8, 2, O>;
#[doc = "Field `STM2` reader - STM2 Reset Request Trigger Reset Configuration (If Product has STM2) - STM2"]
pub type STM2_R = crate::FieldReader<u8, u8>;
#[doc = "Field `STM2` writer - STM2 Reset Request Trigger Reset Configuration (If Product has STM2) - STM2"]
pub type STM2_W<'a, const O: u8> = crate::FieldWriter<'a, u32, RSTCON_SPEC, u8, u8, 2, O>;
impl R {
    #[doc = "Bits 0:1 - ESR0 Reset Request Trigger Reset Configuration - ESR0"]
    #[inline(always)]
    pub fn esr0(&self) -> ESR0_R {
        ESR0_R::new((self.bits & 3) as u8)
    }
    #[doc = "Bits 2:3 - ESR1 Reset Request Trigger Reset Configuration - ESR1"]
    #[inline(always)]
    pub fn esr1(&self) -> ESR1_R {
        ESR1_R::new(((self.bits >> 2) & 3) as u8)
    }
    #[doc = "Bits 6:7 - SMU Reset Request Trigger Reset Configuration - SMU"]
    #[inline(always)]
    pub fn smu(&self) -> SMU_R {
        SMU_R::new(((self.bits >> 6) & 3) as u8)
    }
    #[doc = "Bits 8:9 - SW Reset Request Trigger Reset Configuration - SW"]
    #[inline(always)]
    pub fn sw(&self) -> SW_R {
        SW_R::new(((self.bits >> 8) & 3) as u8)
    }
    #[doc = "Bits 10:11 - STM0 Reset Request Trigger Reset Configuration - STM0"]
    #[inline(always)]
    pub fn stm0(&self) -> STM0_R {
        STM0_R::new(((self.bits >> 10) & 3) as u8)
    }
    #[doc = "Bits 12:13 - STM1 Reset Request Trigger Reset Configuration (If Product has STM1) - STM1"]
    #[inline(always)]
    pub fn stm1(&self) -> STM1_R {
        STM1_R::new(((self.bits >> 12) & 3) as u8)
    }
    #[doc = "Bits 14:15 - STM2 Reset Request Trigger Reset Configuration (If Product has STM2) - STM2"]
    #[inline(always)]
    pub fn stm2(&self) -> STM2_R {
        STM2_R::new(((self.bits >> 14) & 3) as u8)
    }
}
impl W {
    #[doc = "Bits 0:1 - ESR0 Reset Request Trigger Reset Configuration - ESR0"]
    #[inline(always)]
    #[must_use]
    pub fn esr0(&mut self) -> ESR0_W<0> {
        ESR0_W::new(self)
    }
    #[doc = "Bits 2:3 - ESR1 Reset Request Trigger Reset Configuration - ESR1"]
    #[inline(always)]
    #[must_use]
    pub fn esr1(&mut self) -> ESR1_W<2> {
        ESR1_W::new(self)
    }
    #[doc = "Bits 6:7 - SMU Reset Request Trigger Reset Configuration - SMU"]
    #[inline(always)]
    #[must_use]
    pub fn smu(&mut self) -> SMU_W<6> {
        SMU_W::new(self)
    }
    #[doc = "Bits 8:9 - SW Reset Request Trigger Reset Configuration - SW"]
    #[inline(always)]
    #[must_use]
    pub fn sw(&mut self) -> SW_W<8> {
        SW_W::new(self)
    }
    #[doc = "Bits 10:11 - STM0 Reset Request Trigger Reset Configuration - STM0"]
    #[inline(always)]
    #[must_use]
    pub fn stm0(&mut self) -> STM0_W<10> {
        STM0_W::new(self)
    }
    #[doc = "Bits 12:13 - STM1 Reset Request Trigger Reset Configuration (If Product has STM1) - STM1"]
    #[inline(always)]
    #[must_use]
    pub fn stm1(&mut self) -> STM1_W<12> {
        STM1_W::new(self)
    }
    #[doc = "Bits 14:15 - STM2 Reset Request Trigger Reset Configuration (If Product has STM2) - STM2"]
    #[inline(always)]
    #[must_use]
    pub fn stm2(&mut self) -> STM2_W<14> {
        STM2_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "RSTCON\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [rstcon](index.html) module"]
pub struct RSTCON_SPEC;
impl crate::RegisterSpec for RSTCON_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [rstcon::R](R) reader structure"]
impl crate::Readable for RSTCON_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [rstcon::W](W) writer structure"]
impl crate::Writable for RSTCON_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets RSTCON to value 0x0282"]
impl crate::Resettable for RSTCON_SPEC {
    const RESET_VALUE: Self::Ux = 0x0282;
}
