// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `WDTCPU0SR` reader"]
pub struct R(crate::R<WDTCPU0SR_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<WDTCPU0SR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<WDTCPU0SR_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<WDTCPU0SR_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `AE` reader - Watchdog Access Error Status Flag - AE"]
pub type AE_R = crate::BitReader<bool>;
#[doc = "Field `OE` reader - Watchdog Overflow Error Status Flag - OE"]
pub type OE_R = crate::BitReader<bool>;
#[doc = "Field `IS0` reader - Watchdog Input Clock Status - IS1,IS0"]
pub type IS0_R = crate::BitReader<bool>;
#[doc = "Field `DS` reader - Watchdog Enable/Disable Status Flag - DS"]
pub type DS_R = crate::BitReader<bool>;
#[doc = "Field `TO` reader - Watchdog Time-Out Mode Flag - TO"]
pub type TO_R = crate::BitReader<bool>;
#[doc = "Field `IS1` reader - Watchdog Input Clock Status - IS1,IS0"]
pub type IS1_R = crate::BitReader<bool>;
#[doc = "Field `US` reader - SMU Unlock Restriction Status Flag - US"]
pub type US_R = crate::BitReader<bool>;
#[doc = "Field `PAS` reader - Password Auto-sequence Status Flag - PAS"]
pub type PAS_R = crate::BitReader<bool>;
#[doc = "Field `TCS` reader - Timer Check Status Flag - TCS"]
pub type TCS_R = crate::BitReader<bool>;
#[doc = "Field `TCT` reader - Timer Check Tolerance - TCT"]
pub type TCT_R = crate::FieldReader<u8, u8>;
#[doc = "Field `TIM` reader - Timer Value - TIM"]
pub type TIM_R = crate::FieldReader<u16, u16>;
impl R {
    #[doc = "Bit 0 - Watchdog Access Error Status Flag - AE"]
    #[inline(always)]
    pub fn ae(&self) -> AE_R {
        AE_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - Watchdog Overflow Error Status Flag - OE"]
    #[inline(always)]
    pub fn oe(&self) -> OE_R {
        OE_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - Watchdog Input Clock Status - IS1,IS0"]
    #[inline(always)]
    pub fn is0(&self) -> IS0_R {
        IS0_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - Watchdog Enable/Disable Status Flag - DS"]
    #[inline(always)]
    pub fn ds(&self) -> DS_R {
        DS_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 4 - Watchdog Time-Out Mode Flag - TO"]
    #[inline(always)]
    pub fn to(&self) -> TO_R {
        TO_R::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 5 - Watchdog Input Clock Status - IS1,IS0"]
    #[inline(always)]
    pub fn is1(&self) -> IS1_R {
        IS1_R::new(((self.bits >> 5) & 1) != 0)
    }
    #[doc = "Bit 6 - SMU Unlock Restriction Status Flag - US"]
    #[inline(always)]
    pub fn us(&self) -> US_R {
        US_R::new(((self.bits >> 6) & 1) != 0)
    }
    #[doc = "Bit 7 - Password Auto-sequence Status Flag - PAS"]
    #[inline(always)]
    pub fn pas(&self) -> PAS_R {
        PAS_R::new(((self.bits >> 7) & 1) != 0)
    }
    #[doc = "Bit 8 - Timer Check Status Flag - TCS"]
    #[inline(always)]
    pub fn tcs(&self) -> TCS_R {
        TCS_R::new(((self.bits >> 8) & 1) != 0)
    }
    #[doc = "Bits 9:15 - Timer Check Tolerance - TCT"]
    #[inline(always)]
    pub fn tct(&self) -> TCT_R {
        TCT_R::new(((self.bits >> 9) & 0x7f) as u8)
    }
    #[doc = "Bits 16:31 - Timer Value - TIM"]
    #[inline(always)]
    pub fn tim(&self) -> TIM_R {
        TIM_R::new(((self.bits >> 16) & 0xffff) as u16)
    }
}
#[doc = "WDTCPU0SR\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [wdtcpu0sr](index.html) module"]
pub struct WDTCPU0SR_SPEC;
impl crate::RegisterSpec for WDTCPU0SR_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [wdtcpu0sr::R](R) reader structure"]
impl crate::Readable for WDTCPU0SR_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets WDTCPU0SR to value 0xfffc_0010"]
impl crate::Resettable for WDTCPU0SR_SPEC {
    const RESET_VALUE: Self::Ux = 0xfffc_0010;
}
