// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `HF_PSTATUS` reader"]
pub struct R(crate::R<HF_PSTATUS_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<HF_PSTATUS_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<HF_PSTATUS_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<HF_PSTATUS_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `SLEEP` reader - Sleep Mode - SLEEP"]
pub type SLEEP_R = crate::BitReader<bool>;
#[doc = "Field `IDLE` reader - Dynamic Idle - IDLE"]
pub type IDLE_R = crate::BitReader<bool>;
#[doc = "Field `DEMAND` reader - Demand - DEMAND"]
pub type DEMAND_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bit 0 - Sleep Mode - SLEEP"]
    #[inline(always)]
    pub fn sleep(&self) -> SLEEP_R {
        SLEEP_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - Dynamic Idle - IDLE"]
    #[inline(always)]
    pub fn idle(&self) -> IDLE_R {
        IDLE_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - Demand - DEMAND"]
    #[inline(always)]
    pub fn demand(&self) -> DEMAND_R {
        DEMAND_R::new(((self.bits >> 2) & 1) != 0)
    }
}
#[doc = "Power Status Register\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [hf_pstatus](index.html) module"]
pub struct HF_PSTATUS_SPEC;
impl crate::RegisterSpec for HF_PSTATUS_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [hf_pstatus::R](R) reader structure"]
impl crate::Readable for HF_PSTATUS_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets HF_PSTATUS to value 0"]
impl crate::Resettable for HF_PSTATUS_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
