// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `HF_STATUS` reader"]
pub struct R(crate::R<HF_STATUS_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<HF_STATUS_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<HF_STATUS_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<HF_STATUS_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `D0BUSY` reader - Data Flash Bank 0 Busy - D0BUSY"]
pub type D0BUSY_R = crate::BitReader<bool>;
#[doc = "Field `D1BUSY` reader - Data Flash Bank 1 Busy - D1BUSY"]
pub type D1BUSY_R = crate::BitReader<bool>;
#[doc = "Field `P0BUSY` reader - Program Flash PF0BUSY - P0BUSY"]
pub type P0BUSY_R = crate::BitReader<bool>;
#[doc = "Field `P1BUSY` reader - Program Flash PF1BUSY - P1BUSY"]
pub type P1BUSY_R = crate::BitReader<bool>;
#[doc = "Field `DFPAGE` reader - Data Flash in Page Mode - DFPAGE"]
pub type DFPAGE_R = crate::BitReader<bool>;
#[doc = "Field `PFPAGE` reader - Program Flash in Page Mode - PFPAGE"]
pub type PFPAGE_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bit 0 - Data Flash Bank 0 Busy - D0BUSY"]
    #[inline(always)]
    pub fn d0busy(&self) -> D0BUSY_R {
        D0BUSY_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - Data Flash Bank 1 Busy - D1BUSY"]
    #[inline(always)]
    pub fn d1busy(&self) -> D1BUSY_R {
        D1BUSY_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - Program Flash PF0BUSY - P0BUSY"]
    #[inline(always)]
    pub fn p0busy(&self) -> P0BUSY_R {
        P0BUSY_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - Program Flash PF1BUSY - P1BUSY"]
    #[inline(always)]
    pub fn p1busy(&self) -> P1BUSY_R {
        P1BUSY_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 20 - Data Flash in Page Mode - DFPAGE"]
    #[inline(always)]
    pub fn dfpage(&self) -> DFPAGE_R {
        DFPAGE_R::new(((self.bits >> 20) & 1) != 0)
    }
    #[doc = "Bit 21 - Program Flash in Page Mode - PFPAGE"]
    #[inline(always)]
    pub fn pfpage(&self) -> PFPAGE_R {
        PFPAGE_R::new(((self.bits >> 21) & 1) != 0)
    }
}
#[doc = "Flash Status Register\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [hf_status](index.html) module"]
pub struct HF_STATUS_SPEC;
impl crate::RegisterSpec for HF_STATUS_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [hf_status::R](R) reader structure"]
impl crate::Readable for HF_STATUS_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets HF_STATUS to value 0xff"]
impl crate::Resettable for HF_STATUS_SPEC {
    const RESET_VALUE: Self::Ux = 0xff;
}
