// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `HP_ECPRIO10` reader"]
pub struct R(crate::R<HP_ECPRIO10_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<HP_ECPRIO10_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<HP_ECPRIO10_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<HP_ECPRIO10_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `S0L` reader - PFLASH p Sector 0 Erase Counter priority - S0L"]
pub type S0L_R = crate::BitReader<bool>;
#[doc = "Field `S1L` reader - PFLASH p Sector 1 Erase Counter priority - S1L"]
pub type S1L_R = crate::BitReader<bool>;
#[doc = "Field `S2L` reader - PFLASH p Sector 2 Erase Counter priority - S2L"]
pub type S2L_R = crate::BitReader<bool>;
#[doc = "Field `S3L` reader - PFLASH p Sector 3 Erase Counter priority - S3L"]
pub type S3L_R = crate::BitReader<bool>;
#[doc = "Field `S4L` reader - PFLASH p Sector 4 Erase Counter priority - S4L"]
pub type S4L_R = crate::BitReader<bool>;
#[doc = "Field `S5L` reader - PFLASH p Sector 5 Erase Counter priority - S5L"]
pub type S5L_R = crate::BitReader<bool>;
#[doc = "Field `S6L` reader - PFLASH p Sector 6 Erase Counter priority - S6L"]
pub type S6L_R = crate::BitReader<bool>;
#[doc = "Field `S7L` reader - PFLASH p Sector 7 Erase Counter priority - S7L"]
pub type S7L_R = crate::BitReader<bool>;
#[doc = "Field `S8L` reader - PFLASH p Sector 8 Erase Counter priority - S8L"]
pub type S8L_R = crate::BitReader<bool>;
#[doc = "Field `S9L` reader - PFLASH p Sector 9 Erase Counter priority - S9L"]
pub type S9L_R = crate::BitReader<bool>;
#[doc = "Field `S10L` reader - PFLASH p Sector 10 Erase Counter priority - S10L"]
pub type S10L_R = crate::BitReader<bool>;
#[doc = "Field `S11L` reader - PFLASH p Sector 11 Erase Counter priority - S11L"]
pub type S11L_R = crate::BitReader<bool>;
#[doc = "Field `S12L` reader - PFLASH p Sector 12 Erase Counter priority - S12L"]
pub type S12L_R = crate::BitReader<bool>;
#[doc = "Field `S13L` reader - PFLASH p Sector 13 Erase Counter priority - S13L"]
pub type S13L_R = crate::BitReader<bool>;
#[doc = "Field `S14L` reader - PFLASH p Sector 14 Erase Counter priority - S14L"]
pub type S14L_R = crate::BitReader<bool>;
#[doc = "Field `S15L` reader - PFLASH p Sector 15 Erase Counter priority - S15L"]
pub type S15L_R = crate::BitReader<bool>;
#[doc = "Field `S16L` reader - PFLASH p Sector 16 Erase Counter priority - S16L"]
pub type S16L_R = crate::BitReader<bool>;
#[doc = "Field `S17L` reader - PFLASH p Sector 17 Erase Counter priority - S17L"]
pub type S17L_R = crate::BitReader<bool>;
#[doc = "Field `S18L` reader - PFLASH p Sector 18 Erase Counter priority - S18L"]
pub type S18L_R = crate::BitReader<bool>;
#[doc = "Field `S19L` reader - PFLASH p Sector 19 Erase Counter priority - S19L"]
pub type S19L_R = crate::BitReader<bool>;
#[doc = "Field `S20L` reader - PFLASH p Sector 20 Erase Counter priority - S20L"]
pub type S20L_R = crate::BitReader<bool>;
#[doc = "Field `S21L` reader - PFLASH p Sector 21 Erase Counter priority - S21L"]
pub type S21L_R = crate::BitReader<bool>;
#[doc = "Field `S22L` reader - PFLASH p Sector 22 Erase Counter priority - S22L"]
pub type S22L_R = crate::BitReader<bool>;
#[doc = "Field `S23L` reader - PFLASH p Sector 23 Erase Counter priority - S23L"]
pub type S23L_R = crate::BitReader<bool>;
#[doc = "Field `S24L` reader - PFLASH p Sector 24 Erase Counter priority - S24L"]
pub type S24L_R = crate::BitReader<bool>;
#[doc = "Field `S25L` reader - PFLASH p Sector 25 Erase Counter priority - S25L"]
pub type S25L_R = crate::BitReader<bool>;
#[doc = "Field `S26L` reader - PFLASH p Sector 26 Erase Counter priority - S26L"]
pub type S26L_R = crate::BitReader<bool>;
#[doc = "Field `S27L` reader - PFLASH p Sector 27 Erase Counter priority - S27L"]
pub type S27L_R = crate::BitReader<bool>;
#[doc = "Field `S28L` reader - PFLASH p Sector 28 Erase Counter priority - S28L"]
pub type S28L_R = crate::BitReader<bool>;
#[doc = "Field `S29L` reader - PFLASH p Sector 29 Erase Counter priority - S29L"]
pub type S29L_R = crate::BitReader<bool>;
#[doc = "Field `S30L` reader - PFLASH p Sector 30 Erase Counter priority - S30L"]
pub type S30L_R = crate::BitReader<bool>;
#[doc = "Field `S31L` reader - PFLASH p Sector 31 Erase Counter priority - S31L"]
pub type S31L_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bit 0 - PFLASH p Sector 0 Erase Counter priority - S0L"]
    #[inline(always)]
    pub fn s0l(&self) -> S0L_R {
        S0L_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - PFLASH p Sector 1 Erase Counter priority - S1L"]
    #[inline(always)]
    pub fn s1l(&self) -> S1L_R {
        S1L_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - PFLASH p Sector 2 Erase Counter priority - S2L"]
    #[inline(always)]
    pub fn s2l(&self) -> S2L_R {
        S2L_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - PFLASH p Sector 3 Erase Counter priority - S3L"]
    #[inline(always)]
    pub fn s3l(&self) -> S3L_R {
        S3L_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 4 - PFLASH p Sector 4 Erase Counter priority - S4L"]
    #[inline(always)]
    pub fn s4l(&self) -> S4L_R {
        S4L_R::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 5 - PFLASH p Sector 5 Erase Counter priority - S5L"]
    #[inline(always)]
    pub fn s5l(&self) -> S5L_R {
        S5L_R::new(((self.bits >> 5) & 1) != 0)
    }
    #[doc = "Bit 6 - PFLASH p Sector 6 Erase Counter priority - S6L"]
    #[inline(always)]
    pub fn s6l(&self) -> S6L_R {
        S6L_R::new(((self.bits >> 6) & 1) != 0)
    }
    #[doc = "Bit 7 - PFLASH p Sector 7 Erase Counter priority - S7L"]
    #[inline(always)]
    pub fn s7l(&self) -> S7L_R {
        S7L_R::new(((self.bits >> 7) & 1) != 0)
    }
    #[doc = "Bit 8 - PFLASH p Sector 8 Erase Counter priority - S8L"]
    #[inline(always)]
    pub fn s8l(&self) -> S8L_R {
        S8L_R::new(((self.bits >> 8) & 1) != 0)
    }
    #[doc = "Bit 9 - PFLASH p Sector 9 Erase Counter priority - S9L"]
    #[inline(always)]
    pub fn s9l(&self) -> S9L_R {
        S9L_R::new(((self.bits >> 9) & 1) != 0)
    }
    #[doc = "Bit 10 - PFLASH p Sector 10 Erase Counter priority - S10L"]
    #[inline(always)]
    pub fn s10l(&self) -> S10L_R {
        S10L_R::new(((self.bits >> 10) & 1) != 0)
    }
    #[doc = "Bit 11 - PFLASH p Sector 11 Erase Counter priority - S11L"]
    #[inline(always)]
    pub fn s11l(&self) -> S11L_R {
        S11L_R::new(((self.bits >> 11) & 1) != 0)
    }
    #[doc = "Bit 12 - PFLASH p Sector 12 Erase Counter priority - S12L"]
    #[inline(always)]
    pub fn s12l(&self) -> S12L_R {
        S12L_R::new(((self.bits >> 12) & 1) != 0)
    }
    #[doc = "Bit 13 - PFLASH p Sector 13 Erase Counter priority - S13L"]
    #[inline(always)]
    pub fn s13l(&self) -> S13L_R {
        S13L_R::new(((self.bits >> 13) & 1) != 0)
    }
    #[doc = "Bit 14 - PFLASH p Sector 14 Erase Counter priority - S14L"]
    #[inline(always)]
    pub fn s14l(&self) -> S14L_R {
        S14L_R::new(((self.bits >> 14) & 1) != 0)
    }
    #[doc = "Bit 15 - PFLASH p Sector 15 Erase Counter priority - S15L"]
    #[inline(always)]
    pub fn s15l(&self) -> S15L_R {
        S15L_R::new(((self.bits >> 15) & 1) != 0)
    }
    #[doc = "Bit 16 - PFLASH p Sector 16 Erase Counter priority - S16L"]
    #[inline(always)]
    pub fn s16l(&self) -> S16L_R {
        S16L_R::new(((self.bits >> 16) & 1) != 0)
    }
    #[doc = "Bit 17 - PFLASH p Sector 17 Erase Counter priority - S17L"]
    #[inline(always)]
    pub fn s17l(&self) -> S17L_R {
        S17L_R::new(((self.bits >> 17) & 1) != 0)
    }
    #[doc = "Bit 18 - PFLASH p Sector 18 Erase Counter priority - S18L"]
    #[inline(always)]
    pub fn s18l(&self) -> S18L_R {
        S18L_R::new(((self.bits >> 18) & 1) != 0)
    }
    #[doc = "Bit 19 - PFLASH p Sector 19 Erase Counter priority - S19L"]
    #[inline(always)]
    pub fn s19l(&self) -> S19L_R {
        S19L_R::new(((self.bits >> 19) & 1) != 0)
    }
    #[doc = "Bit 20 - PFLASH p Sector 20 Erase Counter priority - S20L"]
    #[inline(always)]
    pub fn s20l(&self) -> S20L_R {
        S20L_R::new(((self.bits >> 20) & 1) != 0)
    }
    #[doc = "Bit 21 - PFLASH p Sector 21 Erase Counter priority - S21L"]
    #[inline(always)]
    pub fn s21l(&self) -> S21L_R {
        S21L_R::new(((self.bits >> 21) & 1) != 0)
    }
    #[doc = "Bit 22 - PFLASH p Sector 22 Erase Counter priority - S22L"]
    #[inline(always)]
    pub fn s22l(&self) -> S22L_R {
        S22L_R::new(((self.bits >> 22) & 1) != 0)
    }
    #[doc = "Bit 23 - PFLASH p Sector 23 Erase Counter priority - S23L"]
    #[inline(always)]
    pub fn s23l(&self) -> S23L_R {
        S23L_R::new(((self.bits >> 23) & 1) != 0)
    }
    #[doc = "Bit 24 - PFLASH p Sector 24 Erase Counter priority - S24L"]
    #[inline(always)]
    pub fn s24l(&self) -> S24L_R {
        S24L_R::new(((self.bits >> 24) & 1) != 0)
    }
    #[doc = "Bit 25 - PFLASH p Sector 25 Erase Counter priority - S25L"]
    #[inline(always)]
    pub fn s25l(&self) -> S25L_R {
        S25L_R::new(((self.bits >> 25) & 1) != 0)
    }
    #[doc = "Bit 26 - PFLASH p Sector 26 Erase Counter priority - S26L"]
    #[inline(always)]
    pub fn s26l(&self) -> S26L_R {
        S26L_R::new(((self.bits >> 26) & 1) != 0)
    }
    #[doc = "Bit 27 - PFLASH p Sector 27 Erase Counter priority - S27L"]
    #[inline(always)]
    pub fn s27l(&self) -> S27L_R {
        S27L_R::new(((self.bits >> 27) & 1) != 0)
    }
    #[doc = "Bit 28 - PFLASH p Sector 28 Erase Counter priority - S28L"]
    #[inline(always)]
    pub fn s28l(&self) -> S28L_R {
        S28L_R::new(((self.bits >> 28) & 1) != 0)
    }
    #[doc = "Bit 29 - PFLASH p Sector 29 Erase Counter priority - S29L"]
    #[inline(always)]
    pub fn s29l(&self) -> S29L_R {
        S29L_R::new(((self.bits >> 29) & 1) != 0)
    }
    #[doc = "Bit 30 - PFLASH p Sector 30 Erase Counter priority - S30L"]
    #[inline(always)]
    pub fn s30l(&self) -> S30L_R {
        S30L_R::new(((self.bits >> 30) & 1) != 0)
    }
    #[doc = "Bit 31 - PFLASH p Sector 31 Erase Counter priority - S31L"]
    #[inline(always)]
    pub fn s31l(&self) -> S31L_R {
        S31L_R::new(((self.bits >> 31) & 1) != 0)
    }
}
#[doc = "PFLASH Bank 1 Erase Counter Priority configuration 0\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [hp_ecprio10](index.html) module"]
pub struct HP_ECPRIO10_SPEC;
impl crate::RegisterSpec for HP_ECPRIO10_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [hp_ecprio10::R](R) reader structure"]
impl crate::Readable for HP_ECPRIO10_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets HP_ECPRIO10 to value 0"]
impl crate::Resettable for HP_ECPRIO10_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
