// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `HP_PROCONOTP00` reader"]
pub struct R(crate::R<HP_PROCONOTP00_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<HP_PROCONOTP00_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<HP_PROCONOTP00_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<HP_PROCONOTP00_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `S0ROM` reader - PFLASH p Sector 0 Locked for Forever - S0ROM"]
pub type S0ROM_R = crate::BitReader<bool>;
#[doc = "Field `S1ROM` reader - PFLASH p Sector 1 Locked for Forever - S1ROM"]
pub type S1ROM_R = crate::BitReader<bool>;
#[doc = "Field `S2ROM` reader - PFLASH p Sector 2 Locked for Forever - S2ROM"]
pub type S2ROM_R = crate::BitReader<bool>;
#[doc = "Field `S3ROM` reader - PFLASH p Sector 3 Locked for Forever - S3ROM"]
pub type S3ROM_R = crate::BitReader<bool>;
#[doc = "Field `S4ROM` reader - PFLASH p Sector 4 Locked for Forever - S4ROM"]
pub type S4ROM_R = crate::BitReader<bool>;
#[doc = "Field `S5ROM` reader - PFLASH p Sector 5 Locked for Forever - S5ROM"]
pub type S5ROM_R = crate::BitReader<bool>;
#[doc = "Field `S6ROM` reader - PFLASH p Sector 6 Locked for Forever - S6ROM"]
pub type S6ROM_R = crate::BitReader<bool>;
#[doc = "Field `S7ROM` reader - PFLASH p Sector 7 Locked for Forever - S7ROM"]
pub type S7ROM_R = crate::BitReader<bool>;
#[doc = "Field `S8ROM` reader - PFLASH p Sector 8 Locked for Forever - S8ROM"]
pub type S8ROM_R = crate::BitReader<bool>;
#[doc = "Field `S9ROM` reader - PFLASH p Sector 9 Locked for Forever - S9ROM"]
pub type S9ROM_R = crate::BitReader<bool>;
#[doc = "Field `S10ROM` reader - PFLASH p Sector 10 Locked for Forever - S10ROM"]
pub type S10ROM_R = crate::BitReader<bool>;
#[doc = "Field `S11ROM` reader - PFLASH p Sector 11 Locked for Forever - S11ROM"]
pub type S11ROM_R = crate::BitReader<bool>;
#[doc = "Field `S12ROM` reader - PFLASH p Sector 12 Locked for Forever - S12ROM"]
pub type S12ROM_R = crate::BitReader<bool>;
#[doc = "Field `S13ROM` reader - PFLASH p Sector 13 Locked for Forever - S13ROM"]
pub type S13ROM_R = crate::BitReader<bool>;
#[doc = "Field `S14ROM` reader - PFLASH p Sector 14 Locked for Forever - S14ROM"]
pub type S14ROM_R = crate::BitReader<bool>;
#[doc = "Field `S15ROM` reader - PFLASH p Sector 15 Locked for Forever - S15ROM"]
pub type S15ROM_R = crate::BitReader<bool>;
#[doc = "Field `S16ROM` reader - PFLASH p Sector 16 Locked for Forever - S16ROM"]
pub type S16ROM_R = crate::BitReader<bool>;
#[doc = "Field `S17ROM` reader - PFLASH p Sector 17 Locked for Forever - S17ROM"]
pub type S17ROM_R = crate::BitReader<bool>;
#[doc = "Field `S18ROM` reader - PFLASH p Sector 18 Locked for Forever - S18ROM"]
pub type S18ROM_R = crate::BitReader<bool>;
#[doc = "Field `S19ROM` reader - PFLASH p Sector 19 Locked for Forever - S19ROM"]
pub type S19ROM_R = crate::BitReader<bool>;
#[doc = "Field `S20ROM` reader - PFLASH p Sector 20 Locked for Forever - S20ROM"]
pub type S20ROM_R = crate::BitReader<bool>;
#[doc = "Field `S21ROM` reader - PFLASH p Sector 21 Locked for Forever - S21ROM"]
pub type S21ROM_R = crate::BitReader<bool>;
#[doc = "Field `S22ROM` reader - PFLASH p Sector 22 Locked for Forever - S22ROM"]
pub type S22ROM_R = crate::BitReader<bool>;
#[doc = "Field `S23ROM` reader - PFLASH p Sector 23 Locked for Forever - S23ROM"]
pub type S23ROM_R = crate::BitReader<bool>;
#[doc = "Field `S24ROM` reader - PFLASH p Sector 24 Locked for Forever - S24ROM"]
pub type S24ROM_R = crate::BitReader<bool>;
#[doc = "Field `S25ROM` reader - PFLASH p Sector 25 Locked for Forever - S25ROM"]
pub type S25ROM_R = crate::BitReader<bool>;
#[doc = "Field `S26ROM` reader - PFLASH p Sector 26 Locked for Forever - S26ROM"]
pub type S26ROM_R = crate::BitReader<bool>;
#[doc = "Field `S27ROM` reader - PFLASH p Sector 27 Locked for Forever - S27ROM"]
pub type S27ROM_R = crate::BitReader<bool>;
#[doc = "Field `S28ROM` reader - PFLASH p Sector 28 Locked for Forever - S28ROM"]
pub type S28ROM_R = crate::BitReader<bool>;
#[doc = "Field `S29ROM` reader - PFLASH p Sector 29 Locked for Forever - S29ROM"]
pub type S29ROM_R = crate::BitReader<bool>;
#[doc = "Field `S30ROM` reader - PFLASH p Sector 30 Locked for Forever - S30ROM"]
pub type S30ROM_R = crate::BitReader<bool>;
#[doc = "Field `S31ROM` reader - PFLASH p Sector 31 Locked for Forever - S31ROM"]
pub type S31ROM_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bit 0 - PFLASH p Sector 0 Locked for Forever - S0ROM"]
    #[inline(always)]
    pub fn s0rom(&self) -> S0ROM_R {
        S0ROM_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - PFLASH p Sector 1 Locked for Forever - S1ROM"]
    #[inline(always)]
    pub fn s1rom(&self) -> S1ROM_R {
        S1ROM_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - PFLASH p Sector 2 Locked for Forever - S2ROM"]
    #[inline(always)]
    pub fn s2rom(&self) -> S2ROM_R {
        S2ROM_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - PFLASH p Sector 3 Locked for Forever - S3ROM"]
    #[inline(always)]
    pub fn s3rom(&self) -> S3ROM_R {
        S3ROM_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 4 - PFLASH p Sector 4 Locked for Forever - S4ROM"]
    #[inline(always)]
    pub fn s4rom(&self) -> S4ROM_R {
        S4ROM_R::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 5 - PFLASH p Sector 5 Locked for Forever - S5ROM"]
    #[inline(always)]
    pub fn s5rom(&self) -> S5ROM_R {
        S5ROM_R::new(((self.bits >> 5) & 1) != 0)
    }
    #[doc = "Bit 6 - PFLASH p Sector 6 Locked for Forever - S6ROM"]
    #[inline(always)]
    pub fn s6rom(&self) -> S6ROM_R {
        S6ROM_R::new(((self.bits >> 6) & 1) != 0)
    }
    #[doc = "Bit 7 - PFLASH p Sector 7 Locked for Forever - S7ROM"]
    #[inline(always)]
    pub fn s7rom(&self) -> S7ROM_R {
        S7ROM_R::new(((self.bits >> 7) & 1) != 0)
    }
    #[doc = "Bit 8 - PFLASH p Sector 8 Locked for Forever - S8ROM"]
    #[inline(always)]
    pub fn s8rom(&self) -> S8ROM_R {
        S8ROM_R::new(((self.bits >> 8) & 1) != 0)
    }
    #[doc = "Bit 9 - PFLASH p Sector 9 Locked for Forever - S9ROM"]
    #[inline(always)]
    pub fn s9rom(&self) -> S9ROM_R {
        S9ROM_R::new(((self.bits >> 9) & 1) != 0)
    }
    #[doc = "Bit 10 - PFLASH p Sector 10 Locked for Forever - S10ROM"]
    #[inline(always)]
    pub fn s10rom(&self) -> S10ROM_R {
        S10ROM_R::new(((self.bits >> 10) & 1) != 0)
    }
    #[doc = "Bit 11 - PFLASH p Sector 11 Locked for Forever - S11ROM"]
    #[inline(always)]
    pub fn s11rom(&self) -> S11ROM_R {
        S11ROM_R::new(((self.bits >> 11) & 1) != 0)
    }
    #[doc = "Bit 12 - PFLASH p Sector 12 Locked for Forever - S12ROM"]
    #[inline(always)]
    pub fn s12rom(&self) -> S12ROM_R {
        S12ROM_R::new(((self.bits >> 12) & 1) != 0)
    }
    #[doc = "Bit 13 - PFLASH p Sector 13 Locked for Forever - S13ROM"]
    #[inline(always)]
    pub fn s13rom(&self) -> S13ROM_R {
        S13ROM_R::new(((self.bits >> 13) & 1) != 0)
    }
    #[doc = "Bit 14 - PFLASH p Sector 14 Locked for Forever - S14ROM"]
    #[inline(always)]
    pub fn s14rom(&self) -> S14ROM_R {
        S14ROM_R::new(((self.bits >> 14) & 1) != 0)
    }
    #[doc = "Bit 15 - PFLASH p Sector 15 Locked for Forever - S15ROM"]
    #[inline(always)]
    pub fn s15rom(&self) -> S15ROM_R {
        S15ROM_R::new(((self.bits >> 15) & 1) != 0)
    }
    #[doc = "Bit 16 - PFLASH p Sector 16 Locked for Forever - S16ROM"]
    #[inline(always)]
    pub fn s16rom(&self) -> S16ROM_R {
        S16ROM_R::new(((self.bits >> 16) & 1) != 0)
    }
    #[doc = "Bit 17 - PFLASH p Sector 17 Locked for Forever - S17ROM"]
    #[inline(always)]
    pub fn s17rom(&self) -> S17ROM_R {
        S17ROM_R::new(((self.bits >> 17) & 1) != 0)
    }
    #[doc = "Bit 18 - PFLASH p Sector 18 Locked for Forever - S18ROM"]
    #[inline(always)]
    pub fn s18rom(&self) -> S18ROM_R {
        S18ROM_R::new(((self.bits >> 18) & 1) != 0)
    }
    #[doc = "Bit 19 - PFLASH p Sector 19 Locked for Forever - S19ROM"]
    #[inline(always)]
    pub fn s19rom(&self) -> S19ROM_R {
        S19ROM_R::new(((self.bits >> 19) & 1) != 0)
    }
    #[doc = "Bit 20 - PFLASH p Sector 20 Locked for Forever - S20ROM"]
    #[inline(always)]
    pub fn s20rom(&self) -> S20ROM_R {
        S20ROM_R::new(((self.bits >> 20) & 1) != 0)
    }
    #[doc = "Bit 21 - PFLASH p Sector 21 Locked for Forever - S21ROM"]
    #[inline(always)]
    pub fn s21rom(&self) -> S21ROM_R {
        S21ROM_R::new(((self.bits >> 21) & 1) != 0)
    }
    #[doc = "Bit 22 - PFLASH p Sector 22 Locked for Forever - S22ROM"]
    #[inline(always)]
    pub fn s22rom(&self) -> S22ROM_R {
        S22ROM_R::new(((self.bits >> 22) & 1) != 0)
    }
    #[doc = "Bit 23 - PFLASH p Sector 23 Locked for Forever - S23ROM"]
    #[inline(always)]
    pub fn s23rom(&self) -> S23ROM_R {
        S23ROM_R::new(((self.bits >> 23) & 1) != 0)
    }
    #[doc = "Bit 24 - PFLASH p Sector 24 Locked for Forever - S24ROM"]
    #[inline(always)]
    pub fn s24rom(&self) -> S24ROM_R {
        S24ROM_R::new(((self.bits >> 24) & 1) != 0)
    }
    #[doc = "Bit 25 - PFLASH p Sector 25 Locked for Forever - S25ROM"]
    #[inline(always)]
    pub fn s25rom(&self) -> S25ROM_R {
        S25ROM_R::new(((self.bits >> 25) & 1) != 0)
    }
    #[doc = "Bit 26 - PFLASH p Sector 26 Locked for Forever - S26ROM"]
    #[inline(always)]
    pub fn s26rom(&self) -> S26ROM_R {
        S26ROM_R::new(((self.bits >> 26) & 1) != 0)
    }
    #[doc = "Bit 27 - PFLASH p Sector 27 Locked for Forever - S27ROM"]
    #[inline(always)]
    pub fn s27rom(&self) -> S27ROM_R {
        S27ROM_R::new(((self.bits >> 27) & 1) != 0)
    }
    #[doc = "Bit 28 - PFLASH p Sector 28 Locked for Forever - S28ROM"]
    #[inline(always)]
    pub fn s28rom(&self) -> S28ROM_R {
        S28ROM_R::new(((self.bits >> 28) & 1) != 0)
    }
    #[doc = "Bit 29 - PFLASH p Sector 29 Locked for Forever - S29ROM"]
    #[inline(always)]
    pub fn s29rom(&self) -> S29ROM_R {
        S29ROM_R::new(((self.bits >> 29) & 1) != 0)
    }
    #[doc = "Bit 30 - PFLASH p Sector 30 Locked for Forever - S30ROM"]
    #[inline(always)]
    pub fn s30rom(&self) -> S30ROM_R {
        S30ROM_R::new(((self.bits >> 30) & 1) != 0)
    }
    #[doc = "Bit 31 - PFLASH p Sector 31 Locked for Forever - S31ROM"]
    #[inline(always)]
    pub fn s31rom(&self) -> S31ROM_R {
        S31ROM_R::new(((self.bits >> 31) & 1) != 0)
    }
}
#[doc = "PFLASH Bank 0 OTP Protection Configuration 0\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [hp_proconotp00](index.html) module"]
pub struct HP_PROCONOTP00_SPEC;
impl crate::RegisterSpec for HP_PROCONOTP00_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [hp_proconotp00::R](R) reader structure"]
impl crate::Readable for HP_PROCONOTP00_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets HP_PROCONOTP00 to value 0"]
impl crate::Resettable for HP_PROCONOTP00_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
