// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `HP_PROCONOTP03` reader"]
pub struct R(crate::R<HP_PROCONOTP03_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<HP_PROCONOTP03_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<HP_PROCONOTP03_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<HP_PROCONOTP03_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `S96ROM` reader - PFLASH p Sector 96 Locked for Forever - S96ROM"]
pub type S96ROM_R = crate::BitReader<bool>;
#[doc = "Field `S97ROM` reader - PFLASH p Sector 97 Locked for Forever - S97ROM"]
pub type S97ROM_R = crate::BitReader<bool>;
#[doc = "Field `S98ROM` reader - PFLASH p Sector 98 Locked for Forever - S98ROM"]
pub type S98ROM_R = crate::BitReader<bool>;
#[doc = "Field `S99ROM` reader - PFLASH p Sector 99 Locked for Forever - S99ROM"]
pub type S99ROM_R = crate::BitReader<bool>;
#[doc = "Field `S100ROM` reader - PFLASH p Sector 100 Locked for Forever - S100ROM"]
pub type S100ROM_R = crate::BitReader<bool>;
#[doc = "Field `S101ROM` reader - PFLASH p Sector 101 Locked for Forever - S101ROM"]
pub type S101ROM_R = crate::BitReader<bool>;
#[doc = "Field `S102ROM` reader - PFLASH p Sector 102 Locked for Forever - S102ROM"]
pub type S102ROM_R = crate::BitReader<bool>;
#[doc = "Field `S103ROM` reader - PFLASH p Sector 103 Locked for Forever - S103ROM"]
pub type S103ROM_R = crate::BitReader<bool>;
#[doc = "Field `S104ROM` reader - PFLASH p Sector 104 Locked for Forever - S104ROM"]
pub type S104ROM_R = crate::BitReader<bool>;
#[doc = "Field `S105ROM` reader - PFLASH p Sector 105 Locked for Forever - S105ROM"]
pub type S105ROM_R = crate::BitReader<bool>;
#[doc = "Field `S106ROM` reader - PFLASH p Sector 106 Locked for Forever - S106ROM"]
pub type S106ROM_R = crate::BitReader<bool>;
#[doc = "Field `S107ROM` reader - PFLASH p Sector 107 Locked for Forever - S107ROM"]
pub type S107ROM_R = crate::BitReader<bool>;
#[doc = "Field `S108ROM` reader - PFLASH p Sector 108 Locked for Forever - S108ROM"]
pub type S108ROM_R = crate::BitReader<bool>;
#[doc = "Field `S109ROM` reader - PFLASH p Sector 109 Locked for Forever - S109ROM"]
pub type S109ROM_R = crate::BitReader<bool>;
#[doc = "Field `S110ROM` reader - PFLASH p Sector 110 Locked for Forever - S110ROM"]
pub type S110ROM_R = crate::BitReader<bool>;
#[doc = "Field `S111ROM` reader - PFLASH p Sector 111 Locked for Forever - S111ROM"]
pub type S111ROM_R = crate::BitReader<bool>;
#[doc = "Field `S112ROM` reader - PFLASH p Sector 112 Locked for Forever - S112ROM"]
pub type S112ROM_R = crate::BitReader<bool>;
#[doc = "Field `S113ROM` reader - PFLASH p Sector 113 Locked for Forever - S113ROM"]
pub type S113ROM_R = crate::BitReader<bool>;
#[doc = "Field `S114ROM` reader - PFLASH p Sector 114 Locked for Forever - S114ROM"]
pub type S114ROM_R = crate::BitReader<bool>;
#[doc = "Field `S115ROM` reader - PFLASH p Sector 115 Locked for Forever - S115ROM"]
pub type S115ROM_R = crate::BitReader<bool>;
#[doc = "Field `S116ROM` reader - PFLASH p Sector 116 Locked for Forever - S116ROM"]
pub type S116ROM_R = crate::BitReader<bool>;
#[doc = "Field `S117ROM` reader - PFLASH p Sector 117 Locked for Forever - S117ROM"]
pub type S117ROM_R = crate::BitReader<bool>;
#[doc = "Field `S118ROM` reader - PFLASH p Sector 118 Locked for Forever - S118ROM"]
pub type S118ROM_R = crate::BitReader<bool>;
#[doc = "Field `S119ROM` reader - PFLASH p Sector 119 Locked for Forever - S119ROM"]
pub type S119ROM_R = crate::BitReader<bool>;
#[doc = "Field `S120ROM` reader - PFLASH p Sector 120 Locked for Forever - S120ROM"]
pub type S120ROM_R = crate::BitReader<bool>;
#[doc = "Field `S121ROM` reader - PFLASH p Sector 121 Locked for Forever - S121ROM"]
pub type S121ROM_R = crate::BitReader<bool>;
#[doc = "Field `S122ROM` reader - PFLASH p Sector 122 Locked for Forever - S122ROM"]
pub type S122ROM_R = crate::BitReader<bool>;
#[doc = "Field `S123ROM` reader - PFLASH p Sector 123 Locked for Forever - S123ROM"]
pub type S123ROM_R = crate::BitReader<bool>;
#[doc = "Field `S124ROM` reader - PFLASH p Sector 124 Locked for Forever - S124ROM"]
pub type S124ROM_R = crate::BitReader<bool>;
#[doc = "Field `S125ROM` reader - PFLASH p Sector 125 Locked for Forever - S125ROM"]
pub type S125ROM_R = crate::BitReader<bool>;
#[doc = "Field `S126ROM` reader - PFLASH p Sector 126 Locked for Forever - S126ROM"]
pub type S126ROM_R = crate::BitReader<bool>;
#[doc = "Field `S127ROM` reader - PFLASH p Sector 127 Locked for Forever - S127ROM"]
pub type S127ROM_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bit 0 - PFLASH p Sector 96 Locked for Forever - S96ROM"]
    #[inline(always)]
    pub fn s96rom(&self) -> S96ROM_R {
        S96ROM_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - PFLASH p Sector 97 Locked for Forever - S97ROM"]
    #[inline(always)]
    pub fn s97rom(&self) -> S97ROM_R {
        S97ROM_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - PFLASH p Sector 98 Locked for Forever - S98ROM"]
    #[inline(always)]
    pub fn s98rom(&self) -> S98ROM_R {
        S98ROM_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - PFLASH p Sector 99 Locked for Forever - S99ROM"]
    #[inline(always)]
    pub fn s99rom(&self) -> S99ROM_R {
        S99ROM_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 4 - PFLASH p Sector 100 Locked for Forever - S100ROM"]
    #[inline(always)]
    pub fn s100rom(&self) -> S100ROM_R {
        S100ROM_R::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 5 - PFLASH p Sector 101 Locked for Forever - S101ROM"]
    #[inline(always)]
    pub fn s101rom(&self) -> S101ROM_R {
        S101ROM_R::new(((self.bits >> 5) & 1) != 0)
    }
    #[doc = "Bit 6 - PFLASH p Sector 102 Locked for Forever - S102ROM"]
    #[inline(always)]
    pub fn s102rom(&self) -> S102ROM_R {
        S102ROM_R::new(((self.bits >> 6) & 1) != 0)
    }
    #[doc = "Bit 7 - PFLASH p Sector 103 Locked for Forever - S103ROM"]
    #[inline(always)]
    pub fn s103rom(&self) -> S103ROM_R {
        S103ROM_R::new(((self.bits >> 7) & 1) != 0)
    }
    #[doc = "Bit 8 - PFLASH p Sector 104 Locked for Forever - S104ROM"]
    #[inline(always)]
    pub fn s104rom(&self) -> S104ROM_R {
        S104ROM_R::new(((self.bits >> 8) & 1) != 0)
    }
    #[doc = "Bit 9 - PFLASH p Sector 105 Locked for Forever - S105ROM"]
    #[inline(always)]
    pub fn s105rom(&self) -> S105ROM_R {
        S105ROM_R::new(((self.bits >> 9) & 1) != 0)
    }
    #[doc = "Bit 10 - PFLASH p Sector 106 Locked for Forever - S106ROM"]
    #[inline(always)]
    pub fn s106rom(&self) -> S106ROM_R {
        S106ROM_R::new(((self.bits >> 10) & 1) != 0)
    }
    #[doc = "Bit 11 - PFLASH p Sector 107 Locked for Forever - S107ROM"]
    #[inline(always)]
    pub fn s107rom(&self) -> S107ROM_R {
        S107ROM_R::new(((self.bits >> 11) & 1) != 0)
    }
    #[doc = "Bit 12 - PFLASH p Sector 108 Locked for Forever - S108ROM"]
    #[inline(always)]
    pub fn s108rom(&self) -> S108ROM_R {
        S108ROM_R::new(((self.bits >> 12) & 1) != 0)
    }
    #[doc = "Bit 13 - PFLASH p Sector 109 Locked for Forever - S109ROM"]
    #[inline(always)]
    pub fn s109rom(&self) -> S109ROM_R {
        S109ROM_R::new(((self.bits >> 13) & 1) != 0)
    }
    #[doc = "Bit 14 - PFLASH p Sector 110 Locked for Forever - S110ROM"]
    #[inline(always)]
    pub fn s110rom(&self) -> S110ROM_R {
        S110ROM_R::new(((self.bits >> 14) & 1) != 0)
    }
    #[doc = "Bit 15 - PFLASH p Sector 111 Locked for Forever - S111ROM"]
    #[inline(always)]
    pub fn s111rom(&self) -> S111ROM_R {
        S111ROM_R::new(((self.bits >> 15) & 1) != 0)
    }
    #[doc = "Bit 16 - PFLASH p Sector 112 Locked for Forever - S112ROM"]
    #[inline(always)]
    pub fn s112rom(&self) -> S112ROM_R {
        S112ROM_R::new(((self.bits >> 16) & 1) != 0)
    }
    #[doc = "Bit 17 - PFLASH p Sector 113 Locked for Forever - S113ROM"]
    #[inline(always)]
    pub fn s113rom(&self) -> S113ROM_R {
        S113ROM_R::new(((self.bits >> 17) & 1) != 0)
    }
    #[doc = "Bit 18 - PFLASH p Sector 114 Locked for Forever - S114ROM"]
    #[inline(always)]
    pub fn s114rom(&self) -> S114ROM_R {
        S114ROM_R::new(((self.bits >> 18) & 1) != 0)
    }
    #[doc = "Bit 19 - PFLASH p Sector 115 Locked for Forever - S115ROM"]
    #[inline(always)]
    pub fn s115rom(&self) -> S115ROM_R {
        S115ROM_R::new(((self.bits >> 19) & 1) != 0)
    }
    #[doc = "Bit 20 - PFLASH p Sector 116 Locked for Forever - S116ROM"]
    #[inline(always)]
    pub fn s116rom(&self) -> S116ROM_R {
        S116ROM_R::new(((self.bits >> 20) & 1) != 0)
    }
    #[doc = "Bit 21 - PFLASH p Sector 117 Locked for Forever - S117ROM"]
    #[inline(always)]
    pub fn s117rom(&self) -> S117ROM_R {
        S117ROM_R::new(((self.bits >> 21) & 1) != 0)
    }
    #[doc = "Bit 22 - PFLASH p Sector 118 Locked for Forever - S118ROM"]
    #[inline(always)]
    pub fn s118rom(&self) -> S118ROM_R {
        S118ROM_R::new(((self.bits >> 22) & 1) != 0)
    }
    #[doc = "Bit 23 - PFLASH p Sector 119 Locked for Forever - S119ROM"]
    #[inline(always)]
    pub fn s119rom(&self) -> S119ROM_R {
        S119ROM_R::new(((self.bits >> 23) & 1) != 0)
    }
    #[doc = "Bit 24 - PFLASH p Sector 120 Locked for Forever - S120ROM"]
    #[inline(always)]
    pub fn s120rom(&self) -> S120ROM_R {
        S120ROM_R::new(((self.bits >> 24) & 1) != 0)
    }
    #[doc = "Bit 25 - PFLASH p Sector 121 Locked for Forever - S121ROM"]
    #[inline(always)]
    pub fn s121rom(&self) -> S121ROM_R {
        S121ROM_R::new(((self.bits >> 25) & 1) != 0)
    }
    #[doc = "Bit 26 - PFLASH p Sector 122 Locked for Forever - S122ROM"]
    #[inline(always)]
    pub fn s122rom(&self) -> S122ROM_R {
        S122ROM_R::new(((self.bits >> 26) & 1) != 0)
    }
    #[doc = "Bit 27 - PFLASH p Sector 123 Locked for Forever - S123ROM"]
    #[inline(always)]
    pub fn s123rom(&self) -> S123ROM_R {
        S123ROM_R::new(((self.bits >> 27) & 1) != 0)
    }
    #[doc = "Bit 28 - PFLASH p Sector 124 Locked for Forever - S124ROM"]
    #[inline(always)]
    pub fn s124rom(&self) -> S124ROM_R {
        S124ROM_R::new(((self.bits >> 28) & 1) != 0)
    }
    #[doc = "Bit 29 - PFLASH p Sector 125 Locked for Forever - S125ROM"]
    #[inline(always)]
    pub fn s125rom(&self) -> S125ROM_R {
        S125ROM_R::new(((self.bits >> 29) & 1) != 0)
    }
    #[doc = "Bit 30 - PFLASH p Sector 126 Locked for Forever - S126ROM"]
    #[inline(always)]
    pub fn s126rom(&self) -> S126ROM_R {
        S126ROM_R::new(((self.bits >> 30) & 1) != 0)
    }
    #[doc = "Bit 31 - PFLASH p Sector 127 Locked for Forever - S127ROM"]
    #[inline(always)]
    pub fn s127rom(&self) -> S127ROM_R {
        S127ROM_R::new(((self.bits >> 31) & 1) != 0)
    }
}
#[doc = "PFLASH Bank 0 OTP Protection Configuration 3\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [hp_proconotp03](index.html) module"]
pub struct HP_PROCONOTP03_SPEC;
impl crate::RegisterSpec for HP_PROCONOTP03_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [hp_proconotp03::R](R) reader structure"]
impl crate::Readable for HP_PROCONOTP03_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets HP_PROCONOTP03 to value 0"]
impl crate::Resettable for HP_PROCONOTP03_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
