// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `SF_ECCS` reader"]
pub struct R(crate::R<SF_ECCS_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<SF_ECCS_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<SF_ECCS_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<SF_ECCS_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `ERR1` reader - Read Access Single Bit ECC Error - ERR1"]
pub type ERR1_R = crate::BitReader<bool>;
#[doc = "Field `ERR2` reader - Read Access Double Bit ECC Error - ERR2"]
pub type ERR2_R = crate::BitReader<bool>;
#[doc = "Field `ERR3` reader - Read Access Triple Bit ECC Error - ERR3"]
pub type ERR3_R = crate::BitReader<bool>;
#[doc = "Field `ERRM` reader - Read Access Multi-bit ECC Error - ERRM"]
pub type ERRM_R = crate::BitReader<bool>;
#[doc = "Field `ERRANY` reader - Any Read Access ECC Error - ERRANY"]
pub type ERRANY_R = crate::BitReader<bool>;
#[doc = "Field `BLANKA` reader - Read Access Blank Analog - BLANKA"]
pub type BLANKA_R = crate::BitReader<bool>;
#[doc = "Field `AER1` reader - Accumulated Single Bit ECC Errors - AER1"]
pub type AER1_R = crate::BitReader<bool>;
#[doc = "Field `AER2` reader - Accumulated Double Bit ECC Errors - AER2"]
pub type AER2_R = crate::BitReader<bool>;
#[doc = "Field `AER3` reader - Accumulated Triple Bit ECC Errors - AER3"]
pub type AER3_R = crate::BitReader<bool>;
#[doc = "Field `AERM` reader - Accumulated Multi-bit ECC Errors - AERM"]
pub type AERM_R = crate::BitReader<bool>;
#[doc = "Field `AERANY` reader - Accumulated Any Read Access ECC Error - AERANY"]
pub type AERANY_R = crate::BitReader<bool>;
#[doc = "Field `ABLANKA` reader - Accumulated Blank Analog - ABLANKA"]
pub type ABLANKA_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bit 0 - Read Access Single Bit ECC Error - ERR1"]
    #[inline(always)]
    pub fn err1(&self) -> ERR1_R {
        ERR1_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - Read Access Double Bit ECC Error - ERR2"]
    #[inline(always)]
    pub fn err2(&self) -> ERR2_R {
        ERR2_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - Read Access Triple Bit ECC Error - ERR3"]
    #[inline(always)]
    pub fn err3(&self) -> ERR3_R {
        ERR3_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - Read Access Multi-bit ECC Error - ERRM"]
    #[inline(always)]
    pub fn errm(&self) -> ERRM_R {
        ERRM_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 7 - Any Read Access ECC Error - ERRANY"]
    #[inline(always)]
    pub fn errany(&self) -> ERRANY_R {
        ERRANY_R::new(((self.bits >> 7) & 1) != 0)
    }
    #[doc = "Bit 9 - Read Access Blank Analog - BLANKA"]
    #[inline(always)]
    pub fn blanka(&self) -> BLANKA_R {
        BLANKA_R::new(((self.bits >> 9) & 1) != 0)
    }
    #[doc = "Bit 16 - Accumulated Single Bit ECC Errors - AER1"]
    #[inline(always)]
    pub fn aer1(&self) -> AER1_R {
        AER1_R::new(((self.bits >> 16) & 1) != 0)
    }
    #[doc = "Bit 17 - Accumulated Double Bit ECC Errors - AER2"]
    #[inline(always)]
    pub fn aer2(&self) -> AER2_R {
        AER2_R::new(((self.bits >> 17) & 1) != 0)
    }
    #[doc = "Bit 18 - Accumulated Triple Bit ECC Errors - AER3"]
    #[inline(always)]
    pub fn aer3(&self) -> AER3_R {
        AER3_R::new(((self.bits >> 18) & 1) != 0)
    }
    #[doc = "Bit 19 - Accumulated Multi-bit ECC Errors - AERM"]
    #[inline(always)]
    pub fn aerm(&self) -> AERM_R {
        AERM_R::new(((self.bits >> 19) & 1) != 0)
    }
    #[doc = "Bit 23 - Accumulated Any Read Access ECC Error - AERANY"]
    #[inline(always)]
    pub fn aerany(&self) -> AERANY_R {
        AERANY_R::new(((self.bits >> 23) & 1) != 0)
    }
    #[doc = "Bit 25 - Accumulated Blank Analog - ABLANKA"]
    #[inline(always)]
    pub fn ablanka(&self) -> ABLANKA_R {
        ABLANKA_R::new(((self.bits >> 25) & 1) != 0)
    }
}
#[doc = "HSM DF1 ECC Status Register\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [sf_eccs](index.html) module"]
pub struct SF_ECCS_SPEC;
impl crate::RegisterSpec for SF_ECCS_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [sf_eccs::R](R) reader structure"]
impl crate::Readable for SF_ECCS_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets SF_ECCS to value 0"]
impl crate::Resettable for SF_ECCS_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
