// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `SF_ERRSR` reader"]
pub struct R(crate::R<SF_ERRSR_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<SF_ERRSR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<SF_ERRSR_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<SF_ERRSR_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Field `OPER` reader - Flash Operation Error - OPER"]
pub type OPER_R = crate::BitReader<bool>;
#[doc = "Field `SQER` reader - Command Sequence Error - SQER"]
pub type SQER_R = crate::BitReader<bool>;
#[doc = "Field `PVER` reader - Program Verify Error - PVER"]
pub type PVER_R = crate::BitReader<bool>;
#[doc = "Field `EVER` reader - Erase Verify Error - EVER"]
pub type EVER_R = crate::BitReader<bool>;
impl R {
    #[doc = "Bit 0 - Flash Operation Error - OPER"]
    #[inline(always)]
    pub fn oper(&self) -> OPER_R {
        OPER_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - Command Sequence Error - SQER"]
    #[inline(always)]
    pub fn sqer(&self) -> SQER_R {
        SQER_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 3 - Program Verify Error - PVER"]
    #[inline(always)]
    pub fn pver(&self) -> PVER_R {
        PVER_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 4 - Erase Verify Error - EVER"]
    #[inline(always)]
    pub fn ever(&self) -> EVER_R {
        EVER_R::new(((self.bits >> 4) & 1) != 0)
    }
}
#[doc = "HSM Error Status Register\n\nThis register you can [`read`](crate::generic::Reg::read). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [sf_errsr](index.html) module"]
pub struct SF_ERRSR_SPEC;
impl crate::RegisterSpec for SF_ERRSR_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [sf_errsr::R](R) reader structure"]
impl crate::Readable for SF_ERRSR_SPEC {
    type Reader = R;
}
#[doc = "`reset()` method sets SF_ERRSR to value 0"]
impl crate::Resettable for SF_ERRSR_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
