// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `AG11FSP` reader"]
pub struct R(crate::R<AG11FSP_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<AG11FSP_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<AG11FSP_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<AG11FSP_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `AG11FSP` writer"]
pub struct W(crate::W<AG11FSP_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<AG11FSP_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<AG11FSP_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<AG11FSP_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `FE0` reader - Fault signaling configuration flag for alarm 0 belonging to alarm group i. - FE0"]
pub type FE0_R = crate::BitReader<bool>;
#[doc = "Field `FE0` writer - Fault signaling configuration flag for alarm 0 belonging to alarm group i. - FE0"]
pub type FE0_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG11FSP_SPEC, bool, O>;
#[doc = "Field `FE1` reader - Fault signaling configuration flag for alarm 1 belonging to alarm group i. - FE1"]
pub type FE1_R = crate::BitReader<bool>;
#[doc = "Field `FE1` writer - Fault signaling configuration flag for alarm 1 belonging to alarm group i. - FE1"]
pub type FE1_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG11FSP_SPEC, bool, O>;
#[doc = "Field `FE2` reader - Fault signaling configuration flag for alarm 2 belonging to alarm group i. - FE2"]
pub type FE2_R = crate::BitReader<bool>;
#[doc = "Field `FE2` writer - Fault signaling configuration flag for alarm 2 belonging to alarm group i. - FE2"]
pub type FE2_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG11FSP_SPEC, bool, O>;
#[doc = "Field `FE3` reader - Fault signaling configuration flag for alarm 3 belonging to alarm group i. - FE3"]
pub type FE3_R = crate::BitReader<bool>;
#[doc = "Field `FE3` writer - Fault signaling configuration flag for alarm 3 belonging to alarm group i. - FE3"]
pub type FE3_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG11FSP_SPEC, bool, O>;
#[doc = "Field `FE4` reader - Fault signaling configuration flag for alarm 4 belonging to alarm group i. - FE4"]
pub type FE4_R = crate::BitReader<bool>;
#[doc = "Field `FE4` writer - Fault signaling configuration flag for alarm 4 belonging to alarm group i. - FE4"]
pub type FE4_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG11FSP_SPEC, bool, O>;
#[doc = "Field `FE5` reader - Fault signaling configuration flag for alarm 5 belonging to alarm group i. - FE5"]
pub type FE5_R = crate::BitReader<bool>;
#[doc = "Field `FE5` writer - Fault signaling configuration flag for alarm 5 belonging to alarm group i. - FE5"]
pub type FE5_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG11FSP_SPEC, bool, O>;
#[doc = "Field `FE8` reader - Fault signaling configuration flag for alarm 8 belonging to alarm group i. - FE8"]
pub type FE8_R = crate::BitReader<bool>;
#[doc = "Field `FE8` writer - Fault signaling configuration flag for alarm 8 belonging to alarm group i. - FE8"]
pub type FE8_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG11FSP_SPEC, bool, O>;
#[doc = "Field `FE9` reader - Fault signaling configuration flag for alarm 9 belonging to alarm group i. - FE9"]
pub type FE9_R = crate::BitReader<bool>;
#[doc = "Field `FE9` writer - Fault signaling configuration flag for alarm 9 belonging to alarm group i. - FE9"]
pub type FE9_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG11FSP_SPEC, bool, O>;
#[doc = "Field `FE10` reader - Fault signaling configuration flag for alarm 10 belonging to alarm group i. - FE10"]
pub type FE10_R = crate::BitReader<bool>;
#[doc = "Field `FE10` writer - Fault signaling configuration flag for alarm 10 belonging to alarm group i. - FE10"]
pub type FE10_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG11FSP_SPEC, bool, O>;
#[doc = "Field `FE12` reader - Fault signaling configuration flag for alarm 12 belonging to alarm group i. - FE12"]
pub type FE12_R = crate::BitReader<bool>;
#[doc = "Field `FE12` writer - Fault signaling configuration flag for alarm 12 belonging to alarm group i. - FE12"]
pub type FE12_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG11FSP_SPEC, bool, O>;
#[doc = "Field `FE13` reader - Fault signaling configuration flag for alarm 13 belonging to alarm group i. - FE13"]
pub type FE13_R = crate::BitReader<bool>;
#[doc = "Field `FE13` writer - Fault signaling configuration flag for alarm 13 belonging to alarm group i. - FE13"]
pub type FE13_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG11FSP_SPEC, bool, O>;
impl R {
    #[doc = "Bit 0 - Fault signaling configuration flag for alarm 0 belonging to alarm group i. - FE0"]
    #[inline(always)]
    pub fn fe0(&self) -> FE0_R {
        FE0_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - Fault signaling configuration flag for alarm 1 belonging to alarm group i. - FE1"]
    #[inline(always)]
    pub fn fe1(&self) -> FE1_R {
        FE1_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - Fault signaling configuration flag for alarm 2 belonging to alarm group i. - FE2"]
    #[inline(always)]
    pub fn fe2(&self) -> FE2_R {
        FE2_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - Fault signaling configuration flag for alarm 3 belonging to alarm group i. - FE3"]
    #[inline(always)]
    pub fn fe3(&self) -> FE3_R {
        FE3_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 4 - Fault signaling configuration flag for alarm 4 belonging to alarm group i. - FE4"]
    #[inline(always)]
    pub fn fe4(&self) -> FE4_R {
        FE4_R::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 5 - Fault signaling configuration flag for alarm 5 belonging to alarm group i. - FE5"]
    #[inline(always)]
    pub fn fe5(&self) -> FE5_R {
        FE5_R::new(((self.bits >> 5) & 1) != 0)
    }
    #[doc = "Bit 8 - Fault signaling configuration flag for alarm 8 belonging to alarm group i. - FE8"]
    #[inline(always)]
    pub fn fe8(&self) -> FE8_R {
        FE8_R::new(((self.bits >> 8) & 1) != 0)
    }
    #[doc = "Bit 9 - Fault signaling configuration flag for alarm 9 belonging to alarm group i. - FE9"]
    #[inline(always)]
    pub fn fe9(&self) -> FE9_R {
        FE9_R::new(((self.bits >> 9) & 1) != 0)
    }
    #[doc = "Bit 10 - Fault signaling configuration flag for alarm 10 belonging to alarm group i. - FE10"]
    #[inline(always)]
    pub fn fe10(&self) -> FE10_R {
        FE10_R::new(((self.bits >> 10) & 1) != 0)
    }
    #[doc = "Bit 12 - Fault signaling configuration flag for alarm 12 belonging to alarm group i. - FE12"]
    #[inline(always)]
    pub fn fe12(&self) -> FE12_R {
        FE12_R::new(((self.bits >> 12) & 1) != 0)
    }
    #[doc = "Bit 13 - Fault signaling configuration flag for alarm 13 belonging to alarm group i. - FE13"]
    #[inline(always)]
    pub fn fe13(&self) -> FE13_R {
        FE13_R::new(((self.bits >> 13) & 1) != 0)
    }
}
impl W {
    #[doc = "Bit 0 - Fault signaling configuration flag for alarm 0 belonging to alarm group i. - FE0"]
    #[inline(always)]
    #[must_use]
    pub fn fe0(&mut self) -> FE0_W<0> {
        FE0_W::new(self)
    }
    #[doc = "Bit 1 - Fault signaling configuration flag for alarm 1 belonging to alarm group i. - FE1"]
    #[inline(always)]
    #[must_use]
    pub fn fe1(&mut self) -> FE1_W<1> {
        FE1_W::new(self)
    }
    #[doc = "Bit 2 - Fault signaling configuration flag for alarm 2 belonging to alarm group i. - FE2"]
    #[inline(always)]
    #[must_use]
    pub fn fe2(&mut self) -> FE2_W<2> {
        FE2_W::new(self)
    }
    #[doc = "Bit 3 - Fault signaling configuration flag for alarm 3 belonging to alarm group i. - FE3"]
    #[inline(always)]
    #[must_use]
    pub fn fe3(&mut self) -> FE3_W<3> {
        FE3_W::new(self)
    }
    #[doc = "Bit 4 - Fault signaling configuration flag for alarm 4 belonging to alarm group i. - FE4"]
    #[inline(always)]
    #[must_use]
    pub fn fe4(&mut self) -> FE4_W<4> {
        FE4_W::new(self)
    }
    #[doc = "Bit 5 - Fault signaling configuration flag for alarm 5 belonging to alarm group i. - FE5"]
    #[inline(always)]
    #[must_use]
    pub fn fe5(&mut self) -> FE5_W<5> {
        FE5_W::new(self)
    }
    #[doc = "Bit 8 - Fault signaling configuration flag for alarm 8 belonging to alarm group i. - FE8"]
    #[inline(always)]
    #[must_use]
    pub fn fe8(&mut self) -> FE8_W<8> {
        FE8_W::new(self)
    }
    #[doc = "Bit 9 - Fault signaling configuration flag for alarm 9 belonging to alarm group i. - FE9"]
    #[inline(always)]
    #[must_use]
    pub fn fe9(&mut self) -> FE9_W<9> {
        FE9_W::new(self)
    }
    #[doc = "Bit 10 - Fault signaling configuration flag for alarm 10 belonging to alarm group i. - FE10"]
    #[inline(always)]
    #[must_use]
    pub fn fe10(&mut self) -> FE10_W<10> {
        FE10_W::new(self)
    }
    #[doc = "Bit 12 - Fault signaling configuration flag for alarm 12 belonging to alarm group i. - FE12"]
    #[inline(always)]
    #[must_use]
    pub fn fe12(&mut self) -> FE12_W<12> {
        FE12_W::new(self)
    }
    #[doc = "Bit 13 - Fault signaling configuration flag for alarm 13 belonging to alarm group i. - FE13"]
    #[inline(always)]
    #[must_use]
    pub fn fe13(&mut self) -> FE13_W<13> {
        FE13_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "SMU_core FSP Configuration Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [ag11fsp](index.html) module"]
pub struct AG11FSP_SPEC;
impl crate::RegisterSpec for AG11FSP_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [ag11fsp::R](R) reader structure"]
impl crate::Readable for AG11FSP_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [ag11fsp::W](W) writer structure"]
impl crate::Writable for AG11FSP_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets AG11FSP to value 0"]
impl crate::Resettable for AG11FSP_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
