// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = "Register `AG7FSP` reader"]
pub struct R(crate::R<AG7FSP_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<AG7FSP_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<AG7FSP_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<AG7FSP_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `AG7FSP` writer"]
pub struct W(crate::W<AG7FSP_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<AG7FSP_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<AG7FSP_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<AG7FSP_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `FE0` reader - Fault signaling configuration flag for alarm 0 belonging to alarm group i. - FE0"]
pub type FE0_R = crate::BitReader<bool>;
#[doc = "Field `FE0` writer - Fault signaling configuration flag for alarm 0 belonging to alarm group i. - FE0"]
pub type FE0_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE1` reader - Fault signaling configuration flag for alarm 1 belonging to alarm group i. - FE1"]
pub type FE1_R = crate::BitReader<bool>;
#[doc = "Field `FE1` writer - Fault signaling configuration flag for alarm 1 belonging to alarm group i. - FE1"]
pub type FE1_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE2` reader - Fault signaling configuration flag for alarm 2 belonging to alarm group i. - FE2"]
pub type FE2_R = crate::BitReader<bool>;
#[doc = "Field `FE2` writer - Fault signaling configuration flag for alarm 2 belonging to alarm group i. - FE2"]
pub type FE2_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE12` reader - Fault signaling configuration flag for alarm 12 belonging to alarm group i. - FE12"]
pub type FE12_R = crate::BitReader<bool>;
#[doc = "Field `FE12` writer - Fault signaling configuration flag for alarm 12 belonging to alarm group i. - FE12"]
pub type FE12_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE13` reader - Fault signaling configuration flag for alarm 13 belonging to alarm group i. - FE13"]
pub type FE13_R = crate::BitReader<bool>;
#[doc = "Field `FE13` writer - Fault signaling configuration flag for alarm 13 belonging to alarm group i. - FE13"]
pub type FE13_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE14` reader - Fault signaling configuration flag for alarm 14 belonging to alarm group i. - FE14"]
pub type FE14_R = crate::BitReader<bool>;
#[doc = "Field `FE14` writer - Fault signaling configuration flag for alarm 14 belonging to alarm group i. - FE14"]
pub type FE14_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE15` reader - Fault signaling configuration flag for alarm 15 belonging to alarm group i. - FE15"]
pub type FE15_R = crate::BitReader<bool>;
#[doc = "Field `FE15` writer - Fault signaling configuration flag for alarm 15 belonging to alarm group i. - FE15"]
pub type FE15_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE16` reader - Fault signaling configuration flag for alarm 16 belonging to alarm group i. - FE16"]
pub type FE16_R = crate::BitReader<bool>;
#[doc = "Field `FE16` writer - Fault signaling configuration flag for alarm 16 belonging to alarm group i. - FE16"]
pub type FE16_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE17` reader - Fault signaling configuration flag for alarm 17 belonging to alarm group i. - FE17"]
pub type FE17_R = crate::BitReader<bool>;
#[doc = "Field `FE17` writer - Fault signaling configuration flag for alarm 17 belonging to alarm group i. - FE17"]
pub type FE17_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE18` reader - Fault signaling configuration flag for alarm 18 belonging to alarm group i. - FE18"]
pub type FE18_R = crate::BitReader<bool>;
#[doc = "Field `FE18` writer - Fault signaling configuration flag for alarm 18 belonging to alarm group i. - FE18"]
pub type FE18_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE19` reader - Fault signaling configuration flag for alarm 19 belonging to alarm group i. - FE19"]
pub type FE19_R = crate::BitReader<bool>;
#[doc = "Field `FE19` writer - Fault signaling configuration flag for alarm 19 belonging to alarm group i. - FE19"]
pub type FE19_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE20` reader - Fault signaling configuration flag for alarm 20 belonging to alarm group i. - FE20"]
pub type FE20_R = crate::BitReader<bool>;
#[doc = "Field `FE20` writer - Fault signaling configuration flag for alarm 20 belonging to alarm group i. - FE20"]
pub type FE20_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE22` reader - Fault signaling configuration flag for alarm 22 belonging to alarm group i. - FE22"]
pub type FE22_R = crate::BitReader<bool>;
#[doc = "Field `FE22` writer - Fault signaling configuration flag for alarm 22 belonging to alarm group i. - FE22"]
pub type FE22_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE23` reader - Fault signaling configuration flag for alarm 23 belonging to alarm group i. - FE23"]
pub type FE23_R = crate::BitReader<bool>;
#[doc = "Field `FE23` writer - Fault signaling configuration flag for alarm 23 belonging to alarm group i. - FE23"]
pub type FE23_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE24` reader - Fault signaling configuration flag for alarm 24 belonging to alarm group i. - FE24"]
pub type FE24_R = crate::BitReader<bool>;
#[doc = "Field `FE24` writer - Fault signaling configuration flag for alarm 24 belonging to alarm group i. - FE24"]
pub type FE24_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE25` reader - Fault signaling configuration flag for alarm 25 belonging to alarm group i. - FE25"]
pub type FE25_R = crate::BitReader<bool>;
#[doc = "Field `FE25` writer - Fault signaling configuration flag for alarm 25 belonging to alarm group i. - FE25"]
pub type FE25_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE26` reader - Fault signaling configuration flag for alarm 26 belonging to alarm group i. - FE26"]
pub type FE26_R = crate::BitReader<bool>;
#[doc = "Field `FE26` writer - Fault signaling configuration flag for alarm 26 belonging to alarm group i. - FE26"]
pub type FE26_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE27` reader - Fault signaling configuration flag for alarm 27 belonging to alarm group i. - FE27"]
pub type FE27_R = crate::BitReader<bool>;
#[doc = "Field `FE27` writer - Fault signaling configuration flag for alarm 27 belonging to alarm group i. - FE27"]
pub type FE27_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE28` reader - Fault signaling configuration flag for alarm 28 belonging to alarm group i. - FE28"]
pub type FE28_R = crate::BitReader<bool>;
#[doc = "Field `FE28` writer - Fault signaling configuration flag for alarm 28 belonging to alarm group i. - FE28"]
pub type FE28_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE29` reader - Fault signaling configuration flag for alarm 29 belonging to alarm group i. - FE29"]
pub type FE29_R = crate::BitReader<bool>;
#[doc = "Field `FE29` writer - Fault signaling configuration flag for alarm 29 belonging to alarm group i. - FE29"]
pub type FE29_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE30` reader - Fault signaling configuration flag for alarm 30 belonging to alarm group i. - FE30"]
pub type FE30_R = crate::BitReader<bool>;
#[doc = "Field `FE30` writer - Fault signaling configuration flag for alarm 30 belonging to alarm group i. - FE30"]
pub type FE30_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
#[doc = "Field `FE31` reader - Fault signaling configuration flag for alarm 31 belonging to alarm group i. - FE31"]
pub type FE31_R = crate::BitReader<bool>;
#[doc = "Field `FE31` writer - Fault signaling configuration flag for alarm 31 belonging to alarm group i. - FE31"]
pub type FE31_W<'a, const O: u8> = crate::BitWriter<'a, u32, AG7FSP_SPEC, bool, O>;
impl R {
    #[doc = "Bit 0 - Fault signaling configuration flag for alarm 0 belonging to alarm group i. - FE0"]
    #[inline(always)]
    pub fn fe0(&self) -> FE0_R {
        FE0_R::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - Fault signaling configuration flag for alarm 1 belonging to alarm group i. - FE1"]
    #[inline(always)]
    pub fn fe1(&self) -> FE1_R {
        FE1_R::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bit 2 - Fault signaling configuration flag for alarm 2 belonging to alarm group i. - FE2"]
    #[inline(always)]
    pub fn fe2(&self) -> FE2_R {
        FE2_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 12 - Fault signaling configuration flag for alarm 12 belonging to alarm group i. - FE12"]
    #[inline(always)]
    pub fn fe12(&self) -> FE12_R {
        FE12_R::new(((self.bits >> 12) & 1) != 0)
    }
    #[doc = "Bit 13 - Fault signaling configuration flag for alarm 13 belonging to alarm group i. - FE13"]
    #[inline(always)]
    pub fn fe13(&self) -> FE13_R {
        FE13_R::new(((self.bits >> 13) & 1) != 0)
    }
    #[doc = "Bit 14 - Fault signaling configuration flag for alarm 14 belonging to alarm group i. - FE14"]
    #[inline(always)]
    pub fn fe14(&self) -> FE14_R {
        FE14_R::new(((self.bits >> 14) & 1) != 0)
    }
    #[doc = "Bit 15 - Fault signaling configuration flag for alarm 15 belonging to alarm group i. - FE15"]
    #[inline(always)]
    pub fn fe15(&self) -> FE15_R {
        FE15_R::new(((self.bits >> 15) & 1) != 0)
    }
    #[doc = "Bit 16 - Fault signaling configuration flag for alarm 16 belonging to alarm group i. - FE16"]
    #[inline(always)]
    pub fn fe16(&self) -> FE16_R {
        FE16_R::new(((self.bits >> 16) & 1) != 0)
    }
    #[doc = "Bit 17 - Fault signaling configuration flag for alarm 17 belonging to alarm group i. - FE17"]
    #[inline(always)]
    pub fn fe17(&self) -> FE17_R {
        FE17_R::new(((self.bits >> 17) & 1) != 0)
    }
    #[doc = "Bit 18 - Fault signaling configuration flag for alarm 18 belonging to alarm group i. - FE18"]
    #[inline(always)]
    pub fn fe18(&self) -> FE18_R {
        FE18_R::new(((self.bits >> 18) & 1) != 0)
    }
    #[doc = "Bit 19 - Fault signaling configuration flag for alarm 19 belonging to alarm group i. - FE19"]
    #[inline(always)]
    pub fn fe19(&self) -> FE19_R {
        FE19_R::new(((self.bits >> 19) & 1) != 0)
    }
    #[doc = "Bit 20 - Fault signaling configuration flag for alarm 20 belonging to alarm group i. - FE20"]
    #[inline(always)]
    pub fn fe20(&self) -> FE20_R {
        FE20_R::new(((self.bits >> 20) & 1) != 0)
    }
    #[doc = "Bit 22 - Fault signaling configuration flag for alarm 22 belonging to alarm group i. - FE22"]
    #[inline(always)]
    pub fn fe22(&self) -> FE22_R {
        FE22_R::new(((self.bits >> 22) & 1) != 0)
    }
    #[doc = "Bit 23 - Fault signaling configuration flag for alarm 23 belonging to alarm group i. - FE23"]
    #[inline(always)]
    pub fn fe23(&self) -> FE23_R {
        FE23_R::new(((self.bits >> 23) & 1) != 0)
    }
    #[doc = "Bit 24 - Fault signaling configuration flag for alarm 24 belonging to alarm group i. - FE24"]
    #[inline(always)]
    pub fn fe24(&self) -> FE24_R {
        FE24_R::new(((self.bits >> 24) & 1) != 0)
    }
    #[doc = "Bit 25 - Fault signaling configuration flag for alarm 25 belonging to alarm group i. - FE25"]
    #[inline(always)]
    pub fn fe25(&self) -> FE25_R {
        FE25_R::new(((self.bits >> 25) & 1) != 0)
    }
    #[doc = "Bit 26 - Fault signaling configuration flag for alarm 26 belonging to alarm group i. - FE26"]
    #[inline(always)]
    pub fn fe26(&self) -> FE26_R {
        FE26_R::new(((self.bits >> 26) & 1) != 0)
    }
    #[doc = "Bit 27 - Fault signaling configuration flag for alarm 27 belonging to alarm group i. - FE27"]
    #[inline(always)]
    pub fn fe27(&self) -> FE27_R {
        FE27_R::new(((self.bits >> 27) & 1) != 0)
    }
    #[doc = "Bit 28 - Fault signaling configuration flag for alarm 28 belonging to alarm group i. - FE28"]
    #[inline(always)]
    pub fn fe28(&self) -> FE28_R {
        FE28_R::new(((self.bits >> 28) & 1) != 0)
    }
    #[doc = "Bit 29 - Fault signaling configuration flag for alarm 29 belonging to alarm group i. - FE29"]
    #[inline(always)]
    pub fn fe29(&self) -> FE29_R {
        FE29_R::new(((self.bits >> 29) & 1) != 0)
    }
    #[doc = "Bit 30 - Fault signaling configuration flag for alarm 30 belonging to alarm group i. - FE30"]
    #[inline(always)]
    pub fn fe30(&self) -> FE30_R {
        FE30_R::new(((self.bits >> 30) & 1) != 0)
    }
    #[doc = "Bit 31 - Fault signaling configuration flag for alarm 31 belonging to alarm group i. - FE31"]
    #[inline(always)]
    pub fn fe31(&self) -> FE31_R {
        FE31_R::new(((self.bits >> 31) & 1) != 0)
    }
}
impl W {
    #[doc = "Bit 0 - Fault signaling configuration flag for alarm 0 belonging to alarm group i. - FE0"]
    #[inline(always)]
    #[must_use]
    pub fn fe0(&mut self) -> FE0_W<0> {
        FE0_W::new(self)
    }
    #[doc = "Bit 1 - Fault signaling configuration flag for alarm 1 belonging to alarm group i. - FE1"]
    #[inline(always)]
    #[must_use]
    pub fn fe1(&mut self) -> FE1_W<1> {
        FE1_W::new(self)
    }
    #[doc = "Bit 2 - Fault signaling configuration flag for alarm 2 belonging to alarm group i. - FE2"]
    #[inline(always)]
    #[must_use]
    pub fn fe2(&mut self) -> FE2_W<2> {
        FE2_W::new(self)
    }
    #[doc = "Bit 12 - Fault signaling configuration flag for alarm 12 belonging to alarm group i. - FE12"]
    #[inline(always)]
    #[must_use]
    pub fn fe12(&mut self) -> FE12_W<12> {
        FE12_W::new(self)
    }
    #[doc = "Bit 13 - Fault signaling configuration flag for alarm 13 belonging to alarm group i. - FE13"]
    #[inline(always)]
    #[must_use]
    pub fn fe13(&mut self) -> FE13_W<13> {
        FE13_W::new(self)
    }
    #[doc = "Bit 14 - Fault signaling configuration flag for alarm 14 belonging to alarm group i. - FE14"]
    #[inline(always)]
    #[must_use]
    pub fn fe14(&mut self) -> FE14_W<14> {
        FE14_W::new(self)
    }
    #[doc = "Bit 15 - Fault signaling configuration flag for alarm 15 belonging to alarm group i. - FE15"]
    #[inline(always)]
    #[must_use]
    pub fn fe15(&mut self) -> FE15_W<15> {
        FE15_W::new(self)
    }
    #[doc = "Bit 16 - Fault signaling configuration flag for alarm 16 belonging to alarm group i. - FE16"]
    #[inline(always)]
    #[must_use]
    pub fn fe16(&mut self) -> FE16_W<16> {
        FE16_W::new(self)
    }
    #[doc = "Bit 17 - Fault signaling configuration flag for alarm 17 belonging to alarm group i. - FE17"]
    #[inline(always)]
    #[must_use]
    pub fn fe17(&mut self) -> FE17_W<17> {
        FE17_W::new(self)
    }
    #[doc = "Bit 18 - Fault signaling configuration flag for alarm 18 belonging to alarm group i. - FE18"]
    #[inline(always)]
    #[must_use]
    pub fn fe18(&mut self) -> FE18_W<18> {
        FE18_W::new(self)
    }
    #[doc = "Bit 19 - Fault signaling configuration flag for alarm 19 belonging to alarm group i. - FE19"]
    #[inline(always)]
    #[must_use]
    pub fn fe19(&mut self) -> FE19_W<19> {
        FE19_W::new(self)
    }
    #[doc = "Bit 20 - Fault signaling configuration flag for alarm 20 belonging to alarm group i. - FE20"]
    #[inline(always)]
    #[must_use]
    pub fn fe20(&mut self) -> FE20_W<20> {
        FE20_W::new(self)
    }
    #[doc = "Bit 22 - Fault signaling configuration flag for alarm 22 belonging to alarm group i. - FE22"]
    #[inline(always)]
    #[must_use]
    pub fn fe22(&mut self) -> FE22_W<22> {
        FE22_W::new(self)
    }
    #[doc = "Bit 23 - Fault signaling configuration flag for alarm 23 belonging to alarm group i. - FE23"]
    #[inline(always)]
    #[must_use]
    pub fn fe23(&mut self) -> FE23_W<23> {
        FE23_W::new(self)
    }
    #[doc = "Bit 24 - Fault signaling configuration flag for alarm 24 belonging to alarm group i. - FE24"]
    #[inline(always)]
    #[must_use]
    pub fn fe24(&mut self) -> FE24_W<24> {
        FE24_W::new(self)
    }
    #[doc = "Bit 25 - Fault signaling configuration flag for alarm 25 belonging to alarm group i. - FE25"]
    #[inline(always)]
    #[must_use]
    pub fn fe25(&mut self) -> FE25_W<25> {
        FE25_W::new(self)
    }
    #[doc = "Bit 26 - Fault signaling configuration flag for alarm 26 belonging to alarm group i. - FE26"]
    #[inline(always)]
    #[must_use]
    pub fn fe26(&mut self) -> FE26_W<26> {
        FE26_W::new(self)
    }
    #[doc = "Bit 27 - Fault signaling configuration flag for alarm 27 belonging to alarm group i. - FE27"]
    #[inline(always)]
    #[must_use]
    pub fn fe27(&mut self) -> FE27_W<27> {
        FE27_W::new(self)
    }
    #[doc = "Bit 28 - Fault signaling configuration flag for alarm 28 belonging to alarm group i. - FE28"]
    #[inline(always)]
    #[must_use]
    pub fn fe28(&mut self) -> FE28_W<28> {
        FE28_W::new(self)
    }
    #[doc = "Bit 29 - Fault signaling configuration flag for alarm 29 belonging to alarm group i. - FE29"]
    #[inline(always)]
    #[must_use]
    pub fn fe29(&mut self) -> FE29_W<29> {
        FE29_W::new(self)
    }
    #[doc = "Bit 30 - Fault signaling configuration flag for alarm 30 belonging to alarm group i. - FE30"]
    #[inline(always)]
    #[must_use]
    pub fn fe30(&mut self) -> FE30_W<30> {
        FE30_W::new(self)
    }
    #[doc = "Bit 31 - Fault signaling configuration flag for alarm 31 belonging to alarm group i. - FE31"]
    #[inline(always)]
    #[must_use]
    pub fn fe31(&mut self) -> FE31_W<31> {
        FE31_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "SMU_core FSP Configuration Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [ag7fsp](index.html) module"]
pub struct AG7FSP_SPEC;
impl crate::RegisterSpec for AG7FSP_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [ag7fsp::R](R) reader structure"]
impl crate::Readable for AG7FSP_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [ag7fsp::W](W) writer structure"]
impl crate::Writable for AG7FSP_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets AG7FSP to value 0"]
impl crate::Resettable for AG7FSP_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
