// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = r"Register block"]
#[repr(C)]
pub struct RegisterBlock {
    #[doc = "0x00 - Clock Control Register"]
    pub clc: CLC,
    _reserved1: [u8; 0x04],
    #[doc = "0x08 - Module Identification Register"]
    pub id: ID,
    _reserved2: [u8; 0x1c],
    #[doc = "0x28 - OCDS Control and Status Register"]
    pub ocs: OCS,
    #[doc = "0x2c - Kernel Reset Status Clear Register"]
    pub krstclr: KRSTCLR,
    #[doc = "0x30 - Kernel Reset Register 1"]
    pub krst1: KRST1,
    #[doc = "0x34 - Kernel Reset Register 0"]
    pub krst0: KRST0,
    _reserved6: [u8; 0x04],
    #[doc = "0x3c - Access Enable Register 0"]
    pub accen0: ACCEN0,
    _reserved7: [u8; 0x3c],
    #[doc = "0x7c - Converter Control Block Control Register"]
    pub ccctrl: CCCTRL,
    #[doc = "0x80 - Phase Synchronizer Configuration Register"]
    pub phscfg: PHSCFG,
    #[doc = "0x84 - Phase Synchronizer Safety Control Register"]
    pub phssfty: PHSSFTY,
}
#[doc = "CLC (rw) register accessor: an alias for `Reg<CLC_SPEC>`"]
pub type CLC = crate::Reg<clc::CLC_SPEC>;
#[doc = "Clock Control Register"]
pub mod clc;
#[doc = "ID (r) register accessor: an alias for `Reg<ID_SPEC>`"]
pub type ID = crate::Reg<id::ID_SPEC>;
#[doc = "Module Identification Register"]
pub mod id;
#[doc = "OCS (rw) register accessor: an alias for `Reg<OCS_SPEC>`"]
pub type OCS = crate::Reg<ocs::OCS_SPEC>;
#[doc = "OCDS Control and Status Register"]
pub mod ocs;
#[doc = "KRSTCLR (w) register accessor: an alias for `Reg<KRSTCLR_SPEC>`"]
pub type KRSTCLR = crate::Reg<krstclr::KRSTCLR_SPEC>;
#[doc = "Kernel Reset Status Clear Register"]
pub mod krstclr;
#[doc = "KRST1 (rw) register accessor: an alias for `Reg<KRST1_SPEC>`"]
pub type KRST1 = crate::Reg<krst1::KRST1_SPEC>;
#[doc = "Kernel Reset Register 1"]
pub mod krst1;
#[doc = "KRST0 (rw) register accessor: an alias for `Reg<KRST0_SPEC>`"]
pub type KRST0 = crate::Reg<krst0::KRST0_SPEC>;
#[doc = "Kernel Reset Register 0"]
pub mod krst0;
#[doc = "ACCEN0 (rw) register accessor: an alias for `Reg<ACCEN0_SPEC>`"]
pub type ACCEN0 = crate::Reg<accen0::ACCEN0_SPEC>;
#[doc = "Access Enable Register 0"]
pub mod accen0;
#[doc = "CCCTRL (rw) register accessor: an alias for `Reg<CCCTRL_SPEC>`"]
pub type CCCTRL = crate::Reg<ccctrl::CCCTRL_SPEC>;
#[doc = "Converter Control Block Control Register"]
pub mod ccctrl;
#[doc = "PHSCFG (rw) register accessor: an alias for `Reg<PHSCFG_SPEC>`"]
pub type PHSCFG = crate::Reg<phscfg::PHSCFG_SPEC>;
#[doc = "Phase Synchronizer Configuration Register"]
pub mod phscfg;
#[doc = "PHSSFTY (rw) register accessor: an alias for `Reg<PHSSFTY_SPEC>`"]
pub type PHSSFTY = crate::Reg<phssfty::PHSSFTY_SPEC>;
#[doc = "Phase Synchronizer Safety Control Register"]
pub mod phssfty;
