// Copyright (c) 2023 HighTec EDV-Systeme GmbH. All rights reserved.
//
// Use of this file is subject to the Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#[doc = r"Register block"]
#[repr(C)]
pub struct RegisterBlock {
    _reserved0: [u8; 0x08],
    #[doc = "0x08 - Module Identification Register"]
    pub hf_id: HF_ID,
    _reserved1: [u8; 0x04],
    #[doc = "0x10 - Flash Status Register"]
    pub hf_status: HF_STATUS,
    #[doc = "0x14 - Flash Control Register"]
    pub hf_control: HF_CONTROL,
    #[doc = "0x18 - Flash Operation Register"]
    pub hf_operation: HF_OPERATION,
    #[doc = "0x1c - Flash Protection Status Register"]
    pub hf_protect: HF_PROTECT,
    #[doc = "0x20 - Flash Confirm Status Register 0"]
    pub hf_confirm0: HF_CONFIRM0,
    #[doc = "0x24 - Flash Confirm Status Register 1"]
    pub hf_confirm1: HF_CONFIRM1,
    #[doc = "0x28 - Flash Confirm Status Register 2"]
    pub hf_confirm2: HF_CONFIRM2,
    _reserved8: [u8; 0x04],
    #[doc = "0x30 - Enable Error Interrupt Control Register"]
    pub hf_eer: HF_EER,
    #[doc = "0x34 - Error Status Register"]
    pub hf_errsr: HF_ERRSR,
    #[doc = "0x38 - Clear Error Register"]
    pub hf_clre: HF_CLRE,
    _reserved11: [u8; 0x04],
    #[doc = "0x40 - DF0 ECC Read Register"]
    pub hf_eccr: HF_ECCR,
    #[doc = "0x44 - DF0 ECC Status Register"]
    pub hf_eccs: HF_ECCS,
    #[doc = "0x48 - DF0 ECC Control Register"]
    pub hf_eccc: HF_ECCC,
    #[doc = "0x4c - DF0 ECC Write Register"]
    pub hf_eccw: HF_ECCW,
    #[doc = "0x50 - Cranking Control Register"]
    pub hf_ccontrol: HF_CCONTROL,
    _reserved16: [u8; 0x0c],
    #[doc = "0x60 - Power Status Register"]
    pub hf_pstatus: HF_PSTATUS,
    #[doc = "0x64 - Power Control Register"]
    pub hf_pcontrol: HF_PCONTROL,
    #[doc = "0x68 - PFLASH Wait Cycle Register"]
    pub hf_pwait: HF_PWAIT,
    #[doc = "0x6c - DFLASH Wait Cycle Register"]
    pub hf_dwait: HF_DWAIT,
    _reserved20: [u8; 0x04],
    #[doc = "0x74 - DF0 User Mode Control"]
    pub hf_proconusr: HF_PROCONUSR,
    _reserved21: [u8; 0x08],
    #[doc = "0x80 - PFLASH Protection Configuration"]
    pub hf_proconpf: HF_PROCONPF,
    #[doc = "0x84 - Tuning Protection Configuration"]
    pub hf_procontp: HF_PROCONTP,
    #[doc = "0x88 - DFLASH Protection Configuration"]
    pub hf_procondf: HF_PROCONDF,
    #[doc = "0x8c - RAM Configuration"]
    pub hf_proconram: HF_PROCONRAM,
    #[doc = "0x90 - Debug Interface Protection Configuration"]
    pub hf_procondbg: HF_PROCONDBG,
    _reserved26: [u8; 0x5c],
    #[doc = "0xf0 - Suspend Control Register"]
    pub hf_suspend: HF_SUSPEND,
    #[doc = "0xf4 - Margin Control Register"]
    pub hf_margin: HF_MARGIN,
    #[doc = "0xf8 - Access Enable Register 1"]
    pub hf_accen1: HF_ACCEN1,
    #[doc = "0xfc - Access Enable Register 0"]
    pub hf_accen0: HF_ACCEN0,
    _reserved30: [u8; 0xff00],
    #[doc = "0x10000 - PFLASH Bank 0 Protection Configuration 0"]
    pub hp_proconp00: HP_PROCONP00,
    #[doc = "0x10004 - PFLASH Bank 0 Protection Configuration 1"]
    pub hp_proconp01: HP_PROCONP01,
    #[doc = "0x10008 - PFLASH Bank 0 Protection Configuration 2"]
    pub hp_proconp02: HP_PROCONP02,
    #[doc = "0x1000c - PFLASH Bank 0 Protection Configuration 3"]
    pub hp_proconp03: HP_PROCONP03,
    #[doc = "0x10010 - PFLASH Bank 0 Protection Configuration 4"]
    pub hp_proconp04: HP_PROCONP04,
    #[doc = "0x10014 - PFLASH Bank 0 Protection Configuration 5"]
    pub hp_proconp05: HP_PROCONP05,
    _reserved36: [u8; 0x28],
    #[doc = "0x10040 - PFLASH Bank 0 OTP Protection Configuration 0"]
    pub hp_proconotp00: HP_PROCONOTP00,
    #[doc = "0x10044 - PFLASH Bank 0 OTP Protection Configuration 1"]
    pub hp_proconotp01: HP_PROCONOTP01,
    #[doc = "0x10048 - PFLASH Bank 0 OTP Protection Configuration 2"]
    pub hp_proconotp02: HP_PROCONOTP02,
    #[doc = "0x1004c - PFLASH Bank 0 OTP Protection Configuration 3"]
    pub hp_proconotp03: HP_PROCONOTP03,
    #[doc = "0x10050 - PFLASH Bank 0 OTP Protection Configuration 4"]
    pub hp_proconotp04: HP_PROCONOTP04,
    #[doc = "0x10054 - PFLASH Bank 0 OTP Protection Configuration 5"]
    pub hp_proconotp05: HP_PROCONOTP05,
    _reserved42: [u8; 0x28],
    #[doc = "0x10080 - PFLASH Bank 0 WOP Configuration 0"]
    pub hp_proconwop00: HP_PROCONWOP00,
    #[doc = "0x10084 - PFLASH Bank 0 WOP Configuration 1"]
    pub hp_proconwop01: HP_PROCONWOP01,
    #[doc = "0x10088 - PFLASH Bank 0 WOP Configuration 2"]
    pub hp_proconwop02: HP_PROCONWOP02,
    #[doc = "0x1008c - PFLASH Bank 0 WOP Configuration 3"]
    pub hp_proconwop03: HP_PROCONWOP03,
    #[doc = "0x10090 - PFLASH Bank 0 WOP Configuration 4"]
    pub hp_proconwop04: HP_PROCONWOP04,
    #[doc = "0x10094 - PFLASH Bank 0 WOP Configuration 5"]
    pub hp_proconwop05: HP_PROCONWOP05,
    _reserved48: [u8; 0x08],
    #[doc = "0x100a0 - PFLASH Bank 0 Erase Counter Priority configuration 0"]
    pub hp_ecprio00: HP_ECPRIO00,
    #[doc = "0x100a4 - PFLASH Bank 0 Erase Counter Priority Configuration 1"]
    pub hp_ecprio01: HP_ECPRIO01,
    #[doc = "0x100a8 - PFLASH Bank 0 Erase Counter Priority Configuration 2"]
    pub hp_ecprio02: HP_ECPRIO02,
    #[doc = "0x100ac - PFLASH Bank 0 Erase Counter Priority Configuration 3"]
    pub hp_ecprio03: HP_ECPRIO03,
    #[doc = "0x100b0 - PFLASH Bank 0 Erase Counter Priority Configuration 4"]
    pub hp_ecprio04: HP_ECPRIO04,
    #[doc = "0x100b4 - PFLASH Bank 0 Erase Counter Priority Configuration 5"]
    pub hp_ecprio05: HP_ECPRIO05,
    _reserved54: [u8; 0x48],
    #[doc = "0x10100 - PFLASH Bank 1 Protection Configuration 0"]
    pub hp_proconp10: HP_PROCONP10,
    #[doc = "0x10104 - PFLASH Bank 1 Protection Configuration 1"]
    pub hp_proconp11: HP_PROCONP11,
    #[doc = "0x10108 - PFLASH Bank 1 Protection Configuration 2"]
    pub hp_proconp12: HP_PROCONP12,
    #[doc = "0x1010c - PFLASH Bank 1 Protection Configuration 3"]
    pub hp_proconp13: HP_PROCONP13,
    #[doc = "0x10110 - PFLASH Bank 1 Protection Configuration 4"]
    pub hp_proconp14: HP_PROCONP14,
    #[doc = "0x10114 - PFLASH Bank 1 Protection Configuration 5"]
    pub hp_proconp15: HP_PROCONP15,
    _reserved60: [u8; 0x28],
    #[doc = "0x10140 - PFLASH Bank 1 OTP Protection Configuration 0"]
    pub hp_proconotp10: HP_PROCONOTP10,
    #[doc = "0x10144 - PFLASH Bank 1 OTP Protection Configuration 1"]
    pub hp_proconotp11: HP_PROCONOTP11,
    #[doc = "0x10148 - PFLASH Bank 1 OTP Protection Configuration 2"]
    pub hp_proconotp12: HP_PROCONOTP12,
    #[doc = "0x1014c - PFLASH Bank 1 OTP Protection Configuration 3"]
    pub hp_proconotp13: HP_PROCONOTP13,
    #[doc = "0x10150 - PFLASH Bank 1 OTP Protection Configuration 4"]
    pub hp_proconotp14: HP_PROCONOTP14,
    #[doc = "0x10154 - PFLASH Bank 1 OTP Protection Configuration 5"]
    pub hp_proconotp15: HP_PROCONOTP15,
    _reserved66: [u8; 0x28],
    #[doc = "0x10180 - PFLASH Bank 1 WOP Configuration 0"]
    pub hp_proconwop10: HP_PROCONWOP10,
    #[doc = "0x10184 - PFLASH Bank 1 WOP Configuration 1"]
    pub hp_proconwop11: HP_PROCONWOP11,
    #[doc = "0x10188 - PFLASH Bank 1 WOP Configuration 2"]
    pub hp_proconwop12: HP_PROCONWOP12,
    #[doc = "0x1018c - PFLASH Bank 1 WOP Configuration 3"]
    pub hp_proconwop13: HP_PROCONWOP13,
    #[doc = "0x10190 - PFLASH Bank 1 WOP Configuration 4"]
    pub hp_proconwop14: HP_PROCONWOP14,
    #[doc = "0x10194 - PFLASH Bank 1 WOP Configuration 5"]
    pub hp_proconwop15: HP_PROCONWOP15,
    _reserved72: [u8; 0x08],
    #[doc = "0x101a0 - PFLASH Bank 1 Erase Counter Priority configuration 0"]
    pub hp_ecprio10: HP_ECPRIO10,
    #[doc = "0x101a4 - PFLASH Bank 1 Erase Counter Priority Configuration 1"]
    pub hp_ecprio11: HP_ECPRIO11,
    #[doc = "0x101a8 - PFLASH Bank 1 Erase Counter Priority Configuration 2"]
    pub hp_ecprio12: HP_ECPRIO12,
    #[doc = "0x101ac - PFLASH Bank 1 Erase Counter Priority Configuration 3"]
    pub hp_ecprio13: HP_ECPRIO13,
    #[doc = "0x101b0 - PFLASH Bank 1 Erase Counter Priority Configuration 4"]
    pub hp_ecprio14: HP_ECPRIO14,
    #[doc = "0x101b4 - PFLASH Bank 1 Erase Counter Priority Configuration 5"]
    pub hp_ecprio15: HP_ECPRIO15,
    _reserved78: [u8; 0xfe58],
    #[doc = "0x20010 - HSM Flash Status Register"]
    pub sf_status: SF_STATUS,
    #[doc = "0x20014 - HSM Flash Configuration Register"]
    pub sf_control: SF_CONTROL,
    #[doc = "0x20018 - HSM Flash Operation Register"]
    pub sf_operation: SF_OPERATION,
    _reserved81: [u8; 0x14],
    #[doc = "0x20030 - HSM Enable Error Interrupt Control Register"]
    pub sf_eer: SF_EER,
    #[doc = "0x20034 - HSM Error Status Register"]
    pub sf_errsr: SF_ERRSR,
    #[doc = "0x20038 - HSM Clear Error Register"]
    pub sf_clre: SF_CLRE,
    _reserved84: [u8; 0x04],
    #[doc = "0x20040 - HSM DF1 ECC Read Register"]
    pub sf_eccr: SF_ECCR,
    #[doc = "0x20044 - HSM DF1 ECC Status Register"]
    pub sf_eccs: SF_ECCS,
    #[doc = "0x20048 - HSM DF1 ECC Control Register"]
    pub sf_eccc: SF_ECCC,
    #[doc = "0x2004c - HSM DF1 ECC Write Register"]
    pub sf_eccw: SF_ECCW,
    _reserved88: [u8; 0x24],
    #[doc = "0x20074 - HSM DF1 User Mode Control"]
    pub sf_proconusr: SF_PROCONUSR,
    _reserved89: [u8; 0x70],
    #[doc = "0x200e8 - HSM Suspend Control Register"]
    pub sf_suspend: SF_SUSPEND,
    #[doc = "0x200ec - HSM DF1 Margin Control Register"]
    pub sf_margin: SF_MARGIN,
    _reserved91: [u8; 0xff10],
    #[doc = "0x30000 - HSM Protection Configuration"]
    pub sp_proconhsmcfg: SP_PROCONHSMCFG,
    #[doc = "0x30004 - HSM Code Boot Sector"]
    pub sp_proconhsmcbs: SP_PROCONHSMCBS,
    #[doc = "0x30008 - HSM Code Exclusive Protection Configuration"]
    pub sp_proconhsmcx0: SP_PROCONHSMCX0,
    #[doc = "0x3000c - HSM Code Exclusive Protection Configuration"]
    pub sp_proconhsmcx1: SP_PROCONHSMCX1,
    #[doc = "0x30010 - HSM Code OTP Protection Configuration"]
    pub sp_proconhsmcotp0: SP_PROCONHSMCOTP0,
    #[doc = "0x30014 - HSM Code OTP Protection Configuration"]
    pub sp_proconhsmcotp1: SP_PROCONHSMCOTP1,
    _reserved97: [u8; 0x28],
    #[doc = "0x30040 - HSM Interface Protection Configuration"]
    pub sp_proconhsm: SP_PROCONHSM,
}
#[doc = "HF_ID (r) register accessor: an alias for `Reg<HF_ID_SPEC>`"]
pub type HF_ID = crate::Reg<hf_id::HF_ID_SPEC>;
#[doc = "Module Identification Register"]
pub mod hf_id;
#[doc = "HF_STATUS (r) register accessor: an alias for `Reg<HF_STATUS_SPEC>`"]
pub type HF_STATUS = crate::Reg<hf_status::HF_STATUS_SPEC>;
#[doc = "Flash Status Register"]
pub mod hf_status;
#[doc = "HF_CONTROL (rw) register accessor: an alias for `Reg<HF_CONTROL_SPEC>`"]
pub type HF_CONTROL = crate::Reg<hf_control::HF_CONTROL_SPEC>;
#[doc = "Flash Control Register"]
pub mod hf_control;
#[doc = "HF_OPERATION (r) register accessor: an alias for `Reg<HF_OPERATION_SPEC>`"]
pub type HF_OPERATION = crate::Reg<hf_operation::HF_OPERATION_SPEC>;
#[doc = "Flash Operation Register"]
pub mod hf_operation;
#[doc = "HF_PROTECT (r) register accessor: an alias for `Reg<HF_PROTECT_SPEC>`"]
pub type HF_PROTECT = crate::Reg<hf_protect::HF_PROTECT_SPEC>;
#[doc = "Flash Protection Status Register"]
pub mod hf_protect;
#[doc = "HF_CONFIRM0 (r) register accessor: an alias for `Reg<HF_CONFIRM0_SPEC>`"]
pub type HF_CONFIRM0 = crate::Reg<hf_confirm0::HF_CONFIRM0_SPEC>;
#[doc = "Flash Confirm Status Register 0"]
pub mod hf_confirm0;
#[doc = "HF_CONFIRM1 (r) register accessor: an alias for `Reg<HF_CONFIRM1_SPEC>`"]
pub type HF_CONFIRM1 = crate::Reg<hf_confirm1::HF_CONFIRM1_SPEC>;
#[doc = "Flash Confirm Status Register 1"]
pub mod hf_confirm1;
#[doc = "HF_CONFIRM2 (r) register accessor: an alias for `Reg<HF_CONFIRM2_SPEC>`"]
pub type HF_CONFIRM2 = crate::Reg<hf_confirm2::HF_CONFIRM2_SPEC>;
#[doc = "Flash Confirm Status Register 2"]
pub mod hf_confirm2;
#[doc = "HF_EER (rw) register accessor: an alias for `Reg<HF_EER_SPEC>`"]
pub type HF_EER = crate::Reg<hf_eer::HF_EER_SPEC>;
#[doc = "Enable Error Interrupt Control Register"]
pub mod hf_eer;
#[doc = "HF_ERRSR (r) register accessor: an alias for `Reg<HF_ERRSR_SPEC>`"]
pub type HF_ERRSR = crate::Reg<hf_errsr::HF_ERRSR_SPEC>;
#[doc = "Error Status Register"]
pub mod hf_errsr;
#[doc = "HF_CLRE (rw) register accessor: an alias for `Reg<HF_CLRE_SPEC>`"]
pub type HF_CLRE = crate::Reg<hf_clre::HF_CLRE_SPEC>;
#[doc = "Clear Error Register"]
pub mod hf_clre;
#[doc = "HF_ECCR (r) register accessor: an alias for `Reg<HF_ECCR_SPEC>`"]
pub type HF_ECCR = crate::Reg<hf_eccr::HF_ECCR_SPEC>;
#[doc = "DF0 ECC Read Register"]
pub mod hf_eccr;
#[doc = "HF_ECCS (r) register accessor: an alias for `Reg<HF_ECCS_SPEC>`"]
pub type HF_ECCS = crate::Reg<hf_eccs::HF_ECCS_SPEC>;
#[doc = "DF0 ECC Status Register"]
pub mod hf_eccs;
#[doc = "HF_ECCC (rw) register accessor: an alias for `Reg<HF_ECCC_SPEC>`"]
pub type HF_ECCC = crate::Reg<hf_eccc::HF_ECCC_SPEC>;
#[doc = "DF0 ECC Control Register"]
pub mod hf_eccc;
#[doc = "HF_ECCW (rw) register accessor: an alias for `Reg<HF_ECCW_SPEC>`"]
pub type HF_ECCW = crate::Reg<hf_eccw::HF_ECCW_SPEC>;
#[doc = "DF0 ECC Write Register"]
pub mod hf_eccw;
#[doc = "HF_CCONTROL (rw) register accessor: an alias for `Reg<HF_CCONTROL_SPEC>`"]
pub type HF_CCONTROL = crate::Reg<hf_ccontrol::HF_CCONTROL_SPEC>;
#[doc = "Cranking Control Register"]
pub mod hf_ccontrol;
#[doc = "HF_PSTATUS (r) register accessor: an alias for `Reg<HF_PSTATUS_SPEC>`"]
pub type HF_PSTATUS = crate::Reg<hf_pstatus::HF_PSTATUS_SPEC>;
#[doc = "Power Status Register"]
pub mod hf_pstatus;
#[doc = "HF_PCONTROL (rw) register accessor: an alias for `Reg<HF_PCONTROL_SPEC>`"]
pub type HF_PCONTROL = crate::Reg<hf_pcontrol::HF_PCONTROL_SPEC>;
#[doc = "Power Control Register"]
pub mod hf_pcontrol;
#[doc = "HF_PWAIT (rw) register accessor: an alias for `Reg<HF_PWAIT_SPEC>`"]
pub type HF_PWAIT = crate::Reg<hf_pwait::HF_PWAIT_SPEC>;
#[doc = "PFLASH Wait Cycle Register"]
pub mod hf_pwait;
#[doc = "HF_DWAIT (rw) register accessor: an alias for `Reg<HF_DWAIT_SPEC>`"]
pub type HF_DWAIT = crate::Reg<hf_dwait::HF_DWAIT_SPEC>;
#[doc = "DFLASH Wait Cycle Register"]
pub mod hf_dwait;
#[doc = "HF_PROCONUSR (r) register accessor: an alias for `Reg<HF_PROCONUSR_SPEC>`"]
pub type HF_PROCONUSR = crate::Reg<hf_proconusr::HF_PROCONUSR_SPEC>;
#[doc = "DF0 User Mode Control"]
pub mod hf_proconusr;
#[doc = "HF_PROCONPF (r) register accessor: an alias for `Reg<HF_PROCONPF_SPEC>`"]
pub type HF_PROCONPF = crate::Reg<hf_proconpf::HF_PROCONPF_SPEC>;
#[doc = "PFLASH Protection Configuration"]
pub mod hf_proconpf;
#[doc = "HF_PROCONTP (r) register accessor: an alias for `Reg<HF_PROCONTP_SPEC>`"]
pub type HF_PROCONTP = crate::Reg<hf_procontp::HF_PROCONTP_SPEC>;
#[doc = "Tuning Protection Configuration"]
pub mod hf_procontp;
#[doc = "HF_PROCONDF (r) register accessor: an alias for `Reg<HF_PROCONDF_SPEC>`"]
pub type HF_PROCONDF = crate::Reg<hf_procondf::HF_PROCONDF_SPEC>;
#[doc = "DFLASH Protection Configuration"]
pub mod hf_procondf;
#[doc = "HF_PROCONRAM (r) register accessor: an alias for `Reg<HF_PROCONRAM_SPEC>`"]
pub type HF_PROCONRAM = crate::Reg<hf_proconram::HF_PROCONRAM_SPEC>;
#[doc = "RAM Configuration"]
pub mod hf_proconram;
#[doc = "HF_PROCONDBG (r) register accessor: an alias for `Reg<HF_PROCONDBG_SPEC>`"]
pub type HF_PROCONDBG = crate::Reg<hf_procondbg::HF_PROCONDBG_SPEC>;
#[doc = "Debug Interface Protection Configuration"]
pub mod hf_procondbg;
#[doc = "HF_SUSPEND (rw) register accessor: an alias for `Reg<HF_SUSPEND_SPEC>`"]
pub type HF_SUSPEND = crate::Reg<hf_suspend::HF_SUSPEND_SPEC>;
#[doc = "Suspend Control Register"]
pub mod hf_suspend;
#[doc = "HF_MARGIN (rw) register accessor: an alias for `Reg<HF_MARGIN_SPEC>`"]
pub type HF_MARGIN = crate::Reg<hf_margin::HF_MARGIN_SPEC>;
#[doc = "Margin Control Register"]
pub mod hf_margin;
#[doc = "HF_ACCEN1 (r) register accessor: an alias for `Reg<HF_ACCEN1_SPEC>`"]
pub type HF_ACCEN1 = crate::Reg<hf_accen1::HF_ACCEN1_SPEC>;
#[doc = "Access Enable Register 1"]
pub mod hf_accen1;
#[doc = "HF_ACCEN0 (rw) register accessor: an alias for `Reg<HF_ACCEN0_SPEC>`"]
pub type HF_ACCEN0 = crate::Reg<hf_accen0::HF_ACCEN0_SPEC>;
#[doc = "Access Enable Register 0"]
pub mod hf_accen0;
#[doc = "HP_PROCONP00 (r) register accessor: an alias for `Reg<HP_PROCONP00_SPEC>`"]
pub type HP_PROCONP00 = crate::Reg<hp_proconp00::HP_PROCONP00_SPEC>;
#[doc = "PFLASH Bank 0 Protection Configuration 0"]
pub mod hp_proconp00;
#[doc = "HP_PROCONP01 (r) register accessor: an alias for `Reg<HP_PROCONP01_SPEC>`"]
pub type HP_PROCONP01 = crate::Reg<hp_proconp01::HP_PROCONP01_SPEC>;
#[doc = "PFLASH Bank 0 Protection Configuration 1"]
pub mod hp_proconp01;
#[doc = "HP_PROCONP02 (r) register accessor: an alias for `Reg<HP_PROCONP02_SPEC>`"]
pub type HP_PROCONP02 = crate::Reg<hp_proconp02::HP_PROCONP02_SPEC>;
#[doc = "PFLASH Bank 0 Protection Configuration 2"]
pub mod hp_proconp02;
#[doc = "HP_PROCONP03 (r) register accessor: an alias for `Reg<HP_PROCONP03_SPEC>`"]
pub type HP_PROCONP03 = crate::Reg<hp_proconp03::HP_PROCONP03_SPEC>;
#[doc = "PFLASH Bank 0 Protection Configuration 3"]
pub mod hp_proconp03;
#[doc = "HP_PROCONP04 (r) register accessor: an alias for `Reg<HP_PROCONP04_SPEC>`"]
pub type HP_PROCONP04 = crate::Reg<hp_proconp04::HP_PROCONP04_SPEC>;
#[doc = "PFLASH Bank 0 Protection Configuration 4"]
pub mod hp_proconp04;
#[doc = "HP_PROCONP05 (r) register accessor: an alias for `Reg<HP_PROCONP05_SPEC>`"]
pub type HP_PROCONP05 = crate::Reg<hp_proconp05::HP_PROCONP05_SPEC>;
#[doc = "PFLASH Bank 0 Protection Configuration 5"]
pub mod hp_proconp05;
#[doc = "HP_PROCONOTP00 (r) register accessor: an alias for `Reg<HP_PROCONOTP00_SPEC>`"]
pub type HP_PROCONOTP00 = crate::Reg<hp_proconotp00::HP_PROCONOTP00_SPEC>;
#[doc = "PFLASH Bank 0 OTP Protection Configuration 0"]
pub mod hp_proconotp00;
#[doc = "HP_PROCONOTP01 (r) register accessor: an alias for `Reg<HP_PROCONOTP01_SPEC>`"]
pub type HP_PROCONOTP01 = crate::Reg<hp_proconotp01::HP_PROCONOTP01_SPEC>;
#[doc = "PFLASH Bank 0 OTP Protection Configuration 1"]
pub mod hp_proconotp01;
#[doc = "HP_PROCONOTP02 (r) register accessor: an alias for `Reg<HP_PROCONOTP02_SPEC>`"]
pub type HP_PROCONOTP02 = crate::Reg<hp_proconotp02::HP_PROCONOTP02_SPEC>;
#[doc = "PFLASH Bank 0 OTP Protection Configuration 2"]
pub mod hp_proconotp02;
#[doc = "HP_PROCONOTP03 (r) register accessor: an alias for `Reg<HP_PROCONOTP03_SPEC>`"]
pub type HP_PROCONOTP03 = crate::Reg<hp_proconotp03::HP_PROCONOTP03_SPEC>;
#[doc = "PFLASH Bank 0 OTP Protection Configuration 3"]
pub mod hp_proconotp03;
#[doc = "HP_PROCONOTP04 (r) register accessor: an alias for `Reg<HP_PROCONOTP04_SPEC>`"]
pub type HP_PROCONOTP04 = crate::Reg<hp_proconotp04::HP_PROCONOTP04_SPEC>;
#[doc = "PFLASH Bank 0 OTP Protection Configuration 4"]
pub mod hp_proconotp04;
#[doc = "HP_PROCONOTP05 (r) register accessor: an alias for `Reg<HP_PROCONOTP05_SPEC>`"]
pub type HP_PROCONOTP05 = crate::Reg<hp_proconotp05::HP_PROCONOTP05_SPEC>;
#[doc = "PFLASH Bank 0 OTP Protection Configuration 5"]
pub mod hp_proconotp05;
#[doc = "HP_PROCONWOP00 (r) register accessor: an alias for `Reg<HP_PROCONWOP00_SPEC>`"]
pub type HP_PROCONWOP00 = crate::Reg<hp_proconwop00::HP_PROCONWOP00_SPEC>;
#[doc = "PFLASH Bank 0 WOP Configuration 0"]
pub mod hp_proconwop00;
#[doc = "HP_PROCONWOP01 (r) register accessor: an alias for `Reg<HP_PROCONWOP01_SPEC>`"]
pub type HP_PROCONWOP01 = crate::Reg<hp_proconwop01::HP_PROCONWOP01_SPEC>;
#[doc = "PFLASH Bank 0 WOP Configuration 1"]
pub mod hp_proconwop01;
#[doc = "HP_PROCONWOP02 (r) register accessor: an alias for `Reg<HP_PROCONWOP02_SPEC>`"]
pub type HP_PROCONWOP02 = crate::Reg<hp_proconwop02::HP_PROCONWOP02_SPEC>;
#[doc = "PFLASH Bank 0 WOP Configuration 2"]
pub mod hp_proconwop02;
#[doc = "HP_PROCONWOP03 (r) register accessor: an alias for `Reg<HP_PROCONWOP03_SPEC>`"]
pub type HP_PROCONWOP03 = crate::Reg<hp_proconwop03::HP_PROCONWOP03_SPEC>;
#[doc = "PFLASH Bank 0 WOP Configuration 3"]
pub mod hp_proconwop03;
#[doc = "HP_PROCONWOP04 (r) register accessor: an alias for `Reg<HP_PROCONWOP04_SPEC>`"]
pub type HP_PROCONWOP04 = crate::Reg<hp_proconwop04::HP_PROCONWOP04_SPEC>;
#[doc = "PFLASH Bank 0 WOP Configuration 4"]
pub mod hp_proconwop04;
#[doc = "HP_PROCONWOP05 (r) register accessor: an alias for `Reg<HP_PROCONWOP05_SPEC>`"]
pub type HP_PROCONWOP05 = crate::Reg<hp_proconwop05::HP_PROCONWOP05_SPEC>;
#[doc = "PFLASH Bank 0 WOP Configuration 5"]
pub mod hp_proconwop05;
#[doc = "HP_ECPRIO00 (r) register accessor: an alias for `Reg<HP_ECPRIO00_SPEC>`"]
pub type HP_ECPRIO00 = crate::Reg<hp_ecprio00::HP_ECPRIO00_SPEC>;
#[doc = "PFLASH Bank 0 Erase Counter Priority configuration 0"]
pub mod hp_ecprio00;
#[doc = "HP_ECPRIO01 (r) register accessor: an alias for `Reg<HP_ECPRIO01_SPEC>`"]
pub type HP_ECPRIO01 = crate::Reg<hp_ecprio01::HP_ECPRIO01_SPEC>;
#[doc = "PFLASH Bank 0 Erase Counter Priority Configuration 1"]
pub mod hp_ecprio01;
#[doc = "HP_ECPRIO02 (r) register accessor: an alias for `Reg<HP_ECPRIO02_SPEC>`"]
pub type HP_ECPRIO02 = crate::Reg<hp_ecprio02::HP_ECPRIO02_SPEC>;
#[doc = "PFLASH Bank 0 Erase Counter Priority Configuration 2"]
pub mod hp_ecprio02;
#[doc = "HP_ECPRIO03 (r) register accessor: an alias for `Reg<HP_ECPRIO03_SPEC>`"]
pub type HP_ECPRIO03 = crate::Reg<hp_ecprio03::HP_ECPRIO03_SPEC>;
#[doc = "PFLASH Bank 0 Erase Counter Priority Configuration 3"]
pub mod hp_ecprio03;
#[doc = "HP_ECPRIO04 (r) register accessor: an alias for `Reg<HP_ECPRIO04_SPEC>`"]
pub type HP_ECPRIO04 = crate::Reg<hp_ecprio04::HP_ECPRIO04_SPEC>;
#[doc = "PFLASH Bank 0 Erase Counter Priority Configuration 4"]
pub mod hp_ecprio04;
#[doc = "HP_ECPRIO05 (r) register accessor: an alias for `Reg<HP_ECPRIO05_SPEC>`"]
pub type HP_ECPRIO05 = crate::Reg<hp_ecprio05::HP_ECPRIO05_SPEC>;
#[doc = "PFLASH Bank 0 Erase Counter Priority Configuration 5"]
pub mod hp_ecprio05;
#[doc = "HP_PROCONP10 (r) register accessor: an alias for `Reg<HP_PROCONP10_SPEC>`"]
pub type HP_PROCONP10 = crate::Reg<hp_proconp10::HP_PROCONP10_SPEC>;
#[doc = "PFLASH Bank 1 Protection Configuration 0"]
pub mod hp_proconp10;
#[doc = "HP_PROCONP11 (r) register accessor: an alias for `Reg<HP_PROCONP11_SPEC>`"]
pub type HP_PROCONP11 = crate::Reg<hp_proconp11::HP_PROCONP11_SPEC>;
#[doc = "PFLASH Bank 1 Protection Configuration 1"]
pub mod hp_proconp11;
#[doc = "HP_PROCONP12 (r) register accessor: an alias for `Reg<HP_PROCONP12_SPEC>`"]
pub type HP_PROCONP12 = crate::Reg<hp_proconp12::HP_PROCONP12_SPEC>;
#[doc = "PFLASH Bank 1 Protection Configuration 2"]
pub mod hp_proconp12;
#[doc = "HP_PROCONP13 (r) register accessor: an alias for `Reg<HP_PROCONP13_SPEC>`"]
pub type HP_PROCONP13 = crate::Reg<hp_proconp13::HP_PROCONP13_SPEC>;
#[doc = "PFLASH Bank 1 Protection Configuration 3"]
pub mod hp_proconp13;
#[doc = "HP_PROCONP14 (r) register accessor: an alias for `Reg<HP_PROCONP14_SPEC>`"]
pub type HP_PROCONP14 = crate::Reg<hp_proconp14::HP_PROCONP14_SPEC>;
#[doc = "PFLASH Bank 1 Protection Configuration 4"]
pub mod hp_proconp14;
#[doc = "HP_PROCONP15 (r) register accessor: an alias for `Reg<HP_PROCONP15_SPEC>`"]
pub type HP_PROCONP15 = crate::Reg<hp_proconp15::HP_PROCONP15_SPEC>;
#[doc = "PFLASH Bank 1 Protection Configuration 5"]
pub mod hp_proconp15;
#[doc = "HP_PROCONOTP10 (r) register accessor: an alias for `Reg<HP_PROCONOTP10_SPEC>`"]
pub type HP_PROCONOTP10 = crate::Reg<hp_proconotp10::HP_PROCONOTP10_SPEC>;
#[doc = "PFLASH Bank 1 OTP Protection Configuration 0"]
pub mod hp_proconotp10;
#[doc = "HP_PROCONOTP11 (r) register accessor: an alias for `Reg<HP_PROCONOTP11_SPEC>`"]
pub type HP_PROCONOTP11 = crate::Reg<hp_proconotp11::HP_PROCONOTP11_SPEC>;
#[doc = "PFLASH Bank 1 OTP Protection Configuration 1"]
pub mod hp_proconotp11;
#[doc = "HP_PROCONOTP12 (r) register accessor: an alias for `Reg<HP_PROCONOTP12_SPEC>`"]
pub type HP_PROCONOTP12 = crate::Reg<hp_proconotp12::HP_PROCONOTP12_SPEC>;
#[doc = "PFLASH Bank 1 OTP Protection Configuration 2"]
pub mod hp_proconotp12;
#[doc = "HP_PROCONOTP13 (r) register accessor: an alias for `Reg<HP_PROCONOTP13_SPEC>`"]
pub type HP_PROCONOTP13 = crate::Reg<hp_proconotp13::HP_PROCONOTP13_SPEC>;
#[doc = "PFLASH Bank 1 OTP Protection Configuration 3"]
pub mod hp_proconotp13;
#[doc = "HP_PROCONOTP14 (r) register accessor: an alias for `Reg<HP_PROCONOTP14_SPEC>`"]
pub type HP_PROCONOTP14 = crate::Reg<hp_proconotp14::HP_PROCONOTP14_SPEC>;
#[doc = "PFLASH Bank 1 OTP Protection Configuration 4"]
pub mod hp_proconotp14;
#[doc = "HP_PROCONOTP15 (r) register accessor: an alias for `Reg<HP_PROCONOTP15_SPEC>`"]
pub type HP_PROCONOTP15 = crate::Reg<hp_proconotp15::HP_PROCONOTP15_SPEC>;
#[doc = "PFLASH Bank 1 OTP Protection Configuration 5"]
pub mod hp_proconotp15;
#[doc = "HP_PROCONWOP10 (r) register accessor: an alias for `Reg<HP_PROCONWOP10_SPEC>`"]
pub type HP_PROCONWOP10 = crate::Reg<hp_proconwop10::HP_PROCONWOP10_SPEC>;
#[doc = "PFLASH Bank 1 WOP Configuration 0"]
pub mod hp_proconwop10;
#[doc = "HP_PROCONWOP11 (r) register accessor: an alias for `Reg<HP_PROCONWOP11_SPEC>`"]
pub type HP_PROCONWOP11 = crate::Reg<hp_proconwop11::HP_PROCONWOP11_SPEC>;
#[doc = "PFLASH Bank 1 WOP Configuration 1"]
pub mod hp_proconwop11;
#[doc = "HP_PROCONWOP12 (r) register accessor: an alias for `Reg<HP_PROCONWOP12_SPEC>`"]
pub type HP_PROCONWOP12 = crate::Reg<hp_proconwop12::HP_PROCONWOP12_SPEC>;
#[doc = "PFLASH Bank 1 WOP Configuration 2"]
pub mod hp_proconwop12;
#[doc = "HP_PROCONWOP13 (r) register accessor: an alias for `Reg<HP_PROCONWOP13_SPEC>`"]
pub type HP_PROCONWOP13 = crate::Reg<hp_proconwop13::HP_PROCONWOP13_SPEC>;
#[doc = "PFLASH Bank 1 WOP Configuration 3"]
pub mod hp_proconwop13;
#[doc = "HP_PROCONWOP14 (r) register accessor: an alias for `Reg<HP_PROCONWOP14_SPEC>`"]
pub type HP_PROCONWOP14 = crate::Reg<hp_proconwop14::HP_PROCONWOP14_SPEC>;
#[doc = "PFLASH Bank 1 WOP Configuration 4"]
pub mod hp_proconwop14;
#[doc = "HP_PROCONWOP15 (r) register accessor: an alias for `Reg<HP_PROCONWOP15_SPEC>`"]
pub type HP_PROCONWOP15 = crate::Reg<hp_proconwop15::HP_PROCONWOP15_SPEC>;
#[doc = "PFLASH Bank 1 WOP Configuration 5"]
pub mod hp_proconwop15;
#[doc = "HP_ECPRIO10 (r) register accessor: an alias for `Reg<HP_ECPRIO10_SPEC>`"]
pub type HP_ECPRIO10 = crate::Reg<hp_ecprio10::HP_ECPRIO10_SPEC>;
#[doc = "PFLASH Bank 1 Erase Counter Priority configuration 0"]
pub mod hp_ecprio10;
#[doc = "HP_ECPRIO11 (r) register accessor: an alias for `Reg<HP_ECPRIO11_SPEC>`"]
pub type HP_ECPRIO11 = crate::Reg<hp_ecprio11::HP_ECPRIO11_SPEC>;
#[doc = "PFLASH Bank 1 Erase Counter Priority Configuration 1"]
pub mod hp_ecprio11;
#[doc = "HP_ECPRIO12 (r) register accessor: an alias for `Reg<HP_ECPRIO12_SPEC>`"]
pub type HP_ECPRIO12 = crate::Reg<hp_ecprio12::HP_ECPRIO12_SPEC>;
#[doc = "PFLASH Bank 1 Erase Counter Priority Configuration 2"]
pub mod hp_ecprio12;
#[doc = "HP_ECPRIO13 (r) register accessor: an alias for `Reg<HP_ECPRIO13_SPEC>`"]
pub type HP_ECPRIO13 = crate::Reg<hp_ecprio13::HP_ECPRIO13_SPEC>;
#[doc = "PFLASH Bank 1 Erase Counter Priority Configuration 3"]
pub mod hp_ecprio13;
#[doc = "HP_ECPRIO14 (r) register accessor: an alias for `Reg<HP_ECPRIO14_SPEC>`"]
pub type HP_ECPRIO14 = crate::Reg<hp_ecprio14::HP_ECPRIO14_SPEC>;
#[doc = "PFLASH Bank 1 Erase Counter Priority Configuration 4"]
pub mod hp_ecprio14;
#[doc = "HP_ECPRIO15 (r) register accessor: an alias for `Reg<HP_ECPRIO15_SPEC>`"]
pub type HP_ECPRIO15 = crate::Reg<hp_ecprio15::HP_ECPRIO15_SPEC>;
#[doc = "PFLASH Bank 1 Erase Counter Priority Configuration 5"]
pub mod hp_ecprio15;
#[doc = "SF_STATUS (r) register accessor: an alias for `Reg<SF_STATUS_SPEC>`"]
pub type SF_STATUS = crate::Reg<sf_status::SF_STATUS_SPEC>;
#[doc = "HSM Flash Status Register"]
pub mod sf_status;
#[doc = "SF_CONTROL (rw) register accessor: an alias for `Reg<SF_CONTROL_SPEC>`"]
pub type SF_CONTROL = crate::Reg<sf_control::SF_CONTROL_SPEC>;
#[doc = "HSM Flash Configuration Register"]
pub mod sf_control;
#[doc = "SF_OPERATION (r) register accessor: an alias for `Reg<SF_OPERATION_SPEC>`"]
pub type SF_OPERATION = crate::Reg<sf_operation::SF_OPERATION_SPEC>;
#[doc = "HSM Flash Operation Register"]
pub mod sf_operation;
#[doc = "SF_EER (rw) register accessor: an alias for `Reg<SF_EER_SPEC>`"]
pub type SF_EER = crate::Reg<sf_eer::SF_EER_SPEC>;
#[doc = "HSM Enable Error Interrupt Control Register"]
pub mod sf_eer;
#[doc = "SF_ERRSR (r) register accessor: an alias for `Reg<SF_ERRSR_SPEC>`"]
pub type SF_ERRSR = crate::Reg<sf_errsr::SF_ERRSR_SPEC>;
#[doc = "HSM Error Status Register"]
pub mod sf_errsr;
#[doc = "SF_CLRE (rw) register accessor: an alias for `Reg<SF_CLRE_SPEC>`"]
pub type SF_CLRE = crate::Reg<sf_clre::SF_CLRE_SPEC>;
#[doc = "HSM Clear Error Register"]
pub mod sf_clre;
#[doc = "SF_ECCR (r) register accessor: an alias for `Reg<SF_ECCR_SPEC>`"]
pub type SF_ECCR = crate::Reg<sf_eccr::SF_ECCR_SPEC>;
#[doc = "HSM DF1 ECC Read Register"]
pub mod sf_eccr;
#[doc = "SF_ECCS (r) register accessor: an alias for `Reg<SF_ECCS_SPEC>`"]
pub type SF_ECCS = crate::Reg<sf_eccs::SF_ECCS_SPEC>;
#[doc = "HSM DF1 ECC Status Register"]
pub mod sf_eccs;
#[doc = "SF_ECCC (rw) register accessor: an alias for `Reg<SF_ECCC_SPEC>`"]
pub type SF_ECCC = crate::Reg<sf_eccc::SF_ECCC_SPEC>;
#[doc = "HSM DF1 ECC Control Register"]
pub mod sf_eccc;
#[doc = "SF_ECCW (rw) register accessor: an alias for `Reg<SF_ECCW_SPEC>`"]
pub type SF_ECCW = crate::Reg<sf_eccw::SF_ECCW_SPEC>;
#[doc = "HSM DF1 ECC Write Register"]
pub mod sf_eccw;
#[doc = "SF_PROCONUSR (r) register accessor: an alias for `Reg<SF_PROCONUSR_SPEC>`"]
pub type SF_PROCONUSR = crate::Reg<sf_proconusr::SF_PROCONUSR_SPEC>;
#[doc = "HSM DF1 User Mode Control"]
pub mod sf_proconusr;
#[doc = "SF_SUSPEND (rw) register accessor: an alias for `Reg<SF_SUSPEND_SPEC>`"]
pub type SF_SUSPEND = crate::Reg<sf_suspend::SF_SUSPEND_SPEC>;
#[doc = "HSM Suspend Control Register"]
pub mod sf_suspend;
#[doc = "SF_MARGIN (rw) register accessor: an alias for `Reg<SF_MARGIN_SPEC>`"]
pub type SF_MARGIN = crate::Reg<sf_margin::SF_MARGIN_SPEC>;
#[doc = "HSM DF1 Margin Control Register"]
pub mod sf_margin;
#[doc = "SP_PROCONHSMCFG (r) register accessor: an alias for `Reg<SP_PROCONHSMCFG_SPEC>`"]
pub type SP_PROCONHSMCFG = crate::Reg<sp_proconhsmcfg::SP_PROCONHSMCFG_SPEC>;
#[doc = "HSM Protection Configuration"]
pub mod sp_proconhsmcfg;
#[doc = "SP_PROCONHSMCBS (r) register accessor: an alias for `Reg<SP_PROCONHSMCBS_SPEC>`"]
pub type SP_PROCONHSMCBS = crate::Reg<sp_proconhsmcbs::SP_PROCONHSMCBS_SPEC>;
#[doc = "HSM Code Boot Sector"]
pub mod sp_proconhsmcbs;
#[doc = "SP_PROCONHSMCX0 (r) register accessor: an alias for `Reg<SP_PROCONHSMCX0_SPEC>`"]
pub type SP_PROCONHSMCX0 = crate::Reg<sp_proconhsmcx0::SP_PROCONHSMCX0_SPEC>;
#[doc = "HSM Code Exclusive Protection Configuration"]
pub mod sp_proconhsmcx0;
#[doc = "SP_PROCONHSMCX1 (r) register accessor: an alias for `Reg<SP_PROCONHSMCX1_SPEC>`"]
pub type SP_PROCONHSMCX1 = crate::Reg<sp_proconhsmcx1::SP_PROCONHSMCX1_SPEC>;
#[doc = "HSM Code Exclusive Protection Configuration"]
pub mod sp_proconhsmcx1;
#[doc = "SP_PROCONHSMCOTP0 (r) register accessor: an alias for `Reg<SP_PROCONHSMCOTP0_SPEC>`"]
pub type SP_PROCONHSMCOTP0 = crate::Reg<sp_proconhsmcotp0::SP_PROCONHSMCOTP0_SPEC>;
#[doc = "HSM Code OTP Protection Configuration"]
pub mod sp_proconhsmcotp0;
#[doc = "SP_PROCONHSMCOTP1 (r) register accessor: an alias for `Reg<SP_PROCONHSMCOTP1_SPEC>`"]
pub type SP_PROCONHSMCOTP1 = crate::Reg<sp_proconhsmcotp1::SP_PROCONHSMCOTP1_SPEC>;
#[doc = "HSM Code OTP Protection Configuration"]
pub mod sp_proconhsmcotp1;
#[doc = "SP_PROCONHSM (r) register accessor: an alias for `Reg<SP_PROCONHSM_SPEC>`"]
pub type SP_PROCONHSM = crate::Reg<sp_proconhsm::SP_PROCONHSM_SPEC>;
#[doc = "HSM Interface Protection Configuration"]
pub mod sp_proconhsm;
